// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'product_detail_state.dart';

const DeepCollectionEquality _productDetailStateReviewsEquality = DeepCollectionEquality();
const DeepCollectionEquality _productDetailStateRecommendationsEquality = DeepCollectionEquality();

mixin _$ProductDetailState {
  @override
  String toString() {
    final self = this as ProductDetailState;
    return 'ProductDetailState('
        'productId: ${self.productId}, '
        'status: ${self.status}, '
        'reviews: ${self.reviews}, '
        'recommendations: ${self.recommendations}, '
        'errorMessage: ${self.errorMessage}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ProductDetailState;
    return identical(this, other) ||
        other is ProductDetailState &&
            runtimeType == other.runtimeType &&
            other.productId == self.productId &&
            other.status == self.status &&
            _productDetailStateReviewsEquality.equals(other.reviews, self.reviews) &&
            _productDetailStateRecommendationsEquality.equals(other.recommendations, self.recommendations) &&
            other.errorMessage == self.errorMessage;
  }

  @override
  int get hashCode {
    final self = this as ProductDetailState;
    return Object.hashAll([
      runtimeType,
      self.productId,
      self.status,
      _productDetailStateReviewsEquality.hash(self.reviews),
      _productDetailStateRecommendationsEquality.hash(self.recommendations),
      self.errorMessage,
    ]);
  }

  ProductDetailState copyWith({
    Option<int?> productId = const None(),
    ProductDetailStatus? status,
    List<ProductReview>? reviews,
    List<Product>? recommendations,
    Option<String?> errorMessage = const None(),
  }) {
    final self = this as ProductDetailState;
    final nextProductId = switch (productId) {
      None<int?>() => self.productId,
      Some<int?>(:final value) => value,
    };
    final nextReviews = List<ProductReview>.of(
      (reviews ?? self.reviews).map((item_2) => item_2.copyWith()),
    );
    final nextRecommendations = List<Product>.of(
      (recommendations ?? self.recommendations).map((item_3) => item_3.copyWith()),
    );
    final nextErrorMessage = switch (errorMessage) {
      None<String?>() => self.errorMessage,
      Some<String?>(:final value) => value,
    };

    return ProductDetailState(
      productId: nextProductId,
      status: status ?? self.status,
      reviews: nextReviews,
      recommendations: nextRecommendations,
      errorMessage: nextErrorMessage,
    );
  }
}
