// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'product_detail_state.dart';

const DeepCollectionEquality _productDetailStateReviewsEquality = DeepCollectionEquality();
const DeepCollectionEquality _productDetailStateRecommendationsEquality = DeepCollectionEquality();
final class _ProductDetailStateCopyWithUnset {
  const _ProductDetailStateCopyWithUnset();
}

const _productDetailStateCopyWithUnset = _ProductDetailStateCopyWithUnset();

mixin _$ProductDetailState {
  @override
  String toString() {
    final self = this as ProductDetailState;
    return 'ProductDetailState('
        'productId: ${self.productId}, '
        'status: ${self.status}, '
        'reviews: ${self.reviews}, '
        'recommendations: ${self.recommendations}, '
        'errorMessage: ${self.errorMessage}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ProductDetailState;
    return identical(this, other) ||
        other is ProductDetailState &&
            runtimeType == other.runtimeType &&
            other.productId == self.productId &&
            other.status == self.status &&
            _productDetailStateReviewsEquality.equals(other.reviews, self.reviews) &&
            _productDetailStateRecommendationsEquality.equals(other.recommendations, self.recommendations) &&
            other.errorMessage == self.errorMessage;
  }

  @override
  int get hashCode {
    final self = this as ProductDetailState;
    return Object.hashAll([
      runtimeType,
      self.productId,
      self.status,
      _productDetailStateReviewsEquality.hash(self.reviews),
      _productDetailStateRecommendationsEquality.hash(self.recommendations),
      self.errorMessage,
    ]);
  }

  /// Creates a copy of this `ProductDetailState` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = productDetailState.copyWith();
  /// final cleared = productDetailState.copyWith(productId: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$ProductDetailStateCopyWith<ProductDetailState> get copyWith => _$ProductDetailStateCopyWithImpl<ProductDetailState>(this as ProductDetailState, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$ProductDetailStateCopyWith<$Res> {
  $Res call({
    int? productId,
    ProductDetailStatus? status,
    List<ProductReview>? reviews,
    List<Product>? recommendations,
    String? errorMessage,
  });
}

/// @nodoc
final class _$ProductDetailStateCopyWithImpl<$Res> implements _$ProductDetailStateCopyWith<$Res> {
  const _$ProductDetailStateCopyWithImpl(this._self, this._then);

  final ProductDetailState _self;
  final $Res Function(ProductDetailState) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? productId = _productDetailStateCopyWithUnset,
    Object? status = null,
    Object? reviews = null,
    Object? recommendations = null,
    Object? errorMessage = _productDetailStateCopyWithUnset,
  }) {
    return _then(
      ProductDetailState(
        productId: identical(productId, _productDetailStateCopyWithUnset)
            ? _self.productId
            : productId as int?,
        status: status == null ? _self.status : status as ProductDetailStatus,
        reviews: reviews == null ? _self.reviews : reviews as List<ProductReview>,
        recommendations: recommendations == null ? _self.recommendations : recommendations as List<Product>,
        errorMessage: identical(errorMessage, _productDetailStateCopyWithUnset)
            ? _self.errorMessage
            : errorMessage as String?,
      )
    );
  }
}
