// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin.dart';

Router adminRoutes() => Router.module(
      prefix: '',
      routes: [
        Route('GET', '/orders', _$handleAllOrders),
        Route('GET', '/whoami', _$handleWhoAmI),
        Route('DELETE', '/orders', _$handleClearOrders),
      ],
    )..routeLayer(fromExtractor(const OrdersWrite()));

Future<Response> _$handleAllOrders(Request request) async {
  final caller = await const Extension<Caller>().extract(request);
  if (caller case Err(:final error)) return error.intoResponse();
  final caller$ = (caller as Ok<Caller, Rejection>).value;

  final store = await const StateExtractable<OrderStore>().extract(request);
  if (store case Err(:final error)) return error.intoResponse();
  final store$ = (store as Ok<OrderStore, Rejection>).value;

  return guard(() async => jsonResponse(await allOrders(caller$, store$)));
}

Future<Response> _$handleWhoAmI(Request request) async {
  final caller = await const Extension<Caller>().extract(request);
  if (caller case Err(:final error)) return error.intoResponse();
  final caller$ = (caller as Ok<Caller, Rejection>).value;

  return guard(() async => jsonResponse(await whoAmI(caller$)));
}

Future<Response> _$handleClearOrders(Request request) async {
  final caller = await const Extension<Caller>().extract(request);
  if (caller case Err(:final error)) return error.intoResponse();
  final caller$ = (caller as Ok<Caller, Rejection>).value;

  final store = await const StateExtractable<OrderStore>().extract(request);
  if (store case Err(:final error)) return error.intoResponse();
  final store$ = (store as Ok<OrderStore, Rejection>).value;

  return guard(() async {
    await clearOrders(caller$, store$);
    return noContent();
  });
}
