// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'auth_state.dart';

mixin _$AuthState {
  @override
  String toString() {
    final self = this as AuthState;
    return 'AuthState('
        'user: ${self.user}, '
        'token: ${self.token}, '
        'status: ${self.status}, '
        'errorMessage: ${self.errorMessage}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AuthState;
    return identical(this, other) ||
        other is AuthState &&
            runtimeType == other.runtimeType &&
            other.user == self.user &&
            other.token == self.token &&
            other.status == self.status &&
            other.errorMessage == self.errorMessage;
  }

  @override
  int get hashCode {
    final self = this as AuthState;
    return Object.hashAll([
      runtimeType,
      self.user,
      self.token,
      self.status,
      self.errorMessage,
    ]);
  }

  AuthState copyWith({
    Option<User?> user = const None(),
    Option<String?> token = const None(),
    AuthStatus? status,
    Option<String?> errorMessage = const None(),
  }) {
    final self = this as AuthState;
    final nextUserSource = switch (user) {
      None<User?>() => self.user,
      Some<User?>(:final value) => value,
    };
    final nextUser = nextUserSource == null ? null : nextUserSource.copyWith();
    final nextToken = switch (token) {
      None<String?>() => self.token,
      Some<String?>(:final value) => value,
    };
    final nextErrorMessage = switch (errorMessage) {
      None<String?>() => self.errorMessage,
      Some<String?>(:final value) => value,
    };

    return AuthState(
      user: nextUser,
      token: nextToken,
      status: status ?? self.status,
      errorMessage: nextErrorMessage,
    );
  }
}
