// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'register_request.dart';

mixin _$RegisterRequest {
  ValidationResult validate() {
    final self = this as RegisterRequest;
    final errors = <ValidationError>[];
    _validateRegisterRequestEmail(self.email, errors);
    _validateRegisterRequestUsername(self.username, errors);
    _validateRegisterRequestPassword(self.password, errors);
    _validateRegisterRequestConfirmPassword(self, self.confirmPassword, errors);
    _validateRegisterRequestFirstName(self.firstName, errors);
    _validateRegisterRequestLastName(self.lastName, errors);
    _validateRegisterRequestPhone(self.phone, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(:final errors)) {
      throw ValidationException(errors);
    }
  }
}


void _validateRegisterRequestEmail(String email, List<ValidationError> errors) {
  if (email.length < 1) {
    errors.add(ValidationError(field: 'email', message: 'Please enter email'));
  }
  if (!ValidationHelper.isEmail(email)) {
    errors.add(ValidationError(field: 'email', message: 'Please enter a valid email'));
  }
}

String? validateRegisterRequestEmailInput(String? value) {
  final errors = <ValidationError>[];
  _validateRegisterRequestEmail(value ?? '', errors);
  return errors.isEmpty ? null : errors.first.message;
}

void _validateRegisterRequestUsername(String username, List<ValidationError> errors) {
  if (username.length < 1) {
    errors.add(ValidationError(field: 'username', message: 'Please enter username'));
  }
  if (username.length < 3) {
    errors.add(ValidationError(field: 'username', message: 'Username must be at least 3 characters'));
  }
}

String? validateRegisterRequestUsernameInput(String? value) {
  final errors = <ValidationError>[];
  _validateRegisterRequestUsername(value ?? '', errors);
  return errors.isEmpty ? null : errors.first.message;
}

void _validateRegisterRequestPassword(String password, List<ValidationError> errors) {
  if (password.length < 1) {
    errors.add(ValidationError(field: 'password', message: 'Please enter password'));
  }
  if (password.length < 6) {
    errors.add(ValidationError(field: 'password', message: 'Password must be at least 6 characters'));
  }
}

String? validateRegisterRequestPasswordInput(String? value) {
  final errors = <ValidationError>[];
  _validateRegisterRequestPassword(value ?? '', errors);
  return errors.isEmpty ? null : errors.first.message;
}

void _validateRegisterRequestConfirmPassword(
  RegisterRequest self,
  String confirmPassword,
  List<ValidationError> errors,
) {
  if (confirmPassword.length < 1) {
    errors.add(ValidationError(field: 'confirmPassword', message: 'Please confirm password'));
  }
  if (confirmPassword != self.password) {
    errors.add(ValidationError(field: 'confirmPassword', message: 'Passwords do not match'));
  }
}

String? validateRegisterRequestConfirmPasswordInput(
  RegisterRequest self,
  String? value,
) {
  final errors = <ValidationError>[];
  _validateRegisterRequestConfirmPassword(self, value ?? '', errors);
  return errors.isEmpty ? null : errors.first.message;
}

void _validateRegisterRequestFirstName(String firstName, List<ValidationError> errors) {
  if (firstName.length < 1) {
    errors.add(ValidationError(field: 'firstName', message: 'Required'));
  }
}

String? validateRegisterRequestFirstNameInput(String? value) {
  final errors = <ValidationError>[];
  _validateRegisterRequestFirstName(value ?? '', errors);
  return errors.isEmpty ? null : errors.first.message;
}

void _validateRegisterRequestLastName(String lastName, List<ValidationError> errors) {
  if (lastName.length < 1) {
    errors.add(ValidationError(field: 'lastName', message: 'Required'));
  }
}

String? validateRegisterRequestLastNameInput(String? value) {
  final errors = <ValidationError>[];
  _validateRegisterRequestLastName(value ?? '', errors);
  return errors.isEmpty ? null : errors.first.message;
}

void _validateRegisterRequestPhone(String phone, List<ValidationError> errors) {
  if (phone.length < 1) {
    errors.add(ValidationError(field: 'phone', message: 'Please enter phone number'));
  }
}

String? validateRegisterRequestPhoneInput(String? value) {
  final errors = <ValidationError>[];
  _validateRegisterRequestPhone(value ?? '', errors);
  return errors.isEmpty ? null : errors.first.message;
}
