// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'register_request.dart';

mixin _$RegisterRequest {
  /// Validates this `RegisterRequest`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as RegisterRequest;
    final errors = <ValidationError>[];
    _RegisterRequestValidation._validateEmail(self.email, errors);
    _RegisterRequestValidation._validateUsername(self.username, errors);
    _RegisterRequestValidation._validatePassword(self.password, errors);
    _RegisterRequestValidation._validateConfirmPassword(self, self.confirmPassword, errors);
    _RegisterRequestValidation._validateFirstName(self.firstName, errors);
    _RegisterRequestValidation._validateLastName(self.lastName, errors);
    _RegisterRequestValidation._validatePhone(self.phone, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `RegisterRequest` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }
}

/// TextFormField validator for `RegisterRequest.email`.
///
/// Usage:
/// ```dart
/// TextFormField(
///   validator: validateRegisterRequestEmailInput,
/// )
/// ```
String? validateRegisterRequestEmailInput(String? value) {
  return _RegisterRequestValidation.validateEmailInput(value);
}

/// TextFormField validator for `RegisterRequest.username`.
///
/// Usage:
/// ```dart
/// TextFormField(
///   validator: validateRegisterRequestUsernameInput,
/// )
/// ```
String? validateRegisterRequestUsernameInput(String? value) {
  return _RegisterRequestValidation.validateUsernameInput(value);
}

/// TextFormField validator for `RegisterRequest.password`.
///
/// Usage:
/// ```dart
/// TextFormField(
///   validator: validateRegisterRequestPasswordInput,
/// )
/// ```
String? validateRegisterRequestPasswordInput(String? value) {
  return _RegisterRequestValidation.validatePasswordInput(value);
}

/// TextFormField validator for `RegisterRequest.confirmPassword`.
///
/// Usage:
/// ```dart
/// TextFormField(
///   validator: (value) => validateRegisterRequestConfirmPasswordInput(self, value),
/// )
/// ```
String? validateRegisterRequestConfirmPasswordInput(
  RegisterRequest self,
  String? value,
) {
  return _RegisterRequestValidation.validateConfirmPasswordInput(self, value);
}

/// TextFormField validator for `RegisterRequest.firstName`.
///
/// Usage:
/// ```dart
/// TextFormField(
///   validator: validateRegisterRequestFirstNameInput,
/// )
/// ```
String? validateRegisterRequestFirstNameInput(String? value) {
  return _RegisterRequestValidation.validateFirstNameInput(value);
}

/// TextFormField validator for `RegisterRequest.lastName`.
///
/// Usage:
/// ```dart
/// TextFormField(
///   validator: validateRegisterRequestLastNameInput,
/// )
/// ```
String? validateRegisterRequestLastNameInput(String? value) {
  return _RegisterRequestValidation.validateLastNameInput(value);
}

/// TextFormField validator for `RegisterRequest.phone`.
///
/// Usage:
/// ```dart
/// TextFormField(
///   validator: validateRegisterRequestPhoneInput,
/// )
/// ```
String? validateRegisterRequestPhoneInput(String? value) {
  return _RegisterRequestValidation.validatePhoneInput(value);
}

extension _RegisterRequestValidation on RegisterRequest {
  static void _validateEmail(String email, List<ValidationError> errors) {
    if (email.length < 1) {
      errors.add(ValidationError(field: 'email', message: 'Please enter email'));
    }
    if (!ValidationHelper.isEmail(email)) {
      errors.add(ValidationError(field: 'email', message: 'Please enter a valid email'));
    }
  }

  static String? validateEmailInput(String? value) {
    final errors = <ValidationError>[];
    _validateEmail(value ?? '', errors);
    return errors.isEmpty ? null : errors.first.message;
  }

  static void _validateUsername(String username, List<ValidationError> errors) {
    if (username.length < 1) {
      errors.add(ValidationError(field: 'username', message: 'Please enter username'));
    }
    if (username.length < 3) {
      errors.add(ValidationError(field: 'username', message: 'Username must be at least 3 characters'));
    }
  }

  static String? validateUsernameInput(String? value) {
    final errors = <ValidationError>[];
    _validateUsername(value ?? '', errors);
    return errors.isEmpty ? null : errors.first.message;
  }

  static void _validatePassword(String password, List<ValidationError> errors) {
    if (password.length < 1) {
      errors.add(ValidationError(field: 'password', message: 'Please enter password'));
    }
    if (password.length < 6) {
      errors.add(ValidationError(field: 'password', message: 'Password must be at least 6 characters'));
    }
  }

  static String? validatePasswordInput(String? value) {
    final errors = <ValidationError>[];
    _validatePassword(value ?? '', errors);
    return errors.isEmpty ? null : errors.first.message;
  }

  static void _validateConfirmPassword(
    RegisterRequest self,
    String confirmPassword,
    List<ValidationError> errors,
  ) {
    if (confirmPassword.length < 1) {
      errors.add(ValidationError(field: 'confirmPassword', message: 'Please confirm password'));
    }
    if (confirmPassword != self.password) {
      errors.add(ValidationError(field: 'confirmPassword', message: 'Passwords do not match'));
    }
  }

  static String? validateConfirmPasswordInput(
    RegisterRequest self,
    String? value,
  ) {
    final errors = <ValidationError>[];
    _validateConfirmPassword(self, value ?? '', errors);
    return errors.isEmpty ? null : errors.first.message;
  }

  static void _validateFirstName(String firstName, List<ValidationError> errors) {
    if (firstName.length < 1) {
      errors.add(ValidationError(field: 'firstName', message: 'Required'));
    }
  }

  static String? validateFirstNameInput(String? value) {
    final errors = <ValidationError>[];
    _validateFirstName(value ?? '', errors);
    return errors.isEmpty ? null : errors.first.message;
  }

  static void _validateLastName(String lastName, List<ValidationError> errors) {
    if (lastName.length < 1) {
      errors.add(ValidationError(field: 'lastName', message: 'Required'));
    }
  }

  static String? validateLastNameInput(String? value) {
    final errors = <ValidationError>[];
    _validateLastName(value ?? '', errors);
    return errors.isEmpty ? null : errors.first.message;
  }

  static void _validatePhone(String phone, List<ValidationError> errors) {
    if (phone.length < 1) {
      errors.add(ValidationError(field: 'phone', message: 'Please enter phone number'));
    }
  }

  static String? validatePhoneInput(String? value) {
    final errors = <ValidationError>[];
    _validatePhone(value ?? '', errors);
    return errors.isEmpty ? null : errors.first.message;
  }

}
