// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'products_view_model.dart';

enum _ProductsViewModelAspect { products, status, errorMessage, selectedCategory, searchQuery, sortOption }

abstract class $ProductsViewModel extends ViewModelBase<ProductsState, ProductsViewModelArgs> {
  $ProductsViewModel(super.args) : super(initialState: const ProductsState());
}

class _$ProductsViewModelProxy {
  _$ProductsViewModelProxy(this._context, this._vm);

  final BuildContext _context;
  final ProductsViewModel _vm;

  ProductsState get value {
    ProductsViewModelScope.of(_context);
    return _vm.value;
  }

  List<Product> get products {
    ProductsViewModelScope.of(_context, aspect: _ProductsViewModelAspect.products);
    return _vm.state.products;
  }

  ProductsStatus get status {
    ProductsViewModelScope.of(_context, aspect: _ProductsViewModelAspect.status);
    return _vm.state.status;
  }

  String? get errorMessage {
    ProductsViewModelScope.of(_context, aspect: _ProductsViewModelAspect.errorMessage);
    return _vm.state.errorMessage;
  }

  String? get selectedCategory {
    ProductsViewModelScope.of(_context, aspect: _ProductsViewModelAspect.selectedCategory);
    return _vm.state.selectedCategory;
  }

  String get searchQuery {
    ProductsViewModelScope.of(_context, aspect: _ProductsViewModelAspect.searchQuery);
    return _vm.state.searchQuery;
  }

  ProductSortOption get sortOption {
    ProductsViewModelScope.of(_context, aspect: _ProductsViewModelAspect.sortOption);
    return _vm.state.sortOption;
  }
}

class ProductsViewModelScope extends StatefulWidget {
  const ProductsViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
  }) : value = null;

  const ProductsViewModelScope.value({
    super.key,
    required ProductsViewModel this.value,
    required this.child,
  }) : args = null,
       create = null;

  final ProductsViewModelArgs Function(BuildContext context)? args;
  final ProductsViewModel Function(BuildContext context, ProductsViewModelArgs args)? create;
  final ProductsViewModel? value;
  final Widget child;

  static ProductsViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_ProductsViewModelInherited>()
        ?.widget as _ProductsViewModelInherited?;
    if (scope == null) throw StateError('No ProductsViewModelScope found in context.');
    return scope.viewModel;
  }

  static ProductsViewModel of(BuildContext context, {Object? aspect}) {
    final scope = context.dependOnInheritedWidgetOfExactType<_ProductsViewModelInherited>(
      aspect: aspect,
    );
    if (scope == null) throw StateError('No ProductsViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<ProductsViewModelScope> createState() => _ProductsViewModelScopeState();
}

class _ProductsViewModelScopeState extends State<ProductsViewModelScope> {
  @override
  Widget build(BuildContext context) {
    final external = widget.value;
    return external == null
        ? ViewModelOwner<ProductsViewModel, ProductsViewModelArgs>(
            debugName: 'ProductsViewModelScope',
            args: widget.args!,
            create: widget.create!,
            builder: _buildInherited,
          )
        : ViewModelOwner<ProductsViewModel, ProductsViewModelArgs>.value(
            debugName: 'ProductsViewModelScope.value',
            value: external,
            builder: _buildInherited,
          );
  }

  Widget _buildInherited(BuildContext context, ProductsViewModel viewModel) {
    return ListenableBuilder(
      listenable: viewModel,
      builder: (context, child) => _ProductsViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: child!,
      ),
      child: widget.child,
    );
  }
}

class _ProductsViewModelInherited extends InheritedModel<Object> {
  const _ProductsViewModelInherited({required this.viewModel, required this.state, required super.child});

  final ProductsViewModel viewModel;
  final ProductsState state;

  @override
  bool updateShouldNotify(_ProductsViewModelInherited oldWidget) => state != oldWidget.state;

  @override
  bool updateShouldNotifyDependent(_ProductsViewModelInherited oldWidget, Set<Object> dependencies) {
    for (final aspect in dependencies) {
      switch (aspect) {
        case _ProductsViewModelAspect.products:
          if (state.products != oldWidget.state.products) {
            return true;
          }
          break;
        case _ProductsViewModelAspect.status:
          if (state.status != oldWidget.state.status) {
            return true;
          }
          break;
        case _ProductsViewModelAspect.errorMessage:
          if (state.errorMessage != oldWidget.state.errorMessage) {
            return true;
          }
          break;
        case _ProductsViewModelAspect.selectedCategory:
          if (state.selectedCategory != oldWidget.state.selectedCategory) {
            return true;
          }
          break;
        case _ProductsViewModelAspect.searchQuery:
          if (state.searchQuery != oldWidget.state.searchQuery) {
            return true;
          }
          break;
        case _ProductsViewModelAspect.sortOption:
          if (state.sortOption != oldWidget.state.sortOption) {
            return true;
          }
          break;
        default:
          break;
      }
    }
    return false;
  }
}

class ProductsViewModelListener extends StatefulWidget {
  const ProductsViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<ProductsViewModelListener> createState() => _ProductsViewModelListenerState();
}

class _ProductsViewModelListenerState extends State<ProductsViewModelListener> {
  StreamSubscription<Object>? _sub;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _sub?.cancel();
    _sub = ProductsViewModelScope.read(context).effects.listen((effect) {
      if (mounted) widget.listener(context, effect);
    });
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

extension ProductsViewModelBuildContext on BuildContext {
  ProductsViewModel get productsViewModel => ProductsViewModelScope.of(this);

  _$ProductsViewModelProxy watchProductsViewModel() {
    return _$ProductsViewModelProxy(this, ProductsViewModelScope.read(this));
  }

  ProductsViewModel readProductsViewModel() => ProductsViewModelScope.read(this);
}
