// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'stock_model.dart';

mixin _$Stock implements Serializable {
  @override
  String toString() {
    final self = this as Stock;
    return 'Stock('
        'item: ${self.item}, '
        'onHand: ${self.onHand}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Stock;
    return identical(this, other) ||
        other is Stock &&
            runtimeType == other.runtimeType &&
            other.item == self.item &&
            other.onHand == self.onHand;
  }

  @override
  int get hashCode {
    final self = this as Stock;
    return Object.hashAll([
      runtimeType,
      self.item,
      self.onHand,
    ]);
  }

  Map<String, Object?> serialize() => _$StockSerialize(this as Stock);

  Map<String, Object?> toJson() => serialize();
}

final class $StockSerializer implements Serializer<Stock, Map<String, Object?>> {
  const $StockSerializer();

  @override
  Map<String, Object?> serialize(Stock value) => _$StockSerialize(value);
}
extension StockFromRow on Stock {
  static Stock fromRow(Row row) {
    return Stock(
      item: row.read<String>('item'),
      onHand: row.read<int>('on_hand'),
    );
  }
}

/// Row deserializer for [Stock].
///
/// Pass it as the `using:` argument of a typed row query, so a row type with
/// no mapping is an analyzer error rather than a failure on the first request.
final class $StockFromRow implements RowDeserializer<Stock> {
  const $StockFromRow();

  @override
  Stock deserialize(Row row) => StockFromRow.fromRow(row);
}

Map<String, Object?> _$StockSerialize(Stock instance) {
  return <String, Object?>{
    'item': instance.item,
    'onHand': instance.onHand,
  };
}

Map<String, Object?> _$StockToJson(Stock instance) =>
    _$StockSerialize(instance);
