// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

import 'package:flutter/material.dart' hide Route;

import 'route.dart';
import 'package:dust_router/dust_router.dart';
import 'package:dust_test/pages/dashboard_page.dart';
import 'package:dust_test/pages/not_found_page.dart';

abstract class $AppRouter extends DustRouterBase<AppRoutePath> {
  RouterConfig<AppRoutePath> get config {
    final runtimeConfig = DustRouterConfig<AppRoutePath>(
      router: this,
      initialRoute: const DashboardRoute(),
      parseRoute: parseAppRoute,
      routeLocation: routeLocation,
      requiresAuth: routeRequiresAuth,
      resolveGuards: (route) => routeGuards(route, this),
      buildPage: buildAppRoutePage,
    );
    final delegate = DustRouterDelegate<AppRoutePath>(runtimeConfig);
    return RouterConfig<AppRoutePath>(
      routeInformationProvider: PlatformRouteInformationProvider(
        initialRouteInformation: RouteInformation(
          uri: Uri.parse(
            WidgetsBinding.instance.platformDispatcher.defaultRouteName,
          ),
        ),
      ),
      routeInformationParser: DustRouteInformationParser<AppRoutePath>(
        parseRoute: parseAppRoute,
        routeLocation: routeLocation,
      ),
      routerDelegate: delegate,
      backButtonDispatcher: RootBackButtonDispatcher(),
    );
  }
}

const List<GeneratedRoute> $appRoutes = [
  GeneratedRoute('/', page: DashboardPage, name: 'dashboard'),
  GeneratedRoute(
    '/404',
    routes: [
      GeneratedRoute(':path', page: NotFoundPage, name: 'notFound', guards: []),
    ],
  ),
];

typedef RouteState = DustRouteState<AppRoutePath>;

sealed class AppRoutePath {
  const AppRoutePath();

  String get location;

  /// Defaults to true. Override and return false for public routes
  /// (login, invite, forbidden, checkout, notFound).
  bool get requiresAuth => true;
}

final class DashboardRoute extends AppRoutePath {
  const DashboardRoute();

  @override
  String get location {
    return '/';
  }
}

final class NotFoundRoute extends AppRoutePath {
  const NotFoundRoute({required this.path});

  final String path;

  @override
  String get location {
    return '/404?path=${Uri.encodeComponent(path)}';
  }

  @override
  bool get requiresAuth => false;
}

String routeLocation(AppRoutePath route) => route.location;

String _routePath(
  List<String> segments, {
  Map<String, String>? queryParameters,
}) {
  final query = queryParameters?.isEmpty ?? true ? null : queryParameters;
  final text = Uri(pathSegments: segments, queryParameters: query).toString();
  if (text.isEmpty) return '/';
  return text.startsWith('/') ? text : '/$text';
}

bool routeRequiresAuth(AppRoutePath route) => route.requiresAuth;

List<RouteGuard<AppRoutePath>> routeGuards(
  AppRoutePath route,
  $AppRouter router,
) {
  return switch (route) {
    _ => const [],
  };
}

extension DustRouterContext on BuildContext {
  DustRouterController<AppRoutePath> get router =>
      DustRouter.of<AppRoutePath>(this);
  AppRoutesNavigation get routes => AppRoutesNavigation(router);
}

final class AppRoutesNavigation {
  const AppRoutesNavigation(this._router);

  final DustRouterController<AppRoutePath> _router;

  RouteNavigation<AppRoutePath> dashboard() =>
      RouteNavigation(_router, DashboardRoute());

  RouteNavigation<AppRoutePath> notFound({required String path}) =>
      RouteNavigation(_router, NotFoundRoute(path: path));

  void pop() => _router.pop();
}

final class RouteNavigation<T extends Object> {
  const RouteNavigation(this._router, this.route);

  final DustRouterController<T> _router;
  final T route;

  void go() => _router.go(route);
  void push() => _router.push(route);
  void replace() => _router.replace(route);
}

AppRoutePath parseAppRoute(Uri uri) {
  final segments = uri.pathSegments;

  if (segments.isEmpty) {
    return DashboardRoute();
  }

  if (segments.length == 1 && segments[0] == '404') {
    return NotFoundRoute(path: uri.queryParameters['path'] ?? '');
  }

  return _notFoundRoute(uri);
}

AppRoutePath _notFoundRoute(Uri uri) => NotFoundRoute(path: uri.toString());

bool? _parseBool(String? value) {
  return switch (value) {
    'true' || '1' => true,
    'false' || '0' => false,
    null || '' => null,
    _ => () {
      assert(
        false,
        '_parseBool: unrecognised value "$value", treating as null',
      );
      return null;
    }(),
  };
}

const Map<Type, Type?> _kAppliedShellsByPage = {
  DashboardPage: null,
  NotFoundPage: null,
};

bool _shellConsistencyCheck() {
  bool visit(GeneratedRoute route) {
    final page = route.page;
    if (page != null && _kAppliedShellsByPage[page] != route.shell) {
      return false;
    }
    return route.routes.every(visit);
  }

  return $appRoutes.every(visit);
}

Page<void> buildAppRoutePage(AppRoutePath route) {
  assert(
    _shellConsistencyCheck(),
    'Shell mismatch between \$appRoutes and buildAppRoutePage',
  );
  return switch (route) {
    DashboardRoute() => generatedPage(
      location: route.location,
      name: 'dashboard',
      fullscreenDialog: false,
      maintainState: true,
      child: const DashboardPage(),
    ),
    NotFoundRoute(path: final path) => generatedPage(
      location: route.location,
      name: 'notFound',
      fullscreenDialog: false,
      maintainState: true,
      child: NotFoundPage(path: path),
    ),
  };
}
