// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by dust.

// ignore_for_file: unused_import, unnecessary_import

import 'package:flutter/material.dart' hide Route;

import 'route.dart';
import 'package:dust_router/dust_router.dart';
import 'package:routing_prototype/app_state.dart';
import 'package:routing_prototype/layout/app_shell.dart';
import 'package:routing_prototype/pages/admin_page.dart';
import 'package:routing_prototype/pages/checkout_page.dart';
import 'package:routing_prototype/pages/dashboard_page.dart';
import 'package:routing_prototype/pages/forbidden_page.dart';
import 'package:routing_prototype/pages/invite_page.dart';
import 'package:routing_prototype/pages/invoice_page.dart';
import 'package:routing_prototype/pages/login_page.dart';
import 'package:routing_prototype/pages/not_found_page.dart';
import 'package:routing_prototype/pages/page_scaffold.dart';
import 'package:routing_prototype/pages/post_detail_page.dart';
import 'package:routing_prototype/pages/project_page.dart';
import 'package:routing_prototype/pages/project_settings_page.dart';
import 'package:routing_prototype/pages/search_page.dart';

class _NoTransitionBuilder extends PageTransitionsBuilder {
  const _NoTransitionBuilder();

  @override
  Widget buildTransitions<T>(
    PageRoute<T> route,
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
    Widget child,
  ) {
    return child;
  }
}

abstract class $AppRouter extends DustRouterBase<AppRoutePath> {
  RouterConfig<AppRoutePath> get config {
    final runtimeConfig = DustRouterConfig<AppRoutePath>(
      router: this,
      initialRoute: const DashboardRoute(),
      parseRoute: parseAppRoute,
      routeLocation: routeLocation,
      requiresAuth: routeRequiresAuth,
      resolveGuards: (route) => routeGuards(route, this),
      buildPage: buildAppRoutePage,
    );
    final delegate = DustRouterDelegate<AppRoutePath>(runtimeConfig);
    return RouterConfig<AppRoutePath>(
      routeInformationProvider: PlatformRouteInformationProvider(
        initialRouteInformation: RouteInformation(
          uri: Uri.parse(
            WidgetsBinding.instance.platformDispatcher.defaultRouteName,
          ),
        ),
      ),
      routeInformationParser: DustRouteInformationParser<AppRoutePath>(
        parseRoute: parseAppRoute,
        routeLocation: routeLocation,
      ),
      routerDelegate: delegate,
      backButtonDispatcher: RootBackButtonDispatcher(),
    );
  }

  AdminGuard createAdminGuard();

  BillingGuard createBillingGuard();
}

const List<GeneratedRoute> $appRoutes = [
  GeneratedRoute(
    '/',
    page: DashboardPage,
    name: 'dashboard',
    shell: AppShell,
    transition: FadeUpwardsPageTransitionsBuilder(),
  ),
  GeneratedRoute(
    '/404',
    routes: [
      GeneratedRoute(
        ':path',
        page: NotFoundPage,
        name: 'notFound',
        guards: [],
        transition: FadeUpwardsPageTransitionsBuilder(),
      ),
    ],
  ),
  GeneratedRoute(
    '/admin',
    page: AdminPage,
    name: 'admin',
    shell: AppShell,
    guards: [AdminGuard],
  ),
  GeneratedRoute(
    '/billing',
    routes: [
      GeneratedRoute(
        'invoices',
        routes: [
          GeneratedRoute(
            ':invoiceId',
            page: InvoicePage,
            name: 'invoice',
            shell: AppShell,
            guards: [BillingGuard],
          ),
        ],
      ),
    ],
  ),
  GeneratedRoute(
    '/checkout',
    routes: [
      GeneratedRoute(
        ':plan',
        page: CheckoutPage,
        name: 'checkout',
        guards: [],
        transition: BottomToTopPageTransitionsBuilder(),
        fullscreenDialog: true,
      ),
    ],
  ),
  GeneratedRoute(
    '/forbidden',
    page: ForbiddenPage,
    name: 'forbidden',
    guards: [],
    transition: FadeUpwardsPageTransitionsBuilder(),
  ),
  GeneratedRoute(
    '/invite',
    routes: [
      GeneratedRoute(':token', page: InvitePage, name: 'invite', guards: []),
    ],
  ),
  GeneratedRoute(
    '/login',
    page: LoginPage,
    name: 'login',
    guards: [],
    transition: CupertinoPageTransitionsBuilder(),
  ),
  GeneratedRoute(
    '/posts',
    routes: [
      GeneratedRoute(
        ':id',
        page: PostDetailPage,
        name: 'postDetail',
        transition: CupertinoPageTransitionsBuilder(),
      ),
    ],
  ),
  GeneratedRoute(
    '/projects',
    routes: [
      GeneratedRoute(
        ':projectId',
        page: ProjectPage,
        name: 'project',
        shell: AppShell,
        routes: [
          GeneratedRoute(
            'settings',
            page: ProjectSettingsPage,
            name: 'projectSettings',
            shell: AppShell,
          ),
        ],
      ),
    ],
  ),
  GeneratedRoute(
    '/search',
    page: SearchPage,
    name: 'search',
    shell: AppShell,
    transition: _NoTransitionBuilder(),
  ),
];

typedef RouteState = DustRouteState<AppRoutePath>;

sealed class AppRoutePath {
  const AppRoutePath();

  String get location;

  /// Defaults to true. Override and return false for public routes
  /// (login, invite, forbidden, checkout, notFound).
  bool get requiresAuth => true;
}

final class DashboardRoute extends AppRoutePath {
  const DashboardRoute();

  @override
  String get location {
    return '/';
  }
}

final class NotFoundRoute extends AppRoutePath {
  const NotFoundRoute({required this.path});

  final String path;

  @override
  String get location {
    return '/404?path=${Uri.encodeComponent(path)}';
  }

  @override
  bool get requiresAuth => false;
}

final class AdminRoute extends AppRoutePath {
  const AdminRoute();

  @override
  String get location {
    return _routePath(['admin']);
  }
}

final class InvoiceRoute extends AppRoutePath {
  const InvoiceRoute({required this.invoiceId, this.download = false});

  final String invoiceId;
  final bool download;

  @override
  String get location {
    final query = <String, String>{};
    if (download != false) {
      query['download'] = download.toString();
    }
    return _routePath([
      'billing',
      'invoices',
      invoiceId,
    ], queryParameters: query.isEmpty ? null : query);
  }
}

final class CheckoutRoute extends AppRoutePath {
  const CheckoutRoute({required this.plan, this.annual = false});

  final String plan;
  final bool annual;

  @override
  String get location {
    final query = <String, String>{};
    if (annual != false) {
      query['annual'] = annual.toString();
    }
    return _routePath([
      'checkout',
      plan,
    ], queryParameters: query.isEmpty ? null : query);
  }

  @override
  bool get requiresAuth => false;
}

final class ForbiddenRoute extends AppRoutePath {
  const ForbiddenRoute();

  @override
  String get location {
    return _routePath(['forbidden']);
  }

  @override
  bool get requiresAuth => false;
}

final class InviteRoute extends AppRoutePath {
  const InviteRoute({required this.token});

  final String token;

  @override
  String get location {
    return _routePath(['invite', token]);
  }

  @override
  bool get requiresAuth => false;
}

final class LoginRoute extends AppRoutePath {
  const LoginRoute({this.from});

  final String? from;

  @override
  String get location {
    final query = <String, String>{};
    if (from != null) {
      query['from'] = from!;
    }
    return _routePath(['login'], queryParameters: query.isEmpty ? null : query);
  }

  @override
  bool get requiresAuth => false;
}

final class PostDetailRoute extends AppRoutePath {
  const PostDetailRoute({required this.id});

  final int id;

  @override
  String get location {
    return _routePath(['posts', id.toString()]);
  }
}

final class ProjectRoute extends AppRoutePath {
  const ProjectRoute({required this.projectId, this.tab});

  final int projectId;
  final String? tab;

  @override
  String get location {
    final query = <String, String>{};
    if (tab != null) {
      query['tab'] = tab!;
    }
    return _routePath([
      'projects',
      projectId.toString(),
    ], queryParameters: query.isEmpty ? null : query);
  }
}

final class ProjectSettingsRoute extends AppRoutePath {
  const ProjectSettingsRoute({
    required this.projectId,
    this.section = 'general',
  });

  final int projectId;
  final String section;

  @override
  String get location {
    final query = <String, String>{};
    if (section != 'general') {
      query['section'] = section;
    }
    return _routePath([
      'projects',
      projectId.toString(),
      'settings',
    ], queryParameters: query.isEmpty ? null : query);
  }
}

final class SearchRoute extends AppRoutePath {
  const SearchRoute({this.q, this.page = 1});

  final String? q;
  final int page;

  @override
  String get location {
    final query = <String, String>{};
    if (q != null) {
      query['q'] = q!;
    }
    if (page != 1) {
      query['page'] = page.toString();
    }
    return _routePath([
      'search',
    ], queryParameters: query.isEmpty ? null : query);
  }
}

String routeLocation(AppRoutePath route) => route.location;

String _routePath(
  List<String> segments, {
  Map<String, String>? queryParameters,
}) {
  final query = queryParameters?.isEmpty ?? true ? null : queryParameters;
  final text = Uri(pathSegments: segments, queryParameters: query).toString();
  if (text.isEmpty) return '/';
  return text.startsWith('/') ? text : '/$text';
}

bool routeRequiresAuth(AppRoutePath route) => route.requiresAuth;

List<RouteGuard<AppRoutePath>> routeGuards(
  AppRoutePath route,
  $AppRouter router,
) {
  return switch (route) {
    AdminRoute() => [router.createAdminGuard()],
    InvoiceRoute() => [router.createBillingGuard()],
    _ => const [],
  };
}

extension DustRouterContext on BuildContext {
  DustRouterController<AppRoutePath> get router =>
      DustRouter.of<AppRoutePath>(this);
  AppRoutesNavigation get routes => AppRoutesNavigation(router);
}

final class AppRoutesNavigation {
  const AppRoutesNavigation(this._router);

  final DustRouterController<AppRoutePath> _router;

  RouteNavigation<AppRoutePath> dashboard() =>
      RouteNavigation(_router, DashboardRoute());

  RouteNavigation<AppRoutePath> notFound({required String path}) =>
      RouteNavigation(_router, NotFoundRoute(path: path));

  RouteNavigation<AppRoutePath> admin() =>
      RouteNavigation(_router, AdminRoute());

  RouteNavigation<AppRoutePath> invoice({
    required String invoiceId,
    bool download = false,
  }) => RouteNavigation(
    _router,
    InvoiceRoute(invoiceId: invoiceId, download: download),
  );

  RouteNavigation<AppRoutePath> checkout({
    required String plan,
    bool annual = false,
  }) => RouteNavigation(_router, CheckoutRoute(plan: plan, annual: annual));

  RouteNavigation<AppRoutePath> forbidden() =>
      RouteNavigation(_router, ForbiddenRoute());

  RouteNavigation<AppRoutePath> invite({required String token}) =>
      RouteNavigation(_router, InviteRoute(token: token));

  RouteNavigation<AppRoutePath> login({String? from}) =>
      RouteNavigation(_router, LoginRoute(from: from));

  RouteNavigation<AppRoutePath> postDetail({required int id}) =>
      RouteNavigation(_router, PostDetailRoute(id: id));

  RouteNavigation<AppRoutePath> project({
    required int projectId,
    String? tab,
  }) => RouteNavigation(_router, ProjectRoute(projectId: projectId, tab: tab));

  RouteNavigation<AppRoutePath> projectSettings({
    required int projectId,
    String section = 'general',
  }) => RouteNavigation(
    _router,
    ProjectSettingsRoute(projectId: projectId, section: section),
  );

  RouteNavigation<AppRoutePath> search({String? q, int page = 1}) =>
      RouteNavigation(_router, SearchRoute(q: q, page: page));

  void pop() => _router.pop();
}

final class RouteNavigation<T extends Object> {
  const RouteNavigation(this._router, this.route);

  final DustRouterController<T> _router;
  final T route;

  void go() => _router.go(route);
  void push() => _router.push(route);
  void replace() => _router.replace(route);
}

AppRoutePath parseAppRoute(Uri uri) {
  final segments = uri.pathSegments;

  if (segments.isEmpty) {
    return DashboardRoute();
  }

  if (segments.length == 1 && segments[0] == '404') {
    return NotFoundRoute(path: uri.queryParameters['path'] ?? '');
  }

  if (segments.length == 1 && segments[0] == 'admin') {
    return AdminRoute();
  }

  if (segments.length == 3 &&
      segments[0] == 'billing' &&
      segments[1] == 'invoices') {
    final invoiceId = segments[2];
    return InvoiceRoute(
      invoiceId: invoiceId,
      download: _parseBool(uri.queryParameters['download']) ?? false,
    );
  }

  if (segments.length == 2 && segments[0] == 'checkout') {
    final plan = segments[1];
    return CheckoutRoute(
      plan: plan,
      annual: _parseBool(uri.queryParameters['annual']) ?? false,
    );
  }

  if (segments.length == 1 && segments[0] == 'forbidden') {
    return ForbiddenRoute();
  }

  if (segments.length == 2 && segments[0] == 'invite') {
    final token = segments[1];
    return InviteRoute(token: token);
  }

  if (segments.length == 1 && segments[0] == 'login') {
    return LoginRoute(from: uri.queryParameters['from']);
  }

  if (segments.length == 2 && segments[0] == 'posts') {
    final id = int.tryParse(segments[1]);
    if (id == null) {
      return _notFoundRoute(uri);
    }
    return PostDetailRoute(id: id);
  }

  if (segments.length == 2 && segments[0] == 'projects') {
    final projectId = int.tryParse(segments[1]);
    if (projectId == null) {
      return _notFoundRoute(uri);
    }
    return ProjectRoute(projectId: projectId, tab: uri.queryParameters['tab']);
  }

  if (segments.length == 3 &&
      segments[0] == 'projects' &&
      segments[2] == 'settings') {
    final projectId = int.tryParse(segments[1]);
    if (projectId == null) {
      return _notFoundRoute(uri);
    }
    return ProjectSettingsRoute(
      projectId: projectId,
      section: uri.queryParameters['section'] ?? 'general',
    );
  }

  if (segments.length == 1 && segments[0] == 'search') {
    return SearchRoute(
      q: uri.queryParameters['q'],
      page: int.tryParse(uri.queryParameters['page'] ?? '') ?? 1,
    );
  }

  return _notFoundRoute(uri);
}

AppRoutePath _notFoundRoute(Uri uri) => NotFoundRoute(path: uri.toString());

bool? _parseBool(String? value) {
  return switch (value) {
    'true' || '1' => true,
    'false' || '0' => false,
    null || '' => null,
    _ => () {
      assert(
        false,
        '_parseBool: unrecognised value "$value", treating as null',
      );
      return null;
    }(),
  };
}

const Map<Type, Type?> _kAppliedShellsByPage = {
  DashboardPage: AppShell,
  NotFoundPage: null,
  AdminPage: AppShell,
  InvoicePage: AppShell,
  CheckoutPage: null,
  ForbiddenPage: null,
  InvitePage: null,
  LoginPage: null,
  PostDetailPage: null,
  ProjectPage: AppShell,
  ProjectSettingsPage: AppShell,
  SearchPage: AppShell,
};

bool _shellConsistencyCheck() {
  bool visit(GeneratedRoute route) {
    final page = route.page;
    if (page != null && _kAppliedShellsByPage[page] != route.shell) {
      return false;
    }
    return route.routes.every(visit);
  }

  return $appRoutes.every(visit);
}

Page<void> buildAppRoutePage(AppRoutePath route) {
  assert(
    _shellConsistencyCheck(),
    'Shell mismatch between \$appRoutes and buildAppRoutePage',
  );
  return switch (route) {
    DashboardRoute() => generatedPage(
      location: route.location,
      name: 'dashboard',
      transition: const FadeUpwardsPageTransitionsBuilder(),
      fullscreenDialog: false,
      maintainState: true,
      child: AppShell(child: const DashboardPage()),
    ),
    NotFoundRoute(path: final path) => generatedPage(
      location: route.location,
      name: 'notFound',
      transition: const FadeUpwardsPageTransitionsBuilder(),
      fullscreenDialog: false,
      maintainState: true,
      child: NotFoundPage(path: path),
    ),
    AdminRoute() => generatedPage(
      location: route.location,
      name: 'admin',
      fullscreenDialog: false,
      maintainState: true,
      child: AppShell(child: const AdminPage()),
    ),
    InvoiceRoute(invoiceId: final invoiceId, download: final download) =>
      generatedPage(
        location: route.location,
        name: 'invoice',
        fullscreenDialog: false,
        maintainState: true,
        child: AppShell(
          child: InvoicePage(invoiceId: invoiceId, download: download),
        ),
      ),
    CheckoutRoute(plan: final plan, annual: final annual) => generatedPage(
      location: route.location,
      name: 'checkout',
      transition: const BottomToTopPageTransitionsBuilder(),
      fullscreenDialog: true,
      maintainState: true,
      child: CheckoutPage(plan: plan, annual: annual),
    ),
    ForbiddenRoute() => generatedPage(
      location: route.location,
      name: 'forbidden',
      transition: const FadeUpwardsPageTransitionsBuilder(),
      fullscreenDialog: false,
      maintainState: true,
      child: const ForbiddenPage(),
    ),
    InviteRoute(token: final token) => generatedPage(
      location: route.location,
      name: 'invite',
      fullscreenDialog: false,
      maintainState: true,
      child: InvitePage(token: token),
    ),
    LoginRoute(from: final from) => generatedPage(
      location: route.location,
      name: 'login',
      transition: const CupertinoPageTransitionsBuilder(),
      fullscreenDialog: false,
      maintainState: true,
      child: LoginPage(from: from),
    ),
    PostDetailRoute(id: final id) => generatedPage(
      location: route.location,
      name: 'postDetail',
      transition: const CupertinoPageTransitionsBuilder(),
      fullscreenDialog: false,
      maintainState: true,
      child: PostDetailPage(id: id),
    ),
    ProjectRoute(projectId: final projectId, tab: final tab) => generatedPage(
      location: route.location,
      name: 'project',
      fullscreenDialog: false,
      maintainState: true,
      child: AppShell(
        child: ProjectPage(projectId: projectId, tab: tab),
      ),
    ),
    ProjectSettingsRoute(projectId: final projectId, section: final section) =>
      generatedPage(
        location: route.location,
        name: 'projectSettings',
        fullscreenDialog: false,
        maintainState: true,
        child: AppShell(
          child: ProjectSettingsPage(projectId: projectId, section: section),
        ),
      ),
    SearchRoute(q: final q, page: final page) => generatedPage(
      location: route.location,
      name: 'search',
      transition: const _NoTransitionBuilder(),
      fullscreenDialog: false,
      maintainState: true,
      child: AppShell(
        child: SearchPage(q: q, page: page),
      ),
    ),
  };
}
