name: dust
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - packages/dust_dart
  - packages/dust_flutter
  - packages/dust_db_sqlite3
  - examples/product_showcase
  - examples/benchmark_project

hooks:
  user_defines:
    sqlite3:
      source: system
      name: sqlite3
      name_windows: winsqlite3
