name: dust
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - packages/derive_annotation
  - packages/derive_serde_annotation
  - packages/dust_http_client_annotation
  - packages/dust_router
  - packages/dust_state
  - packages/dust_db_annotation
  - packages/dust_db_runtime
  - packages/dust_db_sqlite3
  - examples/product_showcase
  - examples/stress_project
