sonar.projectKey=y3l1n4ung_dust
sonar.organization=y3l1n4ung
sonar.projectName=dust
sonar.sourceEncoding=UTF-8

sonar.sources=crates,packages
sonar.exclusions=**/target/**,**/.dart_tool/**,**/coverage/**,**/.coverage/**,**/*.g.dart,**/*.dart.snapshot,**/test/**,**/tests/**,**/example/**
sonar.coverage.exclusions=**/test/**,**/tests/**,**/*_test.dart,**/*.g.dart,**/*.dart.snapshot

sonar.rust.lcov.reportPaths=.sonar/coverage/coverage-rust/rust.lcov
sonar.dart.lcov.reportPaths=.sonar/coverage/coverage-dart-dust_dart/lcov.info,.sonar/coverage/coverage-dart-dust_db_sqlite3/lcov.info,.sonar/coverage/coverage-dart-dust_server/lcov.info,.sonar/coverage/coverage-flutter-dust_flutter/lcov.info
