// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'shopping_api.dart';

Never _jsonTypeError(Object? value, String key, String expected) =>
    throw ArgumentError.value(value, key, 'expected $expected');
T _jsonAs<T>(Object? value, String key, String expected) =>
    value is T ? value : _jsonTypeError(value, key, expected);
T _jsonParseString<T>(
  Object? value,
  String key,
  String expected,
  T? Function(String value) parse,
) =>
    parse(_jsonAs<String>(value, key, 'String')) ??
    _jsonTypeError(value, key, expected);
List<Object?> _jsonAsList(Object? value, String key) =>
    _jsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _jsonAsMap(Object? value, String key) {
  final map = _jsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _jsonTypeError(value, key, 'Map<String, Object?>');
  }
}

DateTime _jsonAsDateTime(Object? value, String key) =>
    _jsonParseString(value, key, 'ISO-8601 DateTime string', DateTime.tryParse);
Uri _jsonAsUri(Object? value, String key) =>
    _jsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _jsonAsBigInt(Object? value, String key) =>
    _jsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _jsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

RequestOptions _setStreamType<T>(RequestOptions requestOptions) {
  if (T != dynamic &&
      requestOptions.responseType != ResponseType.bytes &&
      requestOptions.responseType != ResponseType.stream) {
    if (T == ResponseBody) {
      requestOptions.responseType = ResponseType.stream;
    } else if (T == String) {
      requestOptions.responseType = ResponseType.plain;
    } else {
      requestOptions.responseType = ResponseType.json;
    }
  }
  return requestOptions;
}

String _combineBaseUrls(String dioBaseUrl, String? baseUrl) {
  if (baseUrl == null || baseUrl.trim().isEmpty) {
    return dioBaseUrl;
  }
  final url = Uri.parse(baseUrl);
  if (url.isAbsolute) {
    return url.toString();
  }
  return Uri.parse(dioBaseUrl).resolveUri(url).toString();
}

Response<T> _buildResponse<T>(Response<dynamic> response, T data) {
  return Response<T>(
    data: data,
    headers: response.headers,
    isRedirect: response.isRedirect,
    redirects: response.redirects,
    requestOptions: response.requestOptions,
    statusCode: response.statusCode,
    statusMessage: response.statusMessage,
    extra: response.extra,
  );
}

mixin _$LoginRequest {
  @override
  String toString() {
    final self = this as LoginRequest;
    return 'LoginRequest('
        'username: ${self.username}, '
        'password: ${self.password}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as LoginRequest;
    return identical(this, other) ||
        other is LoginRequest &&
            runtimeType == other.runtimeType &&
            other.username == self.username &&
            other.password == self.password;
  }

  @override
  int get hashCode {
    final self = this as LoginRequest;
    return Object.hashAll([runtimeType, self.username, self.password]);
  }

  LoginRequest copyWith({String? username, String? password}) {
    final self = this as LoginRequest;
    return LoginRequest(
      username: username ?? self.username,
      password: password ?? self.password,
    );
  }

  Map<String, Object?> toJson() => _$LoginRequestToJson(this as LoginRequest);
}

mixin _$LoginResponse {
  @override
  String toString() {
    final self = this as LoginResponse;
    return 'LoginResponse('
        'token: ${self.token}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as LoginResponse;
    return identical(this, other) ||
        other is LoginResponse &&
            runtimeType == other.runtimeType &&
            other.token == self.token;
  }

  @override
  int get hashCode {
    final self = this as LoginResponse;
    return Object.hashAll([runtimeType, self.token]);
  }

  LoginResponse copyWith({String? token}) {
    final self = this as LoginResponse;
    return LoginResponse(token: token ?? self.token);
  }

  Map<String, Object?> toJson() => _$LoginResponseToJson(this as LoginResponse);
}

mixin _$RegisterUserResponse {
  @override
  String toString() {
    final self = this as RegisterUserResponse;
    return 'RegisterUserResponse('
        'id: ${self.id}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as RegisterUserResponse;
    return identical(this, other) ||
        other is RegisterUserResponse &&
            runtimeType == other.runtimeType &&
            other.id == self.id;
  }

  @override
  int get hashCode {
    final self = this as RegisterUserResponse;
    return Object.hashAll([runtimeType, self.id]);
  }

  RegisterUserResponse copyWith({int? id}) {
    final self = this as RegisterUserResponse;
    return RegisterUserResponse(id: id ?? self.id);
  }

  Map<String, Object?> toJson() =>
      _$RegisterUserResponseToJson(this as RegisterUserResponse);
}

mixin _$RegisterName {
  @override
  String toString() {
    final self = this as RegisterName;
    return 'RegisterName('
        'firstname: ${self.firstname}, '
        'lastname: ${self.lastname}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as RegisterName;
    return identical(this, other) ||
        other is RegisterName &&
            runtimeType == other.runtimeType &&
            other.firstname == self.firstname &&
            other.lastname == self.lastname;
  }

  @override
  int get hashCode {
    final self = this as RegisterName;
    return Object.hashAll([runtimeType, self.firstname, self.lastname]);
  }

  RegisterName copyWith({String? firstname, String? lastname}) {
    final self = this as RegisterName;
    return RegisterName(
      firstname: firstname ?? self.firstname,
      lastname: lastname ?? self.lastname,
    );
  }

  Map<String, Object?> toJson() => _$RegisterNameToJson(this as RegisterName);
}

mixin _$RegisterGeolocation {
  @override
  String toString() {
    final self = this as RegisterGeolocation;
    return 'RegisterGeolocation('
        'lat: ${self.lat}, '
        'long: ${self.long}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as RegisterGeolocation;
    return identical(this, other) ||
        other is RegisterGeolocation &&
            runtimeType == other.runtimeType &&
            other.lat == self.lat &&
            other.long == self.long;
  }

  @override
  int get hashCode {
    final self = this as RegisterGeolocation;
    return Object.hashAll([runtimeType, self.lat, self.long]);
  }

  RegisterGeolocation copyWith({String? lat, String? long}) {
    final self = this as RegisterGeolocation;
    return RegisterGeolocation(lat: lat ?? self.lat, long: long ?? self.long);
  }

  Map<String, Object?> toJson() =>
      _$RegisterGeolocationToJson(this as RegisterGeolocation);
}

mixin _$RegisterAddress {
  @override
  String toString() {
    final self = this as RegisterAddress;
    return 'RegisterAddress('
        'city: ${self.city}, '
        'street: ${self.street}, '
        'number: ${self.number}, '
        'zipcode: ${self.zipcode}, '
        'geolocation: ${self.geolocation}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as RegisterAddress;
    return identical(this, other) ||
        other is RegisterAddress &&
            runtimeType == other.runtimeType &&
            other.city == self.city &&
            other.street == self.street &&
            other.number == self.number &&
            other.zipcode == self.zipcode &&
            other.geolocation == self.geolocation;
  }

  @override
  int get hashCode {
    final self = this as RegisterAddress;
    return Object.hashAll([
      runtimeType,
      self.city,
      self.street,
      self.number,
      self.zipcode,
      self.geolocation,
    ]);
  }

  RegisterAddress copyWith({
    String? city,
    String? street,
    int? number,
    String? zipcode,
    RegisterGeolocation? geolocation,
  }) {
    final self = this as RegisterAddress;
    final nextGeolocation = (geolocation ?? self.geolocation).copyWith();

    return RegisterAddress(
      city: city ?? self.city,
      street: street ?? self.street,
      number: number ?? self.number,
      zipcode: zipcode ?? self.zipcode,
      geolocation: nextGeolocation,
    );
  }

  Map<String, Object?> toJson() =>
      _$RegisterAddressToJson(this as RegisterAddress);
}

mixin _$RegisterUserRequest {
  @override
  String toString() {
    final self = this as RegisterUserRequest;
    return 'RegisterUserRequest('
        'email: ${self.email}, '
        'username: ${self.username}, '
        'password: ${self.password}, '
        'name: ${self.name}, '
        'phone: ${self.phone}, '
        'address: ${self.address}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as RegisterUserRequest;
    return identical(this, other) ||
        other is RegisterUserRequest &&
            runtimeType == other.runtimeType &&
            other.email == self.email &&
            other.username == self.username &&
            other.password == self.password &&
            other.name == self.name &&
            other.phone == self.phone &&
            other.address == self.address;
  }

  @override
  int get hashCode {
    final self = this as RegisterUserRequest;
    return Object.hashAll([
      runtimeType,
      self.email,
      self.username,
      self.password,
      self.name,
      self.phone,
      self.address,
    ]);
  }

  RegisterUserRequest copyWith({
    String? email,
    String? username,
    String? password,
    RegisterName? name,
    String? phone,
    RegisterAddress? address,
  }) {
    final self = this as RegisterUserRequest;
    final nextName = (name ?? self.name).copyWith();
    final nextAddress = (address ?? self.address).copyWith();

    return RegisterUserRequest(
      email: email ?? self.email,
      username: username ?? self.username,
      password: password ?? self.password,
      name: nextName,
      phone: phone ?? self.phone,
      address: nextAddress,
    );
  }

  Map<String, Object?> toJson() =>
      _$RegisterUserRequestToJson(this as RegisterUserRequest);
}

final class _$ShoppingApi implements ShoppingApi {
  _$ShoppingApi(this._dio, {String? baseUrl}) : _baseUrl = baseUrl;

  final Dio _dio;
  final String? _baseUrl;

  @override
  Future<List<Product>> getProducts() async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    _headers['accept'] = 'application/json';
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<List<dynamic>>(
      _setStreamType<List<Product>>(
        _options
            .compose(
              _dio.options,
              '/products',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl ?? 'https://fakestoreapi.com',
              ),
            ),
      ),
    );
    return (_result.data as List<dynamic>)
        .map((item) => Product.fromJson(item as Map<String, dynamic>))
        .toList();
  }

  @override
  Future<Product> getProduct(int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    _headers['accept'] = 'application/json';
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Product>(
        _options
            .compose(
              _dio.options,
              '/products/' + Uri.encodeComponent(id.toString()),
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl ?? 'https://fakestoreapi.com',
              ),
            ),
      ),
    );
    return Product.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<List<String>> getCategories() async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    _headers['accept'] = 'application/json';
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<List<dynamic>>(
      _setStreamType<List<String>>(
        _options
            .compose(
              _dio.options,
              '/products/categories',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl ?? 'https://fakestoreapi.com',
              ),
            ),
      ),
    );
    return (_result.data as List<dynamic>)
        .map((item) => item as String)
        .toList();
  }

  @override
  Future<LoginResponse> login(LoginRequest payload) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    _headers['accept'] = 'application/json';
    _headers['content-type'] = 'application/json';
    final Object? _data = payload.toJson();
    final _options = Options(
      method: 'POST',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<LoginResponse>(
        _options
            .compose(
              _dio.options,
              '/auth/login',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl ?? 'https://fakestoreapi.com',
              ),
            ),
      ),
    );
    return LoginResponse.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<User> getUser(int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    _headers['accept'] = 'application/json';
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<User>(
        _options
            .compose(
              _dio.options,
              '/users/' + Uri.encodeComponent(id.toString()),
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl ?? 'https://fakestoreapi.com',
              ),
            ),
      ),
    );
    return User.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<RegisterUserResponse> registerUser(RegisterUserRequest payload) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    _headers['accept'] = 'application/json';
    _headers['content-type'] = 'application/json';
    final Object? _data = payload.toJson();
    final _options = Options(
      method: 'POST',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<RegisterUserResponse>(
        _options
            .compose(
              _dio.options,
              '/users',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl ?? 'https://fakestoreapi.com',
              ),
            ),
      ),
    );
    return RegisterUserResponse.fromJson(_result.data as Map<String, dynamic>);
  }
}

Map<String, Object?> _$LoginRequestToJson(LoginRequest instance) {
  return <String, Object?>{
    'username': instance.username,
    'password': instance.password,
  };
}

// factory LoginRequest.fromJson(Map<String, Object?> json) => _$LoginRequestFromJson(json);
LoginRequest _$LoginRequestFromJson(Map<String, Object?> json) {
  final usernameValue = _jsonAs<String>(json['username'], 'username', 'String');
  final passwordValue = _jsonAs<String>(json['password'], 'password', 'String');

  return LoginRequest(username: usernameValue, password: passwordValue);
}

Map<String, Object?> _$LoginResponseToJson(LoginResponse instance) {
  return <String, Object?>{'token': instance.token};
}

// factory LoginResponse.fromJson(Map<String, Object?> json) => _$LoginResponseFromJson(json);
LoginResponse _$LoginResponseFromJson(Map<String, Object?> json) {
  final tokenValue = _jsonAs<String>(json['token'], 'token', 'String');

  return LoginResponse(token: tokenValue);
}

Map<String, Object?> _$RegisterUserResponseToJson(
  RegisterUserResponse instance,
) {
  return <String, Object?>{'id': instance.id};
}

// factory RegisterUserResponse.fromJson(Map<String, Object?> json) => _$RegisterUserResponseFromJson(json);
RegisterUserResponse _$RegisterUserResponseFromJson(Map<String, Object?> json) {
  final idValue = _jsonAs<int>(json['id'], 'id', 'int');

  return RegisterUserResponse(id: idValue);
}

Map<String, Object?> _$RegisterNameToJson(RegisterName instance) {
  return <String, Object?>{
    'firstname': instance.firstname,
    'lastname': instance.lastname,
  };
}

// factory RegisterName.fromJson(Map<String, Object?> json) => _$RegisterNameFromJson(json);
RegisterName _$RegisterNameFromJson(Map<String, Object?> json) {
  final firstnameValue = _jsonAs<String>(
    json['firstname'],
    'firstname',
    'String',
  );
  final lastnameValue = _jsonAs<String>(json['lastname'], 'lastname', 'String');

  return RegisterName(firstname: firstnameValue, lastname: lastnameValue);
}

Map<String, Object?> _$RegisterGeolocationToJson(RegisterGeolocation instance) {
  return <String, Object?>{'lat': instance.lat, 'long': instance.long};
}

// factory RegisterGeolocation.fromJson(Map<String, Object?> json) => _$RegisterGeolocationFromJson(json);
RegisterGeolocation _$RegisterGeolocationFromJson(Map<String, Object?> json) {
  final latValue = _jsonAs<String>(json['lat'], 'lat', 'String');
  final longValue = _jsonAs<String>(json['long'], 'long', 'String');

  return RegisterGeolocation(lat: latValue, long: longValue);
}

Map<String, Object?> _$RegisterAddressToJson(RegisterAddress instance) {
  return <String, Object?>{
    'city': instance.city,
    'street': instance.street,
    'number': instance.number,
    'zipcode': instance.zipcode,
    'geolocation': _$RegisterGeolocationToJson(instance.geolocation),
  };
}

// factory RegisterAddress.fromJson(Map<String, Object?> json) => _$RegisterAddressFromJson(json);
RegisterAddress _$RegisterAddressFromJson(Map<String, Object?> json) {
  final cityValue = _jsonAs<String>(json['city'], 'city', 'String');
  final streetValue = _jsonAs<String>(json['street'], 'street', 'String');
  final numberValue = _jsonAs<int>(json['number'], 'number', 'int');
  final zipcodeValue = _jsonAs<String>(json['zipcode'], 'zipcode', 'String');
  final geolocationValue = _$RegisterGeolocationFromJson(
    _jsonAsMap(json['geolocation'], 'geolocation'),
  );

  return RegisterAddress(
    city: cityValue,
    street: streetValue,
    number: numberValue,
    zipcode: zipcodeValue,
    geolocation: geolocationValue,
  );
}

Map<String, Object?> _$RegisterUserRequestToJson(RegisterUserRequest instance) {
  return <String, Object?>{
    'email': instance.email,
    'username': instance.username,
    'password': instance.password,
    'name': _$RegisterNameToJson(instance.name),
    'phone': instance.phone,
    'address': _$RegisterAddressToJson(instance.address),
  };
}

// factory RegisterUserRequest.fromJson(Map<String, Object?> json) => _$RegisterUserRequestFromJson(json);
RegisterUserRequest _$RegisterUserRequestFromJson(Map<String, Object?> json) {
  final emailValue = _jsonAs<String>(json['email'], 'email', 'String');
  final usernameValue = _jsonAs<String>(json['username'], 'username', 'String');
  final passwordValue = _jsonAs<String>(json['password'], 'password', 'String');
  final nameValue = _$RegisterNameFromJson(_jsonAsMap(json['name'], 'name'));
  final phoneValue = _jsonAs<String>(json['phone'], 'phone', 'String');
  final addressValue = _$RegisterAddressFromJson(
    _jsonAsMap(json['address'], 'address'),
  );

  return RegisterUserRequest(
    email: emailValue,
    username: usernameValue,
    password: passwordValue,
    name: nameValue,
    phone: phoneValue,
    address: addressValue,
  );
}
