// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'store_cart.dart';

const DeepCollectionEquality _storeCartProductsEquality = DeepCollectionEquality();

mixin _$StoreCart {
  @override
  String toString() {
    final self = this as StoreCart;
    return 'StoreCart('
        'id: ${self.id}, '
        'userId: ${self.userId}, '
        'date: ${self.date}, '
        'products: ${self.products}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as StoreCart;
    return identical(this, other) ||
        other is StoreCart &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.userId == self.userId &&
            other.date == self.date &&
            _storeCartProductsEquality.equals(other.products, self.products);
  }

  @override
  int get hashCode {
    final self = this as StoreCart;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.userId,
      self.date,
      _storeCartProductsEquality.hash(self.products),
    ]);
  }

  /// Creates a copy of this `StoreCart` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = storeCart.copyWith(id: 1);
  /// ```
  @pragma('vm:prefer-inline')
  _$StoreCartCopyWith<StoreCart> get copyWith => _$StoreCartCopyWithImpl<StoreCart>(this as StoreCart, (value) => value);

  Map<String, Object?> toJson() => _$StoreCartToJson(this as StoreCart);
}

mixin _$StoreCartProduct {
  @override
  String toString() {
    final self = this as StoreCartProduct;
    return 'StoreCartProduct('
        'productId: ${self.productId}, '
        'quantity: ${self.quantity}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as StoreCartProduct;
    return identical(this, other) ||
        other is StoreCartProduct &&
            runtimeType == other.runtimeType &&
            other.productId == self.productId &&
            other.quantity == self.quantity;
  }

  @override
  int get hashCode {
    final self = this as StoreCartProduct;
    return Object.hashAll([
      runtimeType,
      self.productId,
      self.quantity,
    ]);
  }

  /// Creates a copy of this `StoreCartProduct` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = storeCartProduct.copyWith(productId: 1);
  /// ```
  @pragma('vm:prefer-inline')
  _$StoreCartProductCopyWith<StoreCartProduct> get copyWith => _$StoreCartProductCopyWithImpl<StoreCartProduct>(this as StoreCartProduct, (value) => value);

  Map<String, Object?> toJson() =>
      _$StoreCartProductToJson(this as StoreCartProduct);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$StoreCartCopyWith<$Res> {
  $Res call({
    int? id,
    int? userId,
    DateTime? date,
    List<StoreCartProduct>? products,
  });
}

/// @nodoc
final class _$StoreCartCopyWithImpl<$Res> implements _$StoreCartCopyWith<$Res> {
  const _$StoreCartCopyWithImpl(this._self, this._then);

  final StoreCart _self;
  final $Res Function(StoreCart) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? id = null,
    Object? userId = null,
    Object? date = null,
    Object? products = null,
  }) {
    return _then(
      StoreCart(
        id: id == null ? _self.id : id as int,
        userId: userId == null ? _self.userId : userId as int,
        date: date == null ? _self.date : date as DateTime,
        products: products == null ? _self.products : products as List<StoreCartProduct>,
      )
    );
  }
}
/// @nodoc
abstract class _$StoreCartProductCopyWith<$Res> {
  $Res call({
    int? productId,
    int? quantity,
  });
}

/// @nodoc
final class _$StoreCartProductCopyWithImpl<$Res> implements _$StoreCartProductCopyWith<$Res> {
  const _$StoreCartProductCopyWithImpl(this._self, this._then);

  final StoreCartProduct _self;
  final $Res Function(StoreCartProduct) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? productId = null,
    Object? quantity = null,
  }) {
    return _then(
      StoreCartProduct(
        productId: productId == null ? _self.productId : productId as int,
        quantity: quantity == null ? _self.quantity : quantity as int,
      )
    );
  }
}

Map<String, Object?> _$StoreCartToJson(StoreCart instance) {
  return <String, Object?>{
    'id': instance.id,
    'userId': instance.userId,
    'date': instance.date.toIso8601String(),
    'products': instance.products
        .map((item) => _$StoreCartProductToJson(item))
        .toList(),
  };
}

// factory StoreCart.fromJson(Map<String, Object?> json) => _$StoreCartFromJson(json);
StoreCart _$StoreCartFromJson(Map<String, Object?> json) {
  final idValue = JsonHelper.as<int>(json['id'], 'id', 'int');
  final userIdValue = JsonHelper.as<int>(json['userId'], 'userId', 'int');
  final dateValue = JsonHelper.asDateTime(json['date'], 'date');
  final productsValue = JsonHelper.asList(json['products'], 'products')
      .map((item) => _$StoreCartProductFromJson(JsonHelper.asMap(item, 'products')))
      .toList();

  return StoreCart(
    id: idValue,
    userId: userIdValue,
    date: dateValue,
    products: productsValue,
  );
}

Map<String, Object?> _$StoreCartProductToJson(StoreCartProduct instance) {
  return <String, Object?>{
    'productId': instance.productId,
    'quantity': instance.quantity,
  };
}

// factory StoreCartProduct.fromJson(Map<String, Object?> json) => _$StoreCartProductFromJson(json);
StoreCartProduct _$StoreCartProductFromJson(Map<String, Object?> json) {
  final productIdValue = JsonHelper.as<int>(
    json['productId'],
    'productId',
    'int',
  );
  final quantityValue = JsonHelper.as<int>(json['quantity'], 'quantity', 'int');

  return StoreCartProduct(productId: productIdValue, quantity: quantityValue);
}
