// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'cart_item.dart';

Never _dustJsonTypeError(Object? value, String key, String expected) =>
    throw ArgumentError.value(value, key, 'expected $expected');
T _dustJsonAs<T>(Object? value, String key, String expected) =>
    value is T ? value : _dustJsonTypeError(value, key, expected);
T _dustJsonParseString<T>(
  Object? value,
  String key,
  String expected,
  T? Function(String value) parse,
) =>
    parse(_dustJsonAs<String>(value, key, 'String')) ??
    _dustJsonTypeError(value, key, expected);
List<Object?> _dustJsonAsList(Object? value, String key) =>
    _dustJsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _dustJsonAsMap(Object? value, String key) {
  final map = _dustJsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _dustJsonTypeError(value, key, 'Map<String, Object?>');
  }
}

DateTime _dustJsonAsDateTime(Object? value, String key) => _dustJsonParseString(
  value,
  key,
  'ISO-8601 DateTime string',
  DateTime.tryParse,
);
Uri _dustJsonAsUri(Object? value, String key) =>
    _dustJsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _dustJsonAsBigInt(Object? value, String key) =>
    _dustJsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _dustJsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

mixin _$CartItem {
  CartItem get _dustSelf => this as CartItem;

  @override
  String toString() {
    return 'CartItem('
        'product: ${_dustSelf.product}, '
        'quantity: ${_dustSelf.quantity}'
        ')';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CartItem &&
          runtimeType == other.runtimeType &&
          other.product == _dustSelf.product &&
          other.quantity == _dustSelf.quantity;

  @override
  int get hashCode =>
      Object.hashAll([runtimeType, _dustSelf.product, _dustSelf.quantity]);

  CartItem copyWith({Product? product, int? quantity}) {
    final nextProduct = (product ?? _dustSelf.product).copyWith();

    return CartItem(
      product: nextProduct,
      quantity: quantity ?? _dustSelf.quantity,
    );
  }

  Map<String, Object?> toJson() => _$CartItemToJson(_dustSelf);
}

Map<String, Object?> _$CartItemToJson(CartItem instance) {
  return <String, Object?>{
    'product': instance.product.toJson(),
    'quantity': instance.quantity,
  };
}

// factory CartItem.fromJson(Map<String, Object?> json) => _$CartItemFromJson(json);
CartItem _$CartItemFromJson(Map<String, Object?> json) {
  final productValue = Product.fromJson(
    _dustJsonAsMap(json['product'], 'product'),
  );
  final quantityValue = _dustJsonAs<int>(json['quantity'], 'quantity', 'int');

  return CartItem(product: productValue, quantity: quantityValue);
}
