// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'cart_item.dart';

Never _jsonTypeError(Object? value, String key, String expected) =>
    throw ArgumentError.value(value, key, 'expected $expected');
T _jsonAs<T>(Object? value, String key, String expected) =>
    value is T ? value : _jsonTypeError(value, key, expected);
T _jsonParseString<T>(
  Object? value,
  String key,
  String expected,
  T? Function(String value) parse,
) =>
    parse(_jsonAs<String>(value, key, 'String')) ??
    _jsonTypeError(value, key, expected);
List<Object?> _jsonAsList(Object? value, String key) =>
    _jsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _jsonAsMap(Object? value, String key) {
  final map = _jsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _jsonTypeError(value, key, 'Map<String, Object?>');
  }
}

DateTime _jsonAsDateTime(Object? value, String key) =>
    _jsonParseString(value, key, 'ISO-8601 DateTime string', DateTime.tryParse);
Uri _jsonAsUri(Object? value, String key) =>
    _jsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _jsonAsBigInt(Object? value, String key) =>
    _jsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _jsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

mixin _$CartItem {
  @override
  String toString() {
    final self = this as CartItem;
    return 'CartItem('
        'product: ${self.product}, '
        'quantity: ${self.quantity}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CartItem;
    return identical(this, other) ||
        other is CartItem &&
            runtimeType == other.runtimeType &&
            other.product == self.product &&
            other.quantity == self.quantity;
  }

  @override
  int get hashCode {
    final self = this as CartItem;
    return Object.hashAll([
      runtimeType,
      self.product,
      self.quantity,
    ]);
  }

  CartItem copyWith({
    Product? product,
    int? quantity,
  }) {
    final self = this as CartItem;
    final nextProduct = (product ?? self.product).copyWith();

    return CartItem(
      product: nextProduct,
      quantity: quantity ?? self.quantity,
    );
  }

  Map<String, Object?> toJson() => _$CartItemToJson(this as CartItem);
}

Map<String, Object?> _$CartItemToJson(CartItem instance) {
  return <String, Object?>{
    'product': instance.product.toJson(),
    'quantity': instance.quantity,
  };
}
// factory CartItem.fromJson(Map<String, Object?> json) => _$CartItemFromJson(json);
CartItem _$CartItemFromJson(Map<String, Object?> json) {
  final productValue = Product.fromJson(_jsonAsMap(json['product'], 'product'));
  final quantityValue = _jsonAs<int>(json['quantity'], 'quantity', 'int');

  return CartItem(product: productValue, quantity: quantityValue);
}
