// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'cart_item.dart';

mixin _$CartItem {
  @override
  String toString() {
    final self = this as CartItem;
    return 'CartItem('
        'product: ${self.product}, '
        'quantity: ${self.quantity}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CartItem;
    return identical(this, other) ||
        other is CartItem &&
            runtimeType == other.runtimeType &&
            other.product == self.product &&
            other.quantity == self.quantity;
  }

  @override
  int get hashCode {
    final self = this as CartItem;
    return Object.hashAll([
      runtimeType,
      self.product,
      self.quantity,
    ]);
  }

  CartItem copyWith({
    Product? product,
    int? quantity,
  }) {
    final self = this as CartItem;
    final nextProduct = (product ?? self.product).copyWith();

    return CartItem(
      product: nextProduct,
      quantity: quantity ?? self.quantity,
    );
  }

  Map<String, Object?> toJson() => _$CartItemToJson(this as CartItem);
}

Map<String, Object?> _$CartItemToJson(CartItem instance) {
  return <String, Object?>{
    'product': instance.product.toJson(),
    'quantity': instance.quantity,
  };
}
// factory CartItem.fromJson(Map<String, Object?> json) => _$CartItemFromJson(json);
CartItem _$CartItemFromJson(Map<String, Object?> json) {
  final productValue = Product.fromJson(JsonHelper.asMap(json['product'], 'product'));
  final quantityValue = JsonHelper.as<int>(json['quantity'], 'quantity', 'int');

  return CartItem(product: productValue, quantity: quantityValue);
}
