// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'orders_view_model.dart';

/// Generated base class for OrdersViewModel.
///
/// Extend this class in the user-authored ViewModel and forward typed args:
///
/// ```dart
/// final class OrdersViewModel extends $OrdersViewModel {
///   OrdersViewModel(super.args);
/// }
/// ```
abstract class $OrdersViewModel extends ViewModelBase<OrdersState, OrdersViewModelArgs> {
  $OrdersViewModel(super.args) : super(initialState: const OrdersState());
}

/// Typed state reader returned by `context.watchOrdersViewModel()`.
///
/// Read `value` to rebuild for the whole state.
///
/// ```dart
/// final state = context.watchOrdersViewModel().value;
/// ```
class _$OrdersViewModelProxy {
  _$OrdersViewModelProxy(this._context);

  final BuildContext _context;

  OrdersState get value {
    return OrdersViewModelScope.of(_context).value;
  }
}

/// Builds from a selected OrdersState value.
///
/// The selector listens to OrdersViewModel and rebuilds only when the
/// selected value changes.
class OrdersViewModelSelector<R> extends StatefulWidget {
  const OrdersViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(OrdersState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<OrdersViewModelSelector<R>> createState() => _OrdersViewModelSelectorState<R>();
}

class _OrdersViewModelSelectorState<R> extends State<OrdersViewModelSelector<R>> {
  OrdersViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = OrdersViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(OrdersViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Provides OrdersViewModel to descendants and owns it by default.
///
/// Use the default constructor when this scope should create and dispose the
/// ViewModel. Use `.value` only for externally owned ViewModels.
///
/// ```dart
/// OrdersViewModelScope(
///   args: (context) => OrdersViewModelArgs(...),
///   create: (context, args) => OrdersViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class OrdersViewModelScope extends StatefulWidget {
  /// Creates an owned OrdersViewModel from typed args.
  const OrdersViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned OrdersViewModel without disposing it.
  const OrdersViewModelScope.value({
    super.key,
    required OrdersViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final OrdersViewModelArgs Function(BuildContext context)? args;
  final OrdersViewModel Function(BuildContext context, OrdersViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final OrdersViewModel? value;
  final Widget child;

  /// Reads OrdersViewModel without subscribing the caller to state changes.
  static OrdersViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_OrdersViewModelInstance>()
        ?.widget as _OrdersViewModelInstance?;
    if (scope == null) throw StateError('No OrdersViewModelScope found in context.');
    return scope.viewModel;
  }

  static OrdersViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_OrdersViewModelInstance>();
    if (scope == null) throw StateError('No OrdersViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches OrdersViewModel and subscribes to state changes.
  static OrdersViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_OrdersViewModelInherited>();
    if (scope == null) throw StateError('No OrdersViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<OrdersViewModelScope> createState() => _OrdersViewModelScopeState();
}

class _OrdersViewModelScopeState extends State<OrdersViewModelScope> {
  OrdersViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(OrdersViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  OrdersViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned OrdersViewModelScope requires args and create.');
    }
    late final OrdersViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(
        StateError(
          'OrdersViewModelScope failed to create its view model. Check the generated '
          'scope args/create dependency injection. Original error: $error',
        ),
        stackTrace,
      );
    }
    return created;
  }

  void _replaceViewModel(
    OrdersViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(OrdersViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('OrdersViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('OrdersViewModelScope built before its view model was initialized.');
    }
    return _OrdersViewModelInstance(
      viewModel: viewModel,
      child: _OrdersViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _OrdersViewModelInstance extends InheritedWidget {
  const _OrdersViewModelInstance({required this.viewModel, required super.child});

  final OrdersViewModel viewModel;

  @override
  bool updateShouldNotify(_OrdersViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _OrdersViewModelInherited extends InheritedWidget {
  const _OrdersViewModelInherited({required this.viewModel, required this.state, required super.child});

  final OrdersViewModel viewModel;
  final OrdersState state;

  @override
  bool updateShouldNotify(_OrdersViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Listens to one-shot effects from OrdersViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// OrdersViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class OrdersViewModelListener extends StatefulWidget {
  const OrdersViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<OrdersViewModelListener> createState() => _OrdersViewModelListenerState();
}

class _OrdersViewModelListenerState extends State<OrdersViewModelListener> {
  StreamSubscription<Object>? _sub;
  OrdersViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = OrdersViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// Generated BuildContext helpers for OrdersViewModel.
///
/// ```dart
/// final vm = context.readOrdersViewModel();
/// final state = context.watchOrdersViewModel().value;
/// ```
extension OrdersViewModelBuildContext on BuildContext {
  _$OrdersViewModelProxy watchOrdersViewModel() {
    return _$OrdersViewModelProxy(this);
  }

  OrdersViewModel readOrdersViewModel() => OrdersViewModelScope.read(this);
}
