// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'order_tracking_view_model.dart';

abstract class $OrderTrackingViewModel extends ViewModelBase<OrderTrackingState, OrderTrackingViewModelArgs> {
  $OrderTrackingViewModel(super.args) : super(initialState: const OrderTrackingState());
  ShoppingRepository get repository => args.repository;
}

class _$OrderTrackingViewModelProxy {
  _$OrderTrackingViewModelProxy(this._context, this._vm);

  final BuildContext _context;
  final OrderTrackingViewModel _vm;

  OrderTrackingState get value {
    OrderTrackingViewModelScope.of(_context);
    return _vm.value;
  }
}

class OrderTrackingViewModelScope extends StatefulWidget {
  const OrderTrackingViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
  }) : value = null;

  const OrderTrackingViewModelScope.value({
    super.key,
    required OrderTrackingViewModel this.value,
    required this.child,
  }) : args = null,
       create = null;

  final OrderTrackingViewModelArgs Function(BuildContext context)? args;
  final OrderTrackingViewModel Function(BuildContext context, OrderTrackingViewModelArgs args)? create;
  final OrderTrackingViewModel? value;
  final Widget child;

  static OrderTrackingViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_OrderTrackingViewModelInherited>()
        ?.widget as _OrderTrackingViewModelInherited?;
    if (scope == null) throw StateError('No OrderTrackingViewModelScope found in context.');
    return scope.viewModel;
  }

  static OrderTrackingViewModel of(BuildContext context, {Object? aspect}) {
    final scope = context.dependOnInheritedWidgetOfExactType<_OrderTrackingViewModelInherited>(
      aspect: aspect,
    );
    if (scope == null) throw StateError('No OrderTrackingViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<OrderTrackingViewModelScope> createState() => _OrderTrackingViewModelScopeState();
}

class _OrderTrackingViewModelScopeState extends State<OrderTrackingViewModelScope> {
  @override
  Widget build(BuildContext context) {
    final external = widget.value;
    return external == null
        ? ViewModelOwner<OrderTrackingViewModel, OrderTrackingViewModelArgs>(
            debugName: 'OrderTrackingViewModelScope',
            args: widget.args!,
            create: widget.create!,
            builder: _buildInherited,
          )
        : ViewModelOwner<OrderTrackingViewModel, OrderTrackingViewModelArgs>.value(
            debugName: 'OrderTrackingViewModelScope.value',
            value: external,
            builder: _buildInherited,
          );
  }

  Widget _buildInherited(BuildContext context, OrderTrackingViewModel viewModel) {
    return ListenableBuilder(
      listenable: viewModel,
      builder: (context, child) => _OrderTrackingViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: child!,
      ),
      child: widget.child,
    );
  }
}

class _OrderTrackingViewModelInherited extends InheritedModel<Object> {
  const _OrderTrackingViewModelInherited({required this.viewModel, required this.state, required super.child});

  final OrderTrackingViewModel viewModel;
  final OrderTrackingState state;

  @override
  bool updateShouldNotify(_OrderTrackingViewModelInherited oldWidget) => state != oldWidget.state;

  @override
  bool updateShouldNotifyDependent(_OrderTrackingViewModelInherited oldWidget, Set<Object> dependencies) {
    return false;
  }
}

class OrderTrackingViewModelListener extends StatefulWidget {
  const OrderTrackingViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<OrderTrackingViewModelListener> createState() => _OrderTrackingViewModelListenerState();
}

class _OrderTrackingViewModelListenerState extends State<OrderTrackingViewModelListener> {
  StreamSubscription<Object>? _sub;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _sub?.cancel();
    _sub = OrderTrackingViewModelScope.read(context).effects.listen((effect) {
      if (mounted) widget.listener(context, effect);
    });
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

extension OrderTrackingViewModelBuildContext on BuildContext {
  OrderTrackingViewModel get orderTrackingViewModel => OrderTrackingViewModelScope.of(this);

  _$OrderTrackingViewModelProxy watchOrderTrackingViewModel() {
    return _$OrderTrackingViewModelProxy(this, OrderTrackingViewModelScope.read(this));
  }

  OrderTrackingViewModel readOrderTrackingViewModel() => OrderTrackingViewModelScope.read(this);
}
