/// A fixture for the server plugin, laid out in feature slices.
///
/// Each feature owns its DTO, model, repository, handlers, and router, so a
/// change to one stays in one directory. What is shared — the database, the
/// password and token primitives — sits under `shared/`.
///
/// ```text
/// bin/server.dart          the entry point
/// lib/src/
///   app.dart               mounts every feature's module
///   features/
///     accounts/            accounts_handler.dart -> accounts_handler.g.dart,
///                          credentials_dto, account_model, accounts_repo,
///                          require_scope
///     orders/              orders_handler.dart -> orders_handler.g.dart,
///                          new_order_dto, order_model, orders_repo
///     inventory/           inventory_handler.dart -> inventory_handler.g.dart,
///                          stock_model, inventory_repo
///     exports/             exports_handler.dart -> exports_handler.g.dart
///   shared/
///     auth/                passwords, tokens
///     db/                  database.dart -> database.g.dart
/// ```
///
/// The models, repositories, and database `.g.dart` files are generated by
/// `dust build`. The `*_handler.g.dart` files are what the server plugin will
/// emit, hand-written until it exists: a `<file>_handler.dart` produces
/// `<file>_handler.g.dart`, which declares `$<fileBase>Routes()`.
///
library;

export 'src/app.dart';
export 'src/features/accounts/account_model.dart';
export 'src/features/accounts/accounts_handler.dart';
export 'src/features/accounts/accounts_repo.dart';
export 'src/features/accounts/credentials_dto.dart';
export 'src/features/accounts/require_scope.dart';
export 'src/features/exports/exports_handler.dart';
export 'src/features/inventory/inventory_handler.dart';
export 'src/features/inventory/inventory_repo.dart';
export 'src/features/inventory/stock_model.dart';
export 'src/features/orders/new_order_dto.dart';
export 'src/features/orders/order_model.dart';
export 'src/features/orders/orders_handler.dart';
export 'src/features/orders/orders_repo.dart';
export 'src/shared/auth/passwords.dart';
export 'src/shared/auth/tokens.dart';
export 'src/shared/db/database.dart';
