/// A fixture for the server plugin: annotated handlers, hand-emitted output.
///
/// The layout follows the worked example in `docs/design/server-plugin.md`, so
/// the plugin sees the shape a real application has:
///
/// ```text
/// lib/src/
///   api/orders.dart          -> orders.g.dart   (hand-written until the plugin exists)
///   auth/caller.dart
///   auth/require_scope.dart
///   models/new_order.dart    -> new_order.g.dart  (generated by dust build)
///   models/order.dart        -> order.g.dart      (generated by dust build)
///   repo/order_store.dart
/// ```
library;

export 'src/api/orders.dart';
export 'src/auth/caller.dart';
export 'src/auth/require_scope.dart';
export 'src/models/new_order.dart';
export 'src/models/order.dart';
export 'src/repo/order_store.dart';
