/// A fixture for the server plugin, laid out in feature slices.
///
/// Each feature owns its DTO, model, repository, handlers, and router, so a
/// change to one stays in one directory. What is shared — the database, the
/// password and token primitives — sits under `shared/`.
///
/// ```text
/// lib/src/
///   features/
///     accounts/    credentials_dto, account_model, accounts_repo,
///                  accounts_handler -> accounts_router.g.dart, require_scope
///     orders/      new_order_dto, order_model, orders_repo,
///                  orders_handler -> orders_router.g.dart
///     inventory/   stock_model, inventory_repo,
///                  inventory_handler -> inventory_router.g.dart
///     exports/     exports_handler -> exports_router.g.dart
///   shared/
///     auth/        passwords, tokens
///     db/          database -> database.g.dart
/// ```
///
/// Everything ending `.g.dart` under `models`, `repo`, and `db` is generated by
/// `dust build`. The `*_router.g.dart` files are what the server plugin will
/// emit, hand-written until it exists.
library;

export 'src/features/accounts/account_model.dart';
export 'src/features/accounts/accounts_handler.dart';
export 'src/features/accounts/accounts_repo.dart';
export 'src/features/accounts/credentials_dto.dart';
export 'src/features/accounts/require_scope.dart';
export 'src/features/exports/exports_handler.dart';
export 'src/features/inventory/inventory_handler.dart';
export 'src/features/inventory/inventory_repo.dart';
export 'src/features/inventory/stock_model.dart';
export 'src/features/orders/new_order_dto.dart';
export 'src/features/orders/order_model.dart';
export 'src/features/orders/orders_handler.dart';
export 'src/features/orders/orders_repo.dart';
export 'src/shared/auth/passwords.dart';
export 'src/shared/auth/tokens.dart';
export 'src/shared/db/database.dart';
