// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'checkout_quote.dart';

final class _CheckoutQuoteRequestCopyWithUnset {
  const _CheckoutQuoteRequestCopyWithUnset();
}

const _checkoutQuoteRequestCopyWithUnset = _CheckoutQuoteRequestCopyWithUnset();
final class _CheckoutQuoteCopyWithUnset {
  const _CheckoutQuoteCopyWithUnset();
}

const _checkoutQuoteCopyWithUnset = _CheckoutQuoteCopyWithUnset();

mixin _$CheckoutQuoteRequest {
  @override
  String toString() {
    final self = this as CheckoutQuoteRequest;
    return 'CheckoutQuoteRequest('
        'subtotal: ${self.subtotal}, '
        'couponCode: ${self.couponCode}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CheckoutQuoteRequest;
    return identical(this, other) ||
        other is CheckoutQuoteRequest &&
            runtimeType == other.runtimeType &&
            other.subtotal == self.subtotal &&
            other.couponCode == self.couponCode;
  }

  @override
  int get hashCode {
    final self = this as CheckoutQuoteRequest;
    return Object.hashAll([
      runtimeType,
      self.subtotal,
      self.couponCode,
    ]);
  }

  /// Creates a copy of this `CheckoutQuoteRequest` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = checkoutQuoteRequest.copyWith(subtotal: 1.0);
  /// final cleared = checkoutQuoteRequest.copyWith(couponCode: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$CheckoutQuoteRequestCopyWith<CheckoutQuoteRequest> get copyWith => _$CheckoutQuoteRequestCopyWithImpl<CheckoutQuoteRequest>(this as CheckoutQuoteRequest, (value) => value);

  Map<String, Object?> toJson() =>
      _$CheckoutQuoteRequestToJson(this as CheckoutQuoteRequest);
}

mixin _$CheckoutQuote {
  @override
  String toString() {
    final self = this as CheckoutQuote;
    return 'CheckoutQuote('
        'subtotal: ${self.subtotal}, '
        'discount: ${self.discount}, '
        'shipping: ${self.shipping}, '
        'tax: ${self.tax}, '
        'total: ${self.total}, '
        'estimatedDeliveryDays: ${self.estimatedDeliveryDays}, '
        'appliedCoupon: ${self.appliedCoupon}, '
        'message: ${self.message}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CheckoutQuote;
    return identical(this, other) ||
        other is CheckoutQuote &&
            runtimeType == other.runtimeType &&
            other.subtotal == self.subtotal &&
            other.discount == self.discount &&
            other.shipping == self.shipping &&
            other.tax == self.tax &&
            other.total == self.total &&
            other.estimatedDeliveryDays == self.estimatedDeliveryDays &&
            other.appliedCoupon == self.appliedCoupon &&
            other.message == self.message;
  }

  @override
  int get hashCode {
    final self = this as CheckoutQuote;
    return Object.hashAll([
      runtimeType,
      self.subtotal,
      self.discount,
      self.shipping,
      self.tax,
      self.total,
      self.estimatedDeliveryDays,
      self.appliedCoupon,
      self.message,
    ]);
  }

  /// Creates a copy of this `CheckoutQuote` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = checkoutQuote.copyWith(subtotal: 1.0);
  /// final cleared = checkoutQuote.copyWith(appliedCoupon: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$CheckoutQuoteCopyWith<CheckoutQuote> get copyWith => _$CheckoutQuoteCopyWithImpl<CheckoutQuote>(this as CheckoutQuote, (value) => value);

  Map<String, Object?> toJson() => _$CheckoutQuoteToJson(this as CheckoutQuote);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$CheckoutQuoteRequestCopyWith<$Res> {
  $Res call({
    double? subtotal,
    String? couponCode,
  });
}

/// @nodoc
final class _$CheckoutQuoteRequestCopyWithImpl<$Res> implements _$CheckoutQuoteRequestCopyWith<$Res> {
  const _$CheckoutQuoteRequestCopyWithImpl(this._self, this._then);

  final CheckoutQuoteRequest _self;
  final $Res Function(CheckoutQuoteRequest) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? subtotal = null,
    Object? couponCode = _checkoutQuoteRequestCopyWithUnset,
  }) {
    return _then(
      CheckoutQuoteRequest(
        subtotal: subtotal == null ? _self.subtotal : subtotal as double,
        couponCode: identical(couponCode, _checkoutQuoteRequestCopyWithUnset)
            ? _self.couponCode
            : couponCode as String?,
      )
    );
  }
}
/// @nodoc
abstract class _$CheckoutQuoteCopyWith<$Res> {
  $Res call({
    double? subtotal,
    double? discount,
    double? shipping,
    double? tax,
    double? total,
    int? estimatedDeliveryDays,
    String? appliedCoupon,
    String? message,
  });
}

/// @nodoc
final class _$CheckoutQuoteCopyWithImpl<$Res> implements _$CheckoutQuoteCopyWith<$Res> {
  const _$CheckoutQuoteCopyWithImpl(this._self, this._then);

  final CheckoutQuote _self;
  final $Res Function(CheckoutQuote) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? subtotal = null,
    Object? discount = null,
    Object? shipping = null,
    Object? tax = null,
    Object? total = null,
    Object? estimatedDeliveryDays = null,
    Object? appliedCoupon = _checkoutQuoteCopyWithUnset,
    Object? message = _checkoutQuoteCopyWithUnset,
  }) {
    return _then(
      CheckoutQuote(
        subtotal: subtotal == null ? _self.subtotal : subtotal as double,
        discount: discount == null ? _self.discount : discount as double,
        shipping: shipping == null ? _self.shipping : shipping as double,
        tax: tax == null ? _self.tax : tax as double,
        total: total == null ? _self.total : total as double,
        estimatedDeliveryDays: estimatedDeliveryDays == null ? _self.estimatedDeliveryDays : estimatedDeliveryDays as int,
        appliedCoupon: identical(appliedCoupon, _checkoutQuoteCopyWithUnset)
            ? _self.appliedCoupon
            : appliedCoupon as String?,
        message: identical(message, _checkoutQuoteCopyWithUnset)
            ? _self.message
            : message as String?,
      )
    );
  }
}

Map<String, Object?> _$CheckoutQuoteRequestToJson(CheckoutQuoteRequest instance) {
  return <String, Object?>{
    'subtotal': instance.subtotal,
    'couponCode': instance.couponCode,
  };
}

// factory CheckoutQuoteRequest.fromJson(Map<String, Object?> json) => _$CheckoutQuoteRequestFromJson(json);
CheckoutQuoteRequest _$CheckoutQuoteRequestFromJson(Map<String, Object?> json) {
  final subtotalValue = JsonHelper.as<num>(json['subtotal'], 'subtotal', 'num').toDouble();
  final couponCodeValue = json['couponCode'] == null
      ? null
      : JsonHelper.as<String>(json['couponCode'], 'couponCode', 'String');

  return CheckoutQuoteRequest(
    subtotal: subtotalValue,
    couponCode: couponCodeValue,
  );
}

Map<String, Object?> _$CheckoutQuoteToJson(CheckoutQuote instance) {
  return <String, Object?>{
    'subtotal': instance.subtotal,
    'discount': instance.discount,
    'shipping': instance.shipping,
    'tax': instance.tax,
    'total': instance.total,
    'estimatedDeliveryDays': instance.estimatedDeliveryDays,
    'appliedCoupon': instance.appliedCoupon,
    'message': instance.message,
  };
}

// factory CheckoutQuote.fromJson(Map<String, Object?> json) => _$CheckoutQuoteFromJson(json);
CheckoutQuote _$CheckoutQuoteFromJson(Map<String, Object?> json) {
  final subtotalValue = JsonHelper.as<num>(json['subtotal'], 'subtotal', 'num').toDouble();
  final discountValue = JsonHelper.as<num>(json['discount'], 'discount', 'num').toDouble();
  final shippingValue = JsonHelper.as<num>(json['shipping'], 'shipping', 'num').toDouble();
  final taxValue = JsonHelper.as<num>(json['tax'], 'tax', 'num').toDouble();
  final totalValue = JsonHelper.as<num>(json['total'], 'total', 'num').toDouble();
  final estimatedDeliveryDaysValue = JsonHelper.as<int>(
    json['estimatedDeliveryDays'],
    'estimatedDeliveryDays',
    'int',
  );
  final appliedCouponValue = json['appliedCoupon'] == null
      ? null
      : JsonHelper.as<String>(json['appliedCoupon'], 'appliedCoupon', 'String');
  final messageValue = json['message'] == null
      ? null
      : JsonHelper.as<String>(json['message'], 'message', 'String');

  return CheckoutQuote(
    subtotal: subtotalValue,
    discount: discountValue,
    shipping: shippingValue,
    tax: taxValue,
    total: totalValue,
    estimatedDeliveryDays: estimatedDeliveryDaysValue,
    appliedCoupon: appliedCouponValue,
    message: messageValue,
  );
}
