// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'checkout_state.dart';

final class _CheckoutStateCopyWithUnset {
  const _CheckoutStateCopyWithUnset();
}

const _checkoutStateCopyWithUnset = _CheckoutStateCopyWithUnset();

mixin _$CheckoutState {
  @override
  String toString() {
    final self = this as CheckoutState;
    return 'CheckoutState('
        'status: ${self.status}, '
        'shippingAddress: ${self.shippingAddress}, '
        'errorMessage: ${self.errorMessage}, '
        'orderId: ${self.orderId}, '
        'couponCode: ${self.couponCode}, '
        'quote: ${self.quote}, '
        'isQuoteLoading: ${self.isQuoteLoading}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CheckoutState;
    return identical(this, other) ||
        other is CheckoutState &&
            runtimeType == other.runtimeType &&
            other.status == self.status &&
            other.shippingAddress == self.shippingAddress &&
            other.errorMessage == self.errorMessage &&
            other.orderId == self.orderId &&
            other.couponCode == self.couponCode &&
            other.quote == self.quote &&
            other.isQuoteLoading == self.isQuoteLoading;
  }

  @override
  int get hashCode {
    final self = this as CheckoutState;
    return Object.hashAll([
      runtimeType,
      self.status,
      self.shippingAddress,
      self.errorMessage,
      self.orderId,
      self.couponCode,
      self.quote,
      self.isQuoteLoading,
    ]);
  }

  /// Creates a copy of this `CheckoutState` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = checkoutState.copyWith(isQuoteLoading: true);
  /// final cleared = checkoutState.copyWith(shippingAddress: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$CheckoutStateCopyWith<CheckoutState> get copyWith => _$CheckoutStateCopyWithImpl<CheckoutState>(this as CheckoutState, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$CheckoutStateCopyWith<$Res> {
  $Res call({
    CheckoutStatus? status,
    ShippingAddress? shippingAddress,
    String? errorMessage,
    String? orderId,
    String? couponCode,
    CheckoutQuote? quote,
    bool? isQuoteLoading,
  });
}

/// @nodoc
final class _$CheckoutStateCopyWithImpl<$Res> implements _$CheckoutStateCopyWith<$Res> {
  const _$CheckoutStateCopyWithImpl(this._self, this._then);

  final CheckoutState _self;
  final $Res Function(CheckoutState) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? status = null,
    Object? shippingAddress = _checkoutStateCopyWithUnset,
    Object? errorMessage = _checkoutStateCopyWithUnset,
    Object? orderId = _checkoutStateCopyWithUnset,
    Object? couponCode = _checkoutStateCopyWithUnset,
    Object? quote = _checkoutStateCopyWithUnset,
    Object? isQuoteLoading = null,
  }) {
    return _then(
      CheckoutState(
        status: status == null ? _self.status : status as CheckoutStatus,
        shippingAddress: identical(shippingAddress, _checkoutStateCopyWithUnset)
            ? _self.shippingAddress
            : shippingAddress as ShippingAddress?,
        errorMessage: identical(errorMessage, _checkoutStateCopyWithUnset)
            ? _self.errorMessage
            : errorMessage as String?,
        orderId: identical(orderId, _checkoutStateCopyWithUnset)
            ? _self.orderId
            : orderId as String?,
        couponCode: identical(couponCode, _checkoutStateCopyWithUnset)
            ? _self.couponCode
            : couponCode as String?,
        quote: identical(quote, _checkoutStateCopyWithUnset)
            ? _self.quote
            : quote as CheckoutQuote?,
        isQuoteLoading: isQuoteLoading == null ? _self.isQuoteLoading : isQuoteLoading as bool,
      )
    );
  }
}
