// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'checkout_state.dart';

const Object _undefined = Object();

mixin _$CheckoutState {
  @override
  String toString() {
    final self = this as CheckoutState;
    return 'CheckoutState('
        'status: ${self.status}, '
        'shippingAddress: ${self.shippingAddress}, '
        'errorMessage: ${self.errorMessage}, '
        'orderId: ${self.orderId}, '
        'couponCode: ${self.couponCode}, '
        'quote: ${self.quote}, '
        'isQuoteLoading: ${self.isQuoteLoading}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CheckoutState;
    return identical(this, other) ||
        other is CheckoutState &&
            runtimeType == other.runtimeType &&
            other.status == self.status &&
            other.shippingAddress == self.shippingAddress &&
            other.errorMessage == self.errorMessage &&
            other.orderId == self.orderId &&
            other.couponCode == self.couponCode &&
            other.quote == self.quote &&
            other.isQuoteLoading == self.isQuoteLoading;
  }

  @override
  int get hashCode {
    final self = this as CheckoutState;
    return Object.hashAll([
      runtimeType,
      self.status,
      self.shippingAddress,
      self.errorMessage,
      self.orderId,
      self.couponCode,
      self.quote,
      self.isQuoteLoading,
    ]);
  }

  CheckoutState copyWith({
    CheckoutStatus? status,
    Object? shippingAddress = _undefined,
    Object? errorMessage = _undefined,
    Object? orderId = _undefined,
    Object? couponCode = _undefined,
    Object? quote = _undefined,
    bool? isQuoteLoading,
  }) {
    final self = this as CheckoutState;
    final nextShippingAddressSource = identical(shippingAddress, _undefined)
        ? self.shippingAddress
        : shippingAddress as ShippingAddress?;
    final nextShippingAddress = nextShippingAddressSource == null ? null : nextShippingAddressSource.copyWith();
    final nextQuoteSource = identical(quote, _undefined)
        ? self.quote
        : quote as CheckoutQuote?;
    final nextQuote = nextQuoteSource == null ? null : nextQuoteSource.copyWith();

    return CheckoutState(
      status: status ?? self.status,
      shippingAddress: nextShippingAddress,
      errorMessage: identical(errorMessage, _undefined)
          ? self.errorMessage
          : errorMessage as String?,
      orderId: identical(orderId, _undefined)
          ? self.orderId
          : orderId as String?,
      couponCode: identical(couponCode, _undefined)
          ? self.couponCode
          : couponCode as String?,
      quote: nextQuote,
      isQuoteLoading: isQuoteLoading ?? self.isQuoteLoading,
    );
  }
}
