// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'shopping_chat_view_model.dart';

/// Base class generated for ShoppingChatViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class ShoppingChatViewModel extends $ShoppingChatViewModel {
///   ShoppingChatViewModel(super.args);
/// }
/// ```
abstract class $ShoppingChatViewModel extends ViewModelBase<ChatState, ShoppingChatViewModelArgs> {
  $ShoppingChatViewModel(super.args) : super(initialState: const ChatState());
}

/// Reads ShoppingChatViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchShoppingChatViewModel().value;
/// ```
class _$ShoppingChatViewModelProxy {
  _$ShoppingChatViewModelProxy(this._context);

  final BuildContext _context;

  ChatState get value {
    return ShoppingChatViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected ChatState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class ShoppingChatViewModelSelector<R> extends StatefulWidget {
  const ShoppingChatViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(ChatState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<ShoppingChatViewModelSelector<R>> createState() => _ShoppingChatViewModelSelectorState<R>();
}

class _ShoppingChatViewModelSelectorState<R> extends State<ShoppingChatViewModelSelector<R>> {
  ShoppingChatViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = ShoppingChatViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(ShoppingChatViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides ShoppingChatViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// ShoppingChatViewModelScope(
///   args: (context) => ShoppingChatViewModelArgs(...),
///   create: (context, args) => ShoppingChatViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class ShoppingChatViewModelScope extends StatefulWidget {
  /// Creates and owns ShoppingChatViewModel from typed args.
  const ShoppingChatViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned ShoppingChatViewModel without disposing it.
  const ShoppingChatViewModelScope.value({
    super.key,
    required ShoppingChatViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final ShoppingChatViewModelArgs Function(BuildContext context)? args;
  final ShoppingChatViewModel Function(BuildContext context, ShoppingChatViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final ShoppingChatViewModel? value;
  final Widget child;

  /// Reads ShoppingChatViewModel without rebuilding when state changes.
  static ShoppingChatViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_ShoppingChatViewModelInstance>()
        ?.widget as _ShoppingChatViewModelInstance?;
    if (scope == null) throw StateError('No ShoppingChatViewModelScope found in context.');
    return scope.viewModel;
  }

  static ShoppingChatViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_ShoppingChatViewModelInstance>();
    if (scope == null) throw StateError('No ShoppingChatViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches ShoppingChatViewModel and rebuilds when state changes.
  static ShoppingChatViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_ShoppingChatViewModelInherited>();
    if (scope == null) throw StateError('No ShoppingChatViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<ShoppingChatViewModelScope> createState() => _ShoppingChatViewModelScopeState();
}

class _ShoppingChatViewModelScopeState extends State<ShoppingChatViewModelScope> {
  ShoppingChatViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(ShoppingChatViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  ShoppingChatViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned ShoppingChatViewModelScope requires args and create.');
    }
    late final ShoppingChatViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(
        StateError(
          'ShoppingChatViewModelScope failed to create its view model. Check the generated '
          'scope args/create dependency injection. Original error: $error',
        ),
        stackTrace,
      );
    }
    return created;
  }

  void _replaceViewModel(
    ShoppingChatViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(ShoppingChatViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('ShoppingChatViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('ShoppingChatViewModelScope built before its view model was initialized.');
    }
    return _ShoppingChatViewModelInstance(
      viewModel: viewModel,
      child: _ShoppingChatViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _ShoppingChatViewModelInstance extends InheritedWidget {
  const _ShoppingChatViewModelInstance({required this.viewModel, required super.child});

  final ShoppingChatViewModel viewModel;

  @override
  bool updateShouldNotify(_ShoppingChatViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _ShoppingChatViewModelInherited extends InheritedWidget {
  const _ShoppingChatViewModelInherited({required this.viewModel, required this.state, required super.child});

  final ShoppingChatViewModel viewModel;
  final ChatState state;

  @override
  bool updateShouldNotify(_ShoppingChatViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from ShoppingChatViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// ShoppingChatViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class ShoppingChatViewModelListener extends StatefulWidget {
  const ShoppingChatViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<ShoppingChatViewModelListener> createState() => _ShoppingChatViewModelListenerState();
}

class _ShoppingChatViewModelListenerState extends State<ShoppingChatViewModelListener> {
  StreamSubscription<Object>? _sub;
  ShoppingChatViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = ShoppingChatViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for ShoppingChatViewModel.
///
/// ```dart
/// final vm = context.readShoppingChatViewModel();
/// final state = context.watchShoppingChatViewModel().value;
/// ```
extension ShoppingChatViewModelBuildContext on BuildContext {
  _$ShoppingChatViewModelProxy watchShoppingChatViewModel() {
    return _$ShoppingChatViewModelProxy(this);
  }

  ShoppingChatViewModel readShoppingChatViewModel() => ShoppingChatViewModelScope.read(this);
}
