// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'shopping_chat_view_model.dart';

final class _ShoppingChatViewModelAspect<R> {
  const _ShoppingChatViewModelAspect(this.selector);

  final R Function(ChatState state) selector;

  bool hasChanged(ChatState previous, ChatState next) {
    return selector(previous) != selector(next);
  }
}

/// Generated base class for ShoppingChatViewModel.
///
/// Extend this class in the user-authored ViewModel and forward typed args:
///
/// ```dart
/// final class ShoppingChatViewModel extends $ShoppingChatViewModel {
///   ShoppingChatViewModel(super.args);
/// }
/// ```
abstract class $ShoppingChatViewModel extends ViewModelBase<ChatState, ShoppingChatViewModelArgs> {
  $ShoppingChatViewModel(super.args) : super(initialState: const ChatState());
}

/// Typed state reader returned by `context.watchShoppingChatViewModel()`.
///
/// Read `value` to rebuild for the whole state, or call `select` to rebuild only
/// when the selected value changes.
///
/// ```dart
/// final state = context.watchShoppingChatViewModel().value;
/// final count = context.watchShoppingChatViewModel().select((state) => state.count);
/// ```
class _$ShoppingChatViewModelProxy {
  _$ShoppingChatViewModelProxy(this._context);

  final BuildContext _context;

  ChatState get value {
    return ShoppingChatViewModelScope.of(_context).value;
  }

  R select<R>(R Function(ChatState state) selector) {
    final aspect = _ShoppingChatViewModelAspect<R>(selector);
    return selector(ShoppingChatViewModelScope.of(_context, aspect: aspect).value);
  }
}

/// Provides ShoppingChatViewModel to descendants and owns it by default.
///
/// Use the default constructor when this scope should create and dispose the
/// ViewModel. Use `.value` only for externally owned ViewModels.
///
/// ```dart
/// ShoppingChatViewModelScope(
///   args: (context) => ShoppingChatViewModelArgs(...),
///   create: (context, args) => ShoppingChatViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class ShoppingChatViewModelScope extends StatefulWidget {
  /// Creates an owned ShoppingChatViewModel from typed args.
  const ShoppingChatViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
  }) : value = null;

  /// Provides an externally owned ShoppingChatViewModel without disposing it.
  const ShoppingChatViewModelScope.value({
    super.key,
    required ShoppingChatViewModel this.value,
    required this.child,
  }) : args = null,
       create = null;

  final ShoppingChatViewModelArgs Function(BuildContext context)? args;
  final ShoppingChatViewModel Function(BuildContext context, ShoppingChatViewModelArgs args)? create;
  final ShoppingChatViewModel? value;
  final Widget child;

  /// Reads ShoppingChatViewModel without subscribing the caller to state changes.
  static ShoppingChatViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_ShoppingChatViewModelInherited>()
        ?.widget as _ShoppingChatViewModelInherited?;
    if (scope == null) throw StateError('No ShoppingChatViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches ShoppingChatViewModel and optionally subscribes to one generated aspect.
  static ShoppingChatViewModel of(BuildContext context, {_ShoppingChatViewModelAspect<Object?>? aspect}) {
    final scope = context.dependOnInheritedWidgetOfExactType<_ShoppingChatViewModelInherited>(
      aspect: aspect,
    );
    if (scope == null) throw StateError('No ShoppingChatViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<ShoppingChatViewModelScope> createState() => _ShoppingChatViewModelScopeState();
}

class _ShoppingChatViewModelScopeState extends State<ShoppingChatViewModelScope> {
  ShoppingChatViewModel? _viewModel;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (_viewModel == null) {
      _replaceViewModel(_resolveViewModel(), ownsViewModel: widget.value == null, notify: false);
    }
  }

  @override
  void didUpdateWidget(ShoppingChatViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    }
  }

  ShoppingChatViewModel _resolveViewModel() {
    return widget.value ?? _createOwnedViewModel();
  }

  ShoppingChatViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned ShoppingChatViewModelScope requires args and create.');
    }
    late final ShoppingChatViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(
        StateError(
          'ShoppingChatViewModelScope failed to create its view model. Check the generated '
          'scope args/create dependency injection. Original error: $error',
        ),
        stackTrace,
      );
    }
    return created;
  }

  void _replaceViewModel(
    ShoppingChatViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    if (ownsViewModel) {
      scheduleMicrotask(() {
        if (mounted && identical(_viewModel, nextViewModel)) {
          nextViewModel.init();
        }
      });
    }
    if (notify && mounted) setState(() {});
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('ShoppingChatViewModelScope built before its view model was initialized.');
    }
    return _ShoppingChatViewModelInherited(
      viewModel: viewModel,
      state: viewModel.value,
      child: widget.child,
    );
  }
}

class _ShoppingChatViewModelInherited extends InheritedModel<_ShoppingChatViewModelAspect<Object?>> {
  const _ShoppingChatViewModelInherited({required this.viewModel, required this.state, required super.child});

  final ShoppingChatViewModel viewModel;
  final ChatState state;

  /// Requires ChatState to implement == and hashCode. Without value equality,
  /// every emitted state is treated as changed and granular rebuilds degrade to
  /// full dependent subtree rebuilds.
  @override
  bool updateShouldNotify(_ShoppingChatViewModelInherited oldWidget) => state != oldWidget.state;

  @override
  bool updateShouldNotifyDependent(
    _ShoppingChatViewModelInherited oldWidget,
    Set<_ShoppingChatViewModelAspect<Object?>> dependencies,
  ) {
    for (final aspect in dependencies) {
      if (aspect.hasChanged(oldWidget.state, state)) {
        return true;
      }
    }
    return false;
  }
}

/// Listens to one-shot effects from ShoppingChatViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// ShoppingChatViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class ShoppingChatViewModelListener extends StatefulWidget {
  const ShoppingChatViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<ShoppingChatViewModelListener> createState() => _ShoppingChatViewModelListenerState();
}

class _ShoppingChatViewModelListenerState extends State<ShoppingChatViewModelListener> {
  StreamSubscription<Object>? _sub;
  ShoppingChatViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = ShoppingChatViewModelScope.read(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// Generated BuildContext helpers for ShoppingChatViewModel.
///
/// ```dart
/// final vm = context.readShoppingChatViewModel();
/// final state = context.watchShoppingChatViewModel().value;
/// ```
extension ShoppingChatViewModelBuildContext on BuildContext {
  _$ShoppingChatViewModelProxy watchShoppingChatViewModel() {
    return _$ShoppingChatViewModelProxy(this);
  }

  ShoppingChatViewModel readShoppingChatViewModel() => ShoppingChatViewModelScope.read(this);
}
