// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'shopping_chat_view_model.dart';

abstract class $ShoppingChatViewModel extends ViewModelBase<ChatState, ShoppingChatViewModelArgs> {
  $ShoppingChatViewModel(super.args) : super(initialState: const ChatState());
  ShoppingRepository get repository => args.repository;
}

class _$ShoppingChatViewModelProxy {
  _$ShoppingChatViewModelProxy(this._context, this._vm);

  final BuildContext _context;
  final ShoppingChatViewModel _vm;

  ChatState get value {
    ShoppingChatViewModelScope.of(_context);
    return _vm.value;
  }
}

class ShoppingChatViewModelScope extends StatefulWidget {
  const ShoppingChatViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
  }) : value = null;

  const ShoppingChatViewModelScope.value({
    super.key,
    required ShoppingChatViewModel this.value,
    required this.child,
  }) : args = null,
       create = null;

  final ShoppingChatViewModelArgs Function(BuildContext context)? args;
  final ShoppingChatViewModel Function(BuildContext context, ShoppingChatViewModelArgs args)? create;
  final ShoppingChatViewModel? value;
  final Widget child;

  static ShoppingChatViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_ShoppingChatViewModelInherited>()
        ?.widget as _ShoppingChatViewModelInherited?;
    if (scope == null) throw StateError('No ShoppingChatViewModelScope found in context.');
    return scope.viewModel;
  }

  static ShoppingChatViewModel of(BuildContext context, {Object? aspect}) {
    final scope = context.dependOnInheritedWidgetOfExactType<_ShoppingChatViewModelInherited>(
      aspect: aspect,
    );
    if (scope == null) throw StateError('No ShoppingChatViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<ShoppingChatViewModelScope> createState() => _ShoppingChatViewModelScopeState();
}

class _ShoppingChatViewModelScopeState extends State<ShoppingChatViewModelScope> {
  @override
  Widget build(BuildContext context) {
    final external = widget.value;
    return external == null
        ? ViewModelOwner<ShoppingChatViewModel, ShoppingChatViewModelArgs>(
            debugName: 'ShoppingChatViewModelScope',
            args: widget.args!,
            create: widget.create!,
            builder: _buildInherited,
          )
        : ViewModelOwner<ShoppingChatViewModel, ShoppingChatViewModelArgs>.value(
            debugName: 'ShoppingChatViewModelScope.value',
            value: external,
            builder: _buildInherited,
          );
  }

  Widget _buildInherited(BuildContext context, ShoppingChatViewModel viewModel) {
    return ListenableBuilder(
      listenable: viewModel,
      builder: (context, child) => _ShoppingChatViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: child!,
      ),
      child: widget.child,
    );
  }
}

class _ShoppingChatViewModelInherited extends InheritedModel<Object> {
  const _ShoppingChatViewModelInherited({required this.viewModel, required this.state, required super.child});

  final ShoppingChatViewModel viewModel;
  final ChatState state;

  @override
  bool updateShouldNotify(_ShoppingChatViewModelInherited oldWidget) => state != oldWidget.state;

  @override
  bool updateShouldNotifyDependent(_ShoppingChatViewModelInherited oldWidget, Set<Object> dependencies) {
    return false;
  }
}

class ShoppingChatViewModelListener extends StatefulWidget {
  const ShoppingChatViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<ShoppingChatViewModelListener> createState() => _ShoppingChatViewModelListenerState();
}

class _ShoppingChatViewModelListenerState extends State<ShoppingChatViewModelListener> {
  StreamSubscription<Object>? _sub;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _sub?.cancel();
    _sub = ShoppingChatViewModelScope.read(context).effects.listen((effect) {
      if (mounted) widget.listener(context, effect);
    });
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

extension ShoppingChatViewModelBuildContext on BuildContext {
  ShoppingChatViewModel get shoppingChatViewModel => ShoppingChatViewModelScope.of(this);

  _$ShoppingChatViewModelProxy watchShoppingChatViewModel() {
    return _$ShoppingChatViewModelProxy(this, ShoppingChatViewModelScope.read(this));
  }

  ShoppingChatViewModel readShoppingChatViewModel() => ShoppingChatViewModelScope.read(this);
}
