use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use dust_ir::ParamKind;

use crate::plugin::emit::path::{PathSegment, path_segments};
use crate::plugin::emit::test_support::{fallback_sample, sample_response_data, sample_value};
use crate::plugin::model::{ClientSpec, EndpointParam, EndpointSpec, RequestMode};
use crate::plugin::util::escape_single_quoted;

pub(crate) fn render_test_file(source_path: &str, specs: &[ClientSpec<'_>]) -> String {
    let source_name = Path::new(source_path)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("source.dart");
    let mut out = String::new();
    out.push_str("// GENERATED CODE - DO NOT MODIFY BY HAND\n");
    out.push_str("// coverage:ignore-file\n");
    out.push_str("// ignore_for_file: type=lint\n");
    out.push_str("// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark\n");
    out.push_str("// Generated by dust.\n\n");
    out.push_str("import 'package:dio/dio.dart';\n");
    out.push_str("import 'package:test/test.dart';\n");
    out.push_str(&format!("import '{}';\n\n", source_name));
    out.push_str("void main() {\n");
    for spec in specs {
        out.push_str(&render_client_group(spec));
    }
    out.push_str("}\n");
    out
}

pub(crate) fn test_output_path(source_path: &str) -> PathBuf {
    let source_path = PathBuf::from(source_path);
    let file_name = source_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("source.dart")
        .replace(".dart", ".test.g.dart");
    source_path
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join(file_name)
}

fn render_client_group(spec: &ClientSpec<'_>) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "  group('{} request mapping', () {{\n",
        spec.class_name
    ));
    for endpoint in &spec.endpoints {
        out.push_str(&render_endpoint_test(spec, endpoint));
    }
    out.push_str("  });\n");
    out
}

fn render_endpoint_test(spec: &ClientSpec<'_>, endpoint: &EndpointSpec<'_>) -> String {
    let Some(invocation) = build_invocation(endpoint) else {
        return format!(
            "    test('{} {}', () {{}}, skip: 'Dust could not synthesize fixtures for one or more parameters');\n",
            endpoint.verb.as_str(),
            endpoint.method.name
        );
    };

    let mut out = String::new();
    out.push_str(&format!(
        "    test('{} {}', () async {{\n",
        endpoint.verb.as_str(),
        endpoint.method.name
    ));
    out.push_str("      RequestOptions? captured;\n");
    out.push_str("      final dio = Dio();\n");
    out.push_str("      dio.interceptors.add(\n");
    out.push_str("        InterceptorsWrapper(\n");
    out.push_str("          onRequest: (options, handler) {\n");
    out.push_str("            captured = options;\n");
    out.push_str(&format!(
        "            handler.resolve(Response<dynamic>(requestOptions: options, data: {}));\n",
        sample_response_data(&endpoint.return_spec)
    ));
    out.push_str("          },\n");
    out.push_str("        ),\n");
    out.push_str("      );\n");
    out.push_str(&format!("      final api = {}(dio);\n", spec.class_name));
    out.push_str("      try {\n");
    let invocation_expr = format!("api.{}({})", endpoint.method.name, invocation.call_arguments);
    if endpoint.return_spec.is_stream() {
        out.push_str(&format!("        await {invocation_expr}.drain<void>();\n"));
    } else {
        out.push_str(&format!("        await {invocation_expr};\n"));
    }
    out.push_str("      } catch (_) {}\n");
    out.push_str("      expect(captured, isNotNull);\n");
    out.push_str("      final request = captured!;\n");
    out.push_str(&format!(
        "      expect(request.method, '{}');\n",
        endpoint.verb.as_str()
    ));
    out.push_str(&format!(
        "      expect(request.path, '{}');\n",
        escape_single_quoted(&render_expected_path(endpoint, &invocation.path_values))
    ));
    for assertion in invocation.assertions {
        out.push_str("      ");
        out.push_str(&assertion);
        out.push('\n');
    }
    out.push_str("    });\n");
    out
}

fn build_invocation(endpoint: &EndpointSpec<'_>) -> Option<Invocation> {
    let mut positional = Vec::new();
    let mut named = Vec::new();
    let mut assertions = vec![
        "expect(request.queryParameters, isA<Map<String, dynamic>>());".to_owned(),
        "expect(request.headers, isA<Map<String, dynamic>>());".to_owned(),
    ];
    let mut path_values = Vec::new();

    for param in &endpoint.method.params {
        let binding = endpoint.binding_for_param(&param.name);
        let sample = sample_value(&param.ty).or_else(|| binding.and_then(fallback_sample))?;
        let value_expr = sample.assertion_expression.clone();
        if param.kind == ParamKind::Named {
            named.push(format!("{}: {}", param.name, sample.expression));
        } else {
            positional.push(sample.expression.clone());
        }

        if let Some(binding) = binding {
            match binding {
                EndpointParam::Path { key, .. } => {
                    path_values.push((key.clone(), sample.path_value))
                }
                EndpointParam::Query { key, .. } => assertions.push(format!(
                    "expect(request.queryParameters['{}'], equals({value_expr}));",
                    escape_single_quoted(key)
                )),
                EndpointParam::Header { key, .. } => assertions.push(format!(
                    "expect(request.headers['{}'], equals({value_expr}));",
                    escape_single_quoted(key)
                )),
                EndpointParam::Body { .. } if endpoint.request_mode == RequestMode::Standard => {
                    assertions.push(format!("expect(request.data, equals({value_expr}));"));
                }
                EndpointParam::Field { key, .. }
                    if endpoint.request_mode == RequestMode::FormUrlEncoded =>
                {
                    assertions.push(format!(
                        "expect((request.data as Map<String, dynamic>)['{}'], equals({value_expr}));",
                        escape_single_quoted(key)
                    ));
                }
                _ => {}
            }
        }
    }

    for (key, value) in &endpoint.headers {
        assertions.push(format!(
            "expect(request.headers['{}'], equals('{}'));",
            escape_single_quoted(key),
            escape_single_quoted(value)
        ));
    }

    let call_arguments = match (positional.is_empty(), named.is_empty()) {
        (true, true) => String::new(),
        (false, true) => positional.join(", "),
        (true, false) => named.join(", "),
        (false, false) => format!("{}, {}", positional.join(", "), named.join(", ")),
    };

    Some(Invocation {
        call_arguments,
        assertions,
        path_values,
    })
}

fn render_expected_path(
    endpoint: &EndpointSpec<'_>,
    values: &[(String, Option<String>)],
) -> String {
    let path_values = values
        .iter()
        .map(|(key, value)| (key.as_str(), value.as_deref()))
        .collect::<BTreeMap<_, _>>();
    let mut path = String::new();

    for segment in path_segments(endpoint) {
        match segment {
            PathSegment::Literal(value) => path.push_str(value),
            PathSegment::Binding { key, .. } => match path_values.get(key).copied().flatten() {
                Some(value) => path.push_str(value),
                None => {
                    path.push('{');
                    path.push_str(key);
                    path.push('}');
                }
            },
        }
    }

    path
}

struct Invocation {
    call_arguments: String,
    assertions: Vec<String>,
    path_values: Vec<(String, Option<String>)>,
}
