// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'catalog.dart';

const DeepCollectionEquality _catalogProductsEquality = DeepCollectionEquality();
const DeepCollectionEquality _catalogCategoryByIdEquality = DeepCollectionEquality();
const DeepCollectionEquality _catalogFeaturedSkusEquality = DeepCollectionEquality.unordered();
const DeepCollectionEquality _catalogInventoryEquality = DeepCollectionEquality();

mixin _$InventoryEntry {
  @override
  String toString() {
    final self = this as InventoryEntry;
    return 'InventoryEntry('
        'productSku: ${self.productSku}, '
        'warehouse: ${self.warehouse}, '
        'quantity: ${self.quantity}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as InventoryEntry;
    return identical(this, other) ||
        other is InventoryEntry &&
            runtimeType == other.runtimeType &&
            other.productSku == self.productSku &&
            other.warehouse == self.warehouse &&
            other.quantity == self.quantity;
  }

  @override
  int get hashCode {
    final self = this as InventoryEntry;
    return Object.hashAll([
      runtimeType,
      self.productSku,
      self.warehouse,
      self.quantity,
    ]);
  }

  InventoryEntry copyWith({
    String? productSku,
    String? warehouse,
    int? quantity,
  }) {
    final self = this as InventoryEntry;
    return InventoryEntry(
      productSku: productSku ?? self.productSku,
      warehouse: warehouse ?? self.warehouse,
      quantity: quantity ?? self.quantity,
    );
  }
}

mixin _$Catalog {
  @override
  String toString() {
    final self = this as Catalog;
    return 'Catalog('
        'id: ${self.id}, '
        'products: ${self.products}, '
        'categoryById: ${self.categoryById}, '
        'featuredSkus: ${self.featuredSkus}, '
        'inventory: ${self.inventory}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Catalog;
    return identical(this, other) ||
        other is Catalog &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            _catalogProductsEquality.equals(other.products, self.products) &&
            _catalogCategoryByIdEquality.equals(other.categoryById, self.categoryById) &&
            _catalogFeaturedSkusEquality.equals(other.featuredSkus, self.featuredSkus) &&
            _catalogInventoryEquality.equals(other.inventory, self.inventory);
  }

  @override
  int get hashCode {
    final self = this as Catalog;
    return Object.hashAll([
      runtimeType,
      self.id,
      _catalogProductsEquality.hash(self.products),
      _catalogCategoryByIdEquality.hash(self.categoryById),
      _catalogFeaturedSkusEquality.hash(self.featuredSkus),
      _catalogInventoryEquality.hash(self.inventory),
    ]);
  }

  Catalog copyWith({
    String? id,
    List<Product>? products,
    Map<String, Category>? categoryById,
    Set<String>? featuredSkus,
    List<InventoryEntry>? inventory,
  }) {
    final self = this as Catalog;
    final nextProducts = List<Product>.of(
      (products ?? self.products).map((item_1) => item_1.copyWith()),
    );
    final nextCategoryById = Map<String, Category>.fromEntries(
      (categoryById ?? self.categoryById).entries.map(
        (entry_2) => MapEntry(entry_2.key, (entry_2.value).copyWith()),
      ),
    );
    final nextFeaturedSkus = Set<String>.of(featuredSkus ?? self.featuredSkus);
    final nextInventory = List<InventoryEntry>.of(
      (inventory ?? self.inventory).map((item_4) => item_4.copyWith()),
    );

    return Catalog(
      id: id ?? self.id,
      products: nextProducts,
      categoryById: nextCategoryById,
      featuredSkus: nextFeaturedSkus,
      inventory: nextInventory,
    );
  }
}
