// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'category.dart';

const DeepCollectionEquality _dustUnorderedDeepCollectionEquality = DeepCollectionEquality.unordered();

mixin _$CategoryDust {
  Category get _dustSelf => this as Category;

  @override
  String toString() {
    return 'Category('
        'id: ${_dustSelf.id}, '
        'title: ${_dustSelf.title}, '
        'labels: ${_dustSelf.labels}'
        ')';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category &&
          runtimeType == other.runtimeType &&
          other.id == _dustSelf.id &&
          other.title == _dustSelf.title &&
          _dustUnorderedDeepCollectionEquality.equals(other.labels, _dustSelf.labels);

  @override
  int get hashCode => Object.hashAll([
    runtimeType,
    _dustSelf.id,
    _dustSelf.title,
    _dustUnorderedDeepCollectionEquality.hash(_dustSelf.labels),
  ]);

  Category copyWith({
    String? id,
    String? title,
    Set<String>? labels,
  }) {
    final nextLabels = Set<String>.of(labels ?? _dustSelf.labels);

    return Category(
      id: id ?? _dustSelf.id,
      title: title ?? _dustSelf.title,
      labels: nextLabels,
    );
  }
}
