// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by dust.

part of 'category.dart';

const DeepCollectionEquality _dustUnorderedDeepCollectionEquality = DeepCollectionEquality.unordered();

mixin _$CategoryDust {
  Category get _dustSelf => this as Category;

  @override
  String toString() => 'Category(id: ${_dustSelf.id}, title: ${_dustSelf.title}, labels: ${_dustSelf.labels})';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category &&
          runtimeType == other.runtimeType &&
          other.id == _dustSelf.id &&
          other.title == _dustSelf.title &&
          _dustUnorderedDeepCollectionEquality.equals(other.labels, _dustSelf.labels);

  @override
  int get hashCode => Object.hashAll([
    runtimeType,
    _dustSelf.id,
    _dustSelf.title,
    _dustUnorderedDeepCollectionEquality.hash(_dustSelf.labels),
  ]);

  Category copyWith({
    String? id,
    String? title,
    Set<String>? labels,
  }) {
    final nextIdSource = id ?? _dustSelf.id;
    final nextId = nextIdSource;
    final nextTitleSource = title ?? _dustSelf.title;
    final nextTitle = nextTitleSource;
    final nextLabelsSource = labels ?? _dustSelf.labels;
    final nextLabels = Set<String>.of(nextLabelsSource);

    return Category(
      id: nextId,
      title: nextTitle,
      labels: nextLabels,
    );
  }

  Category clone() {
    final clonedId = _dustSelf.id;
    final clonedTitle = _dustSelf.title;
    final clonedLabels = Set<String>.of(_dustSelf.labels);

    return Category(
      id: clonedId,
      title: clonedTitle,
      labels: clonedLabels,
    );
  }
}
