// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'entity.dart';

const DeepCollectionEquality _detailedEntityTagsEquality = DeepCollectionEquality();

mixin _$Entity {
  @override
  String toString() {
    final self = this as Entity;
    return 'Entity('
        'id: ${self.id}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Entity;
    return identical(this, other) ||
        other is Entity &&
            runtimeType == other.runtimeType &&
            other.id == self.id;
  }

  @override
  int get hashCode {
    final self = this as Entity;
    return Object.hashAll([
      runtimeType,
      self.id,
    ]);
  }
}

mixin _$DetailedEntity {
  @override
  String toString() {
    final self = this as DetailedEntity;
    return 'DetailedEntity('
        'id: ${self.id}, '
        'label: ${self.label}, '
        'tags: ${self.tags}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as DetailedEntity;
    return identical(this, other) ||
        other is DetailedEntity &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.label == self.label &&
            _detailedEntityTagsEquality.equals(other.tags, self.tags);
  }

  @override
  int get hashCode {
    final self = this as DetailedEntity;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.label,
      _detailedEntityTagsEquality.hash(self.tags),
    ]);
  }

  /// Creates a copy of this `DetailedEntity` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = detailedEntity.copyWith(id: 'John');
  /// ```
  @pragma('vm:prefer-inline')
  _$DetailedEntityCopyWith<DetailedEntity> get copyWith => _$DetailedEntityCopyWithImpl<DetailedEntity>(this as DetailedEntity, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$DetailedEntityCopyWith<$Res> {
  $Res call({
    String? id,
    String? label,
    List<String>? tags,
  });
}

/// @nodoc
final class _$DetailedEntityCopyWithImpl<$Res> implements _$DetailedEntityCopyWith<$Res> {
  const _$DetailedEntityCopyWithImpl(this._self, this._then);

  final DetailedEntity _self;
  final $Res Function(DetailedEntity) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? id = null,
    Object? label = null,
    Object? tags = null,
  }) {
    return _then(
      DetailedEntity(
        id == null ? _self.id : id as String,
        label: label == null ? _self.label : label as String,
        tags: tags == null ? _self.tags : tags as List<String>,
      )
    );
  }
}
