// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'featured_product.dart';

const DeepCollectionEquality _dustUnorderedDeepCollectionEquality = DeepCollectionEquality.unordered();

mixin _$FeaturedProductDust {
  FeaturedProduct get _dustSelf => this as FeaturedProduct;

  @override
  String toString() {
    return 'FeaturedProduct('
        'sku: ${_dustSelf.sku}, '
        'price: ${_dustSelf.price}, '
        'tags: ${_dustSelf.tags}, '
        'archived: ${_dustSelf.archived}'
        ')';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeaturedProduct &&
          runtimeType == other.runtimeType &&
          other.sku == _dustSelf.sku &&
          other.price == _dustSelf.price &&
          _dustUnorderedDeepCollectionEquality.equals(other.tags, _dustSelf.tags) &&
          other.archived == _dustSelf.archived;

  @override
  int get hashCode => Object.hashAll([
    runtimeType,
    _dustSelf.sku,
    _dustSelf.price,
    _dustUnorderedDeepCollectionEquality.hash(_dustSelf.tags),
    _dustSelf.archived,
  ]);

  FeaturedProduct copyWith({
    String? sku,
    Price? price,
    Set<String>? tags,
    bool? archived,
  }) {
    final nextPrice = (price ?? _dustSelf.price).copyWith();
    final nextTags = Set<String>.of(tags ?? _dustSelf.tags);

    return FeaturedProduct(
      sku: sku ?? _dustSelf.sku,
      price: nextPrice,
      tags: nextTags,
      archived: archived ?? _dustSelf.archived,
    );
  }
}
