// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'json_serde_options.dart';

const DeepCollectionEquality _deepCollectionEquality = DeepCollectionEquality();
Never _jsonTypeError(Object? value, String key, String expected) =>
    throw ArgumentError.value(value, key, 'expected $expected');
T _jsonAs<T>(Object? value, String key, String expected) =>
    value is T ? value : _jsonTypeError(value, key, expected);
T _jsonParseString<T>(
  Object? value,
  String key,
  String expected,
  T? Function(String value) parse,
) =>
    parse(_jsonAs<String>(value, key, 'String')) ??
    _jsonTypeError(value, key, expected);
List<Object?> _jsonAsList(Object? value, String key) =>
    _jsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _jsonAsMap(Object? value, String key) {
  final map = _jsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _jsonTypeError(value, key, 'Map<String, Object?>');
  }
}

DateTime _jsonAsDateTime(Object? value, String key) =>
    _jsonParseString(value, key, 'ISO-8601 DateTime string', DateTime.tryParse);
Uri _jsonAsUri(Object? value, String key) =>
    _jsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _jsonAsBigInt(Object? value, String key) =>
    _jsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _jsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

mixin _$JsonSerdeOptions {
  @override
  String toString() {
    final self = this as JsonSerdeOptions;
    return 'JsonSerdeOptions('
        'id: ${self.id}, '
        'e: ${self.e}, '
        'displayName: ${self.displayName}, '
        'tags: ${self.tags}, '
        'serverOnly: ${self.serverOnly}, '
        'clientOnly: ${self.clientOnly}, '
        'hidden: ${self.hidden}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as JsonSerdeOptions;
    return identical(this, other) ||
        other is JsonSerdeOptions &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.e == self.e &&
            other.displayName == self.displayName &&
            _deepCollectionEquality.equals(other.tags, self.tags) &&
            other.serverOnly == self.serverOnly &&
            other.clientOnly == self.clientOnly &&
            other.hidden == self.hidden;
  }

  @override
  int get hashCode {
    final self = this as JsonSerdeOptions;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.e,
      self.displayName,
      _deepCollectionEquality.hash(self.tags),
      self.serverOnly,
      self.clientOnly,
      self.hidden,
    ]);
  }

  Map<String, Object?> toJson() =>
      _$JsonSerdeOptionsToJson(this as JsonSerdeOptions);
}

Map<String, Object?> _$JsonSerdeOptionsToJson(JsonSerdeOptions instance) {
  return <String, Object?>{
    'id': instance.id,
    'e': _$MyEnumToJson(instance.e),
    'display_name': instance.displayName,
    'tags': instance.tags.map((item) => item).toList(),
    'client_only': instance.clientOnly,
  };
}

// factory JsonSerdeOptions.fromJson(Map<String, Object?> json) => _$JsonSerdeOptionsFromJson(json);
JsonSerdeOptions _$JsonSerdeOptionsFromJson(Map<String, Object?> json) {
  const allowedKeys = <String>{
    'id',
    'e',
    'display_name',
    'displayName',
    'tags',
    'server_only',
    'client_only',
    'hidden',
  };
  for (final key in json.keys) {
    if (!allowedKeys.contains(key)) {
      throw ArgumentError.value(
        key,
        'json',
        'unknown key for JsonSerdeOptions',
      );
    }
  }

  final idValue = _jsonAs<String>(json['id'], 'id', 'String');
  final eValue = _$MyEnumFromJson(json['e']);
  final rawDisplayNameKey = json.containsKey('display_name')
      ? 'display_name'
      : json.containsKey('displayName')
      ? 'displayName'
      : 'display_name';
  final rawDisplayName = json.containsKey('display_name')
      ? json['display_name']
      : json.containsKey('displayName')
      ? json['displayName']
      : null;
  final displayNameValue = _jsonAs<String>(
    rawDisplayName,
    rawDisplayNameKey,
    'String',
  );
  final tagsValue = json.containsKey('tags')
      ? _jsonAsList(
          json['tags'],
          'tags',
        ).map((item) => _jsonAs<String>(item, 'tags', 'String')).toList()
      : ['guest'];
  final serverOnlyValue = json.containsKey('server_only')
      ? _jsonAs<String>(json['server_only'], 'server_only', 'String')
      : 'server-default';
  final clientOnlyValue = 'client-default';
  final hiddenValue = 'hidden-default';

  return JsonSerdeOptions(
    id: idValue,
    displayName: displayNameValue,
    e: eValue,
    tags: tagsValue,
    serverOnly: serverOnlyValue,
    clientOnly: clientOnlyValue,
    hidden: hiddenValue,
  );
}

Object? _$MyEnumToJson(MyEnum instance) {
  return switch (instance) {
    MyEnum.A => 'A',
    MyEnum.B => 'B',
  };
}

MyEnum _$MyEnumFromJson(Object? json) {
  return switch (json) {
    'A' => MyEnum.A,
    'B' => MyEnum.B,
    _ => throw ArgumentError.value(json, 'json', 'unknown value for MyEnum'),
  };
}
