// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'json_workspace_capability.dart';

mixin _$JsonWorkspaceAccount {
  Map<String, Object?> toJson() =>
      _$JsonWorkspaceAccountToJson(this as JsonWorkspaceAccount);
}

Map<String, Object?> _$JsonWorkspaceAccountToJson(JsonWorkspaceAccount instance) {
  return <String, Object?>{
    'profile': instance.profile.toJson(),
    'active': instance.active,
  };
}

// factory JsonWorkspaceAccount.fromJson(Map<String, Object?> json) => _$JsonWorkspaceAccountFromJson(json);
JsonWorkspaceAccount _$JsonWorkspaceAccountFromJson(Map<String, Object?> json) {
  final profileValue = JsonWorkspaceProfile.fromJson(
    JsonHelper.asMap(json['profile'], 'profile'),
  );
  final activeValue = JsonHelper.as<bool>(json['active'], 'active', 'bool');

  return JsonWorkspaceAccount(profile: profileValue, active: activeValue);
}

Object? _$JsonWorkspaceKindToJson(JsonWorkspaceKind instance) {
  return switch (instance) {
    JsonWorkspaceKind.retail => 'retail',
    JsonWorkspaceKind.wholesale => 'wholesale',
  };
}

JsonWorkspaceKind _$JsonWorkspaceKindFromJson(Object? json, [String key = 'json']) {
  return switch (json) {
    'retail' => JsonWorkspaceKind.retail,
    'wholesale' => JsonWorkspaceKind.wholesale,
    _ => throw ArgumentError.value(json, key, 'unknown value for JsonWorkspaceKind at $key'),
  };
}
