// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'json_workspace_capability.dart';

mixin _$JsonWorkspaceAccount implements Serializable {
  Map<String, Object?> serialize() =>
      _$JsonWorkspaceAccountSerialize(this as JsonWorkspaceAccount);

  Map<String, Object?> toJson() => serialize();
}

final class $JsonWorkspaceAccountSerializer implements Serializer<JsonWorkspaceAccount, Map<String, Object?>> {
  const $JsonWorkspaceAccountSerializer();

  @override
  Map<String, Object?> serialize(JsonWorkspaceAccount value) => _$JsonWorkspaceAccountSerialize(value);
}
final class $JsonWorkspaceAccountDeserializer implements Deserializer<JsonWorkspaceAccount, Map<String, Object?>> {
  const $JsonWorkspaceAccountDeserializer();

  @override
  JsonWorkspaceAccount deserialize(Map<String, Object?> json) => _$JsonWorkspaceAccountDeserialize(json);
}
final class $JsonWorkspaceKindSerializer implements Serializer<JsonWorkspaceKind, Object?> {
  const $JsonWorkspaceKindSerializer();

  @override
  Object? serialize(JsonWorkspaceKind value) => _$JsonWorkspaceKindSerialize(value);
}
final class $JsonWorkspaceKindDeserializer implements Deserializer<JsonWorkspaceKind, Object?> {
  const $JsonWorkspaceKindDeserializer();

  @override
  JsonWorkspaceKind deserialize(Object? json) => _$JsonWorkspaceKindDeserialize(json);
}

Map<String, Object?> _$JsonWorkspaceAccountSerialize(JsonWorkspaceAccount instance) {
  return <String, Object?>{
    'profile': instance.profile.toJson(),
    'active': instance.active,
  };
}

Map<String, Object?> _$JsonWorkspaceAccountToJson(JsonWorkspaceAccount instance) =>
    _$JsonWorkspaceAccountSerialize(instance);

// factory JsonWorkspaceAccount.fromJson(Map<String, Object?> json) => _$JsonWorkspaceAccountFromJson(json);
JsonWorkspaceAccount _$JsonWorkspaceAccountDeserialize(Map<String, Object?> json) {
  final profileValue = JsonWorkspaceProfile.fromJson(
    JsonHelper.asMap(json['profile'], 'profile'),
  );
  final activeValue = JsonHelper.as<bool>(json['active'], 'active', 'bool');

  return JsonWorkspaceAccount(profile: profileValue, active: activeValue);
}

JsonWorkspaceAccount _$JsonWorkspaceAccountFromJson(Map<String, Object?> json) =>
    _$JsonWorkspaceAccountDeserialize(json);

Object? _$JsonWorkspaceKindSerialize(JsonWorkspaceKind instance) {
  return switch (instance) {
    JsonWorkspaceKind.retail => 'retail',
    JsonWorkspaceKind.wholesale => 'wholesale',
  };
}

Object? _$JsonWorkspaceKindToJson(JsonWorkspaceKind instance) =>
    _$JsonWorkspaceKindSerialize(instance);

JsonWorkspaceKind _$JsonWorkspaceKindDeserialize(Object? json, [String key = 'json']) {
  return switch (json) {
    'retail' => JsonWorkspaceKind.retail,
    'wholesale' => JsonWorkspaceKind.wholesale,
    _ => throw ArgumentError.value(json, key, 'unknown value for JsonWorkspaceKind at $key'),
  };
}

JsonWorkspaceKind _$JsonWorkspaceKindFromJson(Object? json, [String key = 'json']) =>
    _$JsonWorkspaceKindDeserialize(json, key);
