// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'json_enum_bundle.dart';

const DeepCollectionEquality _jsonEnumBundleLevelsEquality = DeepCollectionEquality();
const DeepCollectionEquality _jsonEnumBundleStateByRegionEquality = DeepCollectionEquality();
const DeepCollectionEquality _jsonEnumBundleStatesEquality = DeepCollectionEquality.unordered();

mixin _$JsonEnumBundle {
  @override
  String toString() {
    final self = this as JsonEnumBundle;
    return 'JsonEnumBundle('
        'primaryLevel: ${self.primaryLevel}, '
        'fallbackState: ${self.fallbackState}, '
        'levels: ${self.levels}, '
        'stateByRegion: ${self.stateByRegion}, '
        'states: ${self.states}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as JsonEnumBundle;
    return identical(this, other) ||
        other is JsonEnumBundle &&
            runtimeType == other.runtimeType &&
            other.primaryLevel == self.primaryLevel &&
            other.fallbackState == self.fallbackState &&
            _jsonEnumBundleLevelsEquality.equals(other.levels, self.levels) &&
            _jsonEnumBundleStateByRegionEquality.equals(other.stateByRegion, self.stateByRegion) &&
            _jsonEnumBundleStatesEquality.equals(other.states, self.states);
  }

  @override
  int get hashCode {
    final self = this as JsonEnumBundle;
    return Object.hashAll([
      runtimeType,
      self.primaryLevel,
      self.fallbackState,
      _jsonEnumBundleLevelsEquality.hash(self.levels),
      _jsonEnumBundleStateByRegionEquality.hash(self.stateByRegion),
      _jsonEnumBundleStatesEquality.hash(self.states),
    ]);
  }

  Map<String, Object?> toJson() =>
      _$JsonEnumBundleToJson(this as JsonEnumBundle);
}

Map<String, Object?> _$JsonEnumBundleToJson(JsonEnumBundle instance) {
  return <String, Object?>{
    'primary_level': _$AccessLevelToJson(instance.primaryLevel),
    'fallbackState': instance.fallbackState == null
        ? null
        : _$ReviewStateToJson((instance.fallbackState!)),
    'levels': instance.levels
        .map((item) => _$AccessLevelToJson(item))
        .toList(),
    'stateByRegion': instance.stateByRegion
        .map((key, value) => MapEntry(key, _$ReviewStateToJson(value))),
    'states': instance.states
        .map((item) => _$ReviewStateToJson(item))
        .toList(),
  };
}

// factory JsonEnumBundle.fromJson(Map<String, Object?> json) => _$JsonEnumBundleFromJson(json);
JsonEnumBundle _$JsonEnumBundleFromJson(Map<String, Object?> json) {
  Object? rawPrimaryLevel;
  if (json.containsKey('primary_level')) {
    rawPrimaryLevel = json['primary_level'];
  } else if (json.containsKey('primaryLevel')) {
    rawPrimaryLevel = json['primaryLevel'];
  }
  final primaryLevelValue = _$AccessLevelFromJson(rawPrimaryLevel);
  final fallbackStateValue = json['fallbackState'] == null
      ? null
      : _$ReviewStateFromJson(json['fallbackState']);
  final levelsValue = JsonHelper.asList(json['levels'], 'levels')
      .map((item) => _$AccessLevelFromJson(item))
      .toList();
  final stateByRegionValue = JsonHelper.asMap(json['stateByRegion'], 'stateByRegion')
      .map((mapKey, value) => MapEntry(mapKey, _$ReviewStateFromJson(value)));
  final statesValue = JsonHelper.asList(json['states'], 'states')
      .map((item) => _$ReviewStateFromJson(item))
      .toSet();

  return JsonEnumBundle(
    primaryLevel: primaryLevelValue,
    fallbackState: fallbackStateValue,
    levels: levelsValue,
    stateByRegion: stateByRegionValue,
    states: statesValue,
  );
}

Object? _$AccessLevelToJson(AccessLevel instance) {
  return switch (instance) {
    AccessLevel.superAdmin => 'super-admin',
    AccessLevel.guestUser => 'guest-user',
    AccessLevel.readOnly => 'read-only',
  };
}

AccessLevel _$AccessLevelFromJson(Object? json) {
  return switch (json) {
    'super-admin' => AccessLevel.superAdmin,
    'guest-user' => AccessLevel.guestUser,
    'read-only' => AccessLevel.readOnly,
    _ => throw ArgumentError.value(json, 'json', 'unknown value for AccessLevel'),
  };
}

Object? _$ReviewStateToJson(ReviewState instance) {
  return switch (instance) {
    ReviewState.pending => 'pending',
    ReviewState.approved => 'approved',
    ReviewState.archived => 'archived',
  };
}

ReviewState _$ReviewStateFromJson(Object? json) {
  return switch (json) {
    'pending' => ReviewState.pending,
    'approved' => ReviewState.approved,
    'archived' => ReviewState.archived,
    _ => throw ArgumentError.value(json, 'json', 'unknown value for ReviewState'),
  };
}
