// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'json_scalar_bundle.dart';

const DeepCollectionEquality _deepCollectionEquality = DeepCollectionEquality();
const DeepCollectionEquality _unorderedDeepCollectionEquality =
    DeepCollectionEquality.unordered();
Never _jsonTypeError(Object? value, String key, String expected) =>
    throw ArgumentError.value(value, key, 'expected $expected');
T _jsonAs<T>(Object? value, String key, String expected) =>
    value is T ? value : _jsonTypeError(value, key, expected);
T _jsonParseString<T>(
  Object? value,
  String key,
  String expected,
  T? Function(String value) parse,
) =>
    parse(_jsonAs<String>(value, key, 'String')) ??
    _jsonTypeError(value, key, expected);
List<Object?> _jsonAsList(Object? value, String key) =>
    _jsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _jsonAsMap(Object? value, String key) {
  final map = _jsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _jsonTypeError(value, key, 'Map<String, Object?>');
  }
}

DateTime _jsonAsDateTime(Object? value, String key) =>
    _jsonParseString(value, key, 'ISO-8601 DateTime string', DateTime.tryParse);
Uri _jsonAsUri(Object? value, String key) =>
    _jsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _jsonAsBigInt(Object? value, String key) =>
    _jsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _jsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

mixin _$JsonScalarBundle {
  @override
  String toString() {
    final self = this as JsonScalarBundle;
    return 'JsonScalarBundle('
        'createdAt: ${self.createdAt}, '
        'updatedAt: ${self.updatedAt}, '
        'website: ${self.website}, '
        'largeNumber: ${self.largeNumber}, '
        'endpoints: ${self.endpoints}, '
        'checkpoints: ${self.checkpoints}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as JsonScalarBundle;
    return identical(this, other) ||
        other is JsonScalarBundle &&
            runtimeType == other.runtimeType &&
            other.createdAt == self.createdAt &&
            other.updatedAt == self.updatedAt &&
            other.website == self.website &&
            other.largeNumber == self.largeNumber &&
            _unorderedDeepCollectionEquality.equals(
              other.endpoints,
              self.endpoints,
            ) &&
            _deepCollectionEquality.equals(other.checkpoints, self.checkpoints);
  }

  @override
  int get hashCode {
    final self = this as JsonScalarBundle;
    return Object.hashAll([
      runtimeType,
      self.createdAt,
      self.updatedAt,
      self.website,
      self.largeNumber,
      _unorderedDeepCollectionEquality.hash(self.endpoints),
      _deepCollectionEquality.hash(self.checkpoints),
    ]);
  }

  Map<String, Object?> toJson() =>
      _$JsonScalarBundleToJson(this as JsonScalarBundle);
}

Map<String, Object?> _$JsonScalarBundleToJson(JsonScalarBundle instance) {
  return <String, Object?>{
    'createdAt': instance.createdAt.toIso8601String(),
    'updatedAt': instance.updatedAt == null
        ? null
        : (instance.updatedAt!).toIso8601String(),
    'website': instance.website.toString(),
    'largeNumber': instance.largeNumber.toString(),
    'endpoints': instance.endpoints.map((item) => item.toString()).toList(),
    'checkpoints': instance.checkpoints.map(
      (key, value) => MapEntry(key, value.toIso8601String()),
    ),
  };
}

// factory JsonScalarBundle.fromJson(Map<String, Object?> json) => _$JsonScalarBundleFromJson(json);
JsonScalarBundle _$JsonScalarBundleFromJson(Map<String, Object?> json) {
  final createdAtValue = _jsonAsDateTime(json['createdAt'], 'createdAt');
  final updatedAtValue = json['updatedAt'] == null
      ? null
      : _jsonAsDateTime(json['updatedAt'], 'updatedAt');
  final websiteValue = _jsonAsUri(json['website'], 'website');
  final largeNumberValue = _jsonAsBigInt(json['largeNumber'], 'largeNumber');
  final endpointsValue = _jsonAsList(
    json['endpoints'],
    'endpoints',
  ).map((item) => _jsonAsUri(item, 'endpoints')).toSet();
  final checkpointsValue = _jsonAsMap(json['checkpoints'], 'checkpoints').map(
    (mapKey, value) => MapEntry(mapKey, _jsonAsDateTime(value, 'checkpoints')),
  );

  return JsonScalarBundle(
    createdAt: createdAtValue,
    updatedAt: updatedAtValue,
    website: websiteValue,
    largeNumber: largeNumberValue,
    endpoints: endpointsValue,
    checkpoints: checkpointsValue,
  );
}
