// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'json_scalar_bundle.dart';

const DeepCollectionEquality _dustDeepCollectionEquality = DeepCollectionEquality();
const DeepCollectionEquality _dustUnorderedDeepCollectionEquality = DeepCollectionEquality.unordered();
Never _dustJsonTypeError(Object? value, String key, String expected) => throw ArgumentError.value(value, key, 'expected $expected');
T _dustJsonAs<T>(Object? value, String key, String expected) => value is T ? value : _dustJsonTypeError(value, key, expected);
T _dustJsonParseString<T>(Object? value, String key, String expected, T? Function(String value) parse) => parse(_dustJsonAs<String>(value, key, 'String')) ?? _dustJsonTypeError(value, key, expected);
List<Object?> _dustJsonAsList(Object? value, String key) => _dustJsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _dustJsonAsMap(Object? value, String key) {
  final map = _dustJsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _dustJsonTypeError(value, key, 'Map<String, Object?>');
  }
}
DateTime _dustJsonAsDateTime(Object? value, String key) => _dustJsonParseString(value, key, 'ISO-8601 DateTime string', DateTime.tryParse);
Uri _dustJsonAsUri(Object? value, String key) => _dustJsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _dustJsonAsBigInt(Object? value, String key) => _dustJsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _dustJsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

mixin _$JsonScalarBundleDust {
  JsonScalarBundle get _dustSelf => this as JsonScalarBundle;

  @override
  String toString() {
    return 'JsonScalarBundle('
        'createdAt: ${_dustSelf.createdAt}, '
        'updatedAt: ${_dustSelf.updatedAt}, '
        'website: ${_dustSelf.website}, '
        'largeNumber: ${_dustSelf.largeNumber}, '
        'endpoints: ${_dustSelf.endpoints}, '
        'checkpoints: ${_dustSelf.checkpoints}'
        ')';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsonScalarBundle &&
          runtimeType == other.runtimeType &&
          other.createdAt == _dustSelf.createdAt &&
          other.updatedAt == _dustSelf.updatedAt &&
          other.website == _dustSelf.website &&
          other.largeNumber == _dustSelf.largeNumber &&
          _dustUnorderedDeepCollectionEquality.equals(other.endpoints, _dustSelf.endpoints) &&
          _dustDeepCollectionEquality.equals(other.checkpoints, _dustSelf.checkpoints);

  @override
  int get hashCode => Object.hashAll([
    runtimeType,
    _dustSelf.createdAt,
    _dustSelf.updatedAt,
    _dustSelf.website,
    _dustSelf.largeNumber,
    _dustUnorderedDeepCollectionEquality.hash(_dustSelf.endpoints),
    _dustDeepCollectionEquality.hash(_dustSelf.checkpoints),
  ]);

  Map<String, Object?> toJson() => _$JsonScalarBundleToJson(_dustSelf);
}

Map<String, Object?> _$JsonScalarBundleToJson(JsonScalarBundle instance) {
  return <String, Object?>{
    'createdAt': instance.createdAt.toIso8601String(),
    'updatedAt': instance.updatedAt == null ? null : (instance.updatedAt!).toIso8601String(),
    'website': instance.website.toString(),
    'largeNumber': instance.largeNumber.toString(),
    'endpoints': instance.endpoints.map((item) => item.toString()).toList(),
    'checkpoints': instance.checkpoints.map((key, value) => MapEntry(key, value.toIso8601String())),
  };
}
// factory JsonScalarBundle.fromJson(Map<String, Object?> json) => _$JsonScalarBundleFromJson(json);
JsonScalarBundle _$JsonScalarBundleFromJson(Map<String, Object?> json) {
  final createdAtValue = _dustJsonAsDateTime(json['createdAt'], 'createdAt');
  final updatedAtValue = json['updatedAt'] == null
                         ? null
                         : _dustJsonAsDateTime(json['updatedAt'], 'updatedAt');
  final websiteValue = _dustJsonAsUri(json['website'], 'website');
  final largeNumberValue = _dustJsonAsBigInt(json['largeNumber'], 'largeNumber');
  final endpointsValue = _dustJsonAsList(json['endpoints'], 'endpoints').map((item) => _dustJsonAsUri(item, 'endpoints')).toSet();
  final checkpointsValue = _dustJsonAsMap(json['checkpoints'], 'checkpoints').map((mapKey, value) => MapEntry(mapKey, _dustJsonAsDateTime(value, 'checkpoints')));

  return JsonScalarBundle(
    createdAt: createdAtValue,
    updatedAt: updatedAtValue,
    website: websiteValue,
    largeNumber: largeNumberValue,
    endpoints: endpointsValue,
    checkpoints: checkpointsValue,
  );
}
