// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'json_enum_bundle.dart';

const DeepCollectionEquality _deepCollectionEquality = DeepCollectionEquality();
const DeepCollectionEquality _unorderedDeepCollectionEquality =
    DeepCollectionEquality.unordered();
Never _jsonTypeError(Object? value, String key, String expected) =>
    throw ArgumentError.value(value, key, 'expected $expected');
T _jsonAs<T>(Object? value, String key, String expected) =>
    value is T ? value : _jsonTypeError(value, key, expected);
T _jsonParseString<T>(
  Object? value,
  String key,
  String expected,
  T? Function(String value) parse,
) =>
    parse(_jsonAs<String>(value, key, 'String')) ??
    _jsonTypeError(value, key, expected);
List<Object?> _jsonAsList(Object? value, String key) =>
    _jsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _jsonAsMap(Object? value, String key) {
  final map = _jsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _jsonTypeError(value, key, 'Map<String, Object?>');
  }
}

DateTime _jsonAsDateTime(Object? value, String key) =>
    _jsonParseString(value, key, 'ISO-8601 DateTime string', DateTime.tryParse);
Uri _jsonAsUri(Object? value, String key) =>
    _jsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _jsonAsBigInt(Object? value, String key) =>
    _jsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _jsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

mixin _$JsonEnumBundle {
  @override
  String toString() {
    final self = this as JsonEnumBundle;
    return 'JsonEnumBundle('
        'primaryLevel: ${self.primaryLevel}, '
        'fallbackState: ${self.fallbackState}, '
        'levels: ${self.levels}, '
        'stateByRegion: ${self.stateByRegion}, '
        'states: ${self.states}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as JsonEnumBundle;
    return identical(this, other) ||
        other is JsonEnumBundle &&
            runtimeType == other.runtimeType &&
            other.primaryLevel == self.primaryLevel &&
            other.fallbackState == self.fallbackState &&
            _deepCollectionEquality.equals(other.levels, self.levels) &&
            _deepCollectionEquality.equals(
              other.stateByRegion,
              self.stateByRegion,
            ) &&
            _unorderedDeepCollectionEquality.equals(other.states, self.states);
  }

  @override
  int get hashCode {
    final self = this as JsonEnumBundle;
    return Object.hashAll([
      runtimeType,
      self.primaryLevel,
      self.fallbackState,
      _deepCollectionEquality.hash(self.levels),
      _deepCollectionEquality.hash(self.stateByRegion),
      _unorderedDeepCollectionEquality.hash(self.states),
    ]);
  }

  Map<String, Object?> toJson() =>
      _$JsonEnumBundleToJson(this as JsonEnumBundle);
}

Map<String, Object?> _$JsonEnumBundleToJson(JsonEnumBundle instance) {
  return <String, Object?>{
    'primary_level': _$AccessLevelToJson(instance.primaryLevel),
    'fallbackState': instance.fallbackState == null
        ? null
        : _$ReviewStateToJson((instance.fallbackState!)),
    'levels': instance.levels.map((item) => _$AccessLevelToJson(item)).toList(),
    'stateByRegion': instance.stateByRegion.map(
      (key, value) => MapEntry(key, _$ReviewStateToJson(value)),
    ),
    'states': instance.states.map((item) => _$ReviewStateToJson(item)).toList(),
  };
}

// factory JsonEnumBundle.fromJson(Map<String, Object?> json) => _$JsonEnumBundleFromJson(json);
JsonEnumBundle _$JsonEnumBundleFromJson(Map<String, Object?> json) {
  final rawPrimaryLevel = json.containsKey('primary_level')
      ? json['primary_level']
      : json.containsKey('primaryLevel')
      ? json['primaryLevel']
      : null;
  final primaryLevelValue = _$AccessLevelFromJson(rawPrimaryLevel);
  final fallbackStateValue = json['fallbackState'] == null
      ? null
      : _$ReviewStateFromJson(json['fallbackState']);
  final levelsValue = _jsonAsList(
    json['levels'],
    'levels',
  ).map((item) => _$AccessLevelFromJson(item)).toList();
  final stateByRegionValue = _jsonAsMap(
    json['stateByRegion'],
    'stateByRegion',
  ).map((mapKey, value) => MapEntry(mapKey, _$ReviewStateFromJson(value)));
  final statesValue = _jsonAsList(
    json['states'],
    'states',
  ).map((item) => _$ReviewStateFromJson(item)).toSet();

  return JsonEnumBundle(
    primaryLevel: primaryLevelValue,
    fallbackState: fallbackStateValue,
    levels: levelsValue,
    stateByRegion: stateByRegionValue,
    states: statesValue,
  );
}

Object? _$AccessLevelToJson(AccessLevel instance) {
  return switch (instance) {
    AccessLevel.superAdmin => 'super-admin',
    AccessLevel.guestUser => 'guest-user',
    AccessLevel.readOnly => 'read-only',
  };
}

AccessLevel _$AccessLevelFromJson(Object? json) {
  return switch (json) {
    'super-admin' => AccessLevel.superAdmin,
    'guest-user' => AccessLevel.guestUser,
    'read-only' => AccessLevel.readOnly,
    _ => throw ArgumentError.value(
      json,
      'json',
      'unknown value for AccessLevel',
    ),
  };
}

Object? _$ReviewStateToJson(ReviewState instance) {
  return switch (instance) {
    ReviewState.pending => 'pending',
    ReviewState.approved => 'approved',
    ReviewState.archived => 'archived',
  };
}

ReviewState _$ReviewStateFromJson(Object? json) {
  return switch (json) {
    'pending' => ReviewState.pending,
    'approved' => ReviewState.approved,
    'archived' => ReviewState.archived,
    _ => throw ArgumentError.value(
      json,
      'json',
      'unknown value for ReviewState',
    ),
  };
}
