// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'json_untagged_event.dart';

mixin _$JsonUntaggedEvent implements Serializable {
  Map<String, Object?> serialize() =>
      _$JsonUntaggedEventSerialize(this as JsonUntaggedEvent);

  Map<String, Object?> toJson() => serialize();
}

final class $JsonUntaggedEventSerializer implements Serializer<JsonUntaggedEvent, Map<String, Object?>> {
  const $JsonUntaggedEventSerializer();

  @override
  Map<String, Object?> serialize(JsonUntaggedEvent value) => _$JsonUntaggedEventSerialize(value);
}
final class $JsonUntaggedEventDeserializer implements Deserializer<JsonUntaggedEvent, Map<String, Object?>> {
  const $JsonUntaggedEventDeserializer();

  @override
  JsonUntaggedEvent deserialize(Map<String, Object?> json) => _$JsonUntaggedEventDeserialize(json);
}
final class JsonSignupEvent extends JsonUntaggedEvent {
  const JsonSignupEvent({
    required this.id,
    required this.email,
  }) : super();

  factory JsonSignupEvent.fromJson(Map<String, Object?> json) =>
      _$JsonSignupEventFromJson(json);

  final String id;
  final String email;
}

final class JsonArchiveEvent extends JsonUntaggedEvent {
  const JsonArchiveEvent({
    required this.id,
    required this.reason,
  }) : super();

  factory JsonArchiveEvent.fromJson(Map<String, Object?> json) =>
      _$JsonArchiveEventFromJson(json);

  final String id;
  final String reason;
}
final class $JsonSignupEventSerializer implements Serializer<JsonSignupEvent, Map<String, Object?>> {
  const $JsonSignupEventSerializer();

  @override
  Map<String, Object?> serialize(JsonSignupEvent value) => _$JsonSignupEventSerialize(value);
}
final class $JsonSignupEventDeserializer implements Deserializer<JsonSignupEvent, Map<String, Object?>> {
  const $JsonSignupEventDeserializer();

  @override
  JsonSignupEvent deserialize(Map<String, Object?> json) => _$JsonSignupEventDeserialize(json);
}
final class $JsonArchiveEventSerializer implements Serializer<JsonArchiveEvent, Map<String, Object?>> {
  const $JsonArchiveEventSerializer();

  @override
  Map<String, Object?> serialize(JsonArchiveEvent value) => _$JsonArchiveEventSerialize(value);
}
final class $JsonArchiveEventDeserializer implements Deserializer<JsonArchiveEvent, Map<String, Object?>> {
  const $JsonArchiveEventDeserializer();

  @override
  JsonArchiveEvent deserialize(Map<String, Object?> json) => _$JsonArchiveEventDeserialize(json);
}

Map<String, Object?> _$JsonUntaggedEventSerialize(JsonUntaggedEvent instance) {
  return switch (instance) {
    JsonSignupEvent value => _$JsonSignupEventSerialize(value),
    JsonArchiveEvent value => _$JsonArchiveEventSerialize(value),
  };
}

Map<String, Object?> _$JsonUntaggedEventToJson(JsonUntaggedEvent instance) =>
    _$JsonUntaggedEventSerialize(instance);

// factory JsonUntaggedEvent.fromJson(Map<String, Object?> json) => _$JsonUntaggedEventFromJson(json);
JsonUntaggedEvent _$JsonUntaggedEventDeserialize(Map<String, Object?> json) {
  try {
    return _$JsonSignupEventDeserialize(json);
  } on Object {
    // Try the next untagged SerDe variant.
  }
  try {
    return _$JsonArchiveEventDeserialize(json);
  } on Object {
    // Try the next untagged SerDe variant.
  }
  throw ArgumentError.value(
    json,
    'json',
    'no matching SerDe variant for JsonUntaggedEvent',
  );
}

JsonUntaggedEvent _$JsonUntaggedEventFromJson(Map<String, Object?> json) =>
    _$JsonUntaggedEventDeserialize(json);

Map<String, Object?> _$JsonSignupEventSerialize(JsonSignupEvent instance) {
  return <String, Object?>{
    'id': instance.id,
    'email': instance.email,
  };
}

Map<String, Object?> _$JsonSignupEventToJson(JsonSignupEvent instance) =>
    _$JsonSignupEventSerialize(instance);

// factory JsonSignupEvent.fromJson(Map<String, Object?> json) => _$JsonSignupEventFromJson(json);
JsonSignupEvent _$JsonSignupEventDeserialize(Map<String, Object?> json) {
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final emailValue = JsonHelper.as<String>(json['email'], 'email', 'String');

  return JsonSignupEvent(id: idValue, email: emailValue);
}

JsonSignupEvent _$JsonSignupEventFromJson(Map<String, Object?> json) =>
    _$JsonSignupEventDeserialize(json);

Map<String, Object?> _$JsonArchiveEventSerialize(JsonArchiveEvent instance) {
  return <String, Object?>{
    'id': instance.id,
    'reason': instance.reason,
  };
}

Map<String, Object?> _$JsonArchiveEventToJson(JsonArchiveEvent instance) =>
    _$JsonArchiveEventSerialize(instance);

// factory JsonArchiveEvent.fromJson(Map<String, Object?> json) => _$JsonArchiveEventFromJson(json);
JsonArchiveEvent _$JsonArchiveEventDeserialize(Map<String, Object?> json) {
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final reasonValue = JsonHelper.as<String>(json['reason'], 'reason', 'String');

  return JsonArchiveEvent(id: idValue, reason: reasonValue);
}

JsonArchiveEvent _$JsonArchiveEventFromJson(Map<String, Object?> json) =>
    _$JsonArchiveEventDeserialize(json);
