// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'json_codec_bundle.dart';

mixin _$JsonCodecBundle {
  @override
  String toString() {
    final self = this as JsonCodecBundle;
    return 'JsonCodecBundle('
        'createdAt: ${self.createdAt}, '
        'updatedAt: ${self.updatedAt}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as JsonCodecBundle;
    return identical(this, other) ||
        other is JsonCodecBundle &&
            runtimeType == other.runtimeType &&
            other.createdAt == self.createdAt &&
            other.updatedAt == self.updatedAt;
  }

  @override
  int get hashCode {
    final self = this as JsonCodecBundle;
    return Object.hashAll([
      runtimeType,
      self.createdAt,
      self.updatedAt,
    ]);
  }

  Map<String, Object?> toJson() =>
      _$JsonCodecBundleToJson(this as JsonCodecBundle);
}

Map<String, Object?> _$JsonCodecBundleToJson(JsonCodecBundle instance) {
  return <String, Object?>{
    'createdAt': unixEpochDateTimeCodec.serialize(instance.createdAt),
    'updatedAt': instance.updatedAt == null
        ? null
        : unixEpochDateTimeCodec.serialize(instance.updatedAt!),
  };
}

// factory JsonCodecBundle.fromJson(Map<String, Object?> json) => _$JsonCodecBundleFromJson(json);
JsonCodecBundle _$JsonCodecBundleFromJson(Map<String, Object?> json) {
  final createdAtValue = JsonHelper.decodeWithCodec<DateTime>(
    unixEpochDateTimeCodec,
    json['createdAt'],
    'createdAt',
  );
  final updatedAtValue = json['updatedAt'] == null
      ? null
      : JsonHelper.decodeWithCodec<DateTime>(unixEpochDateTimeCodec, json['updatedAt'], 'updatedAt');

  return JsonCodecBundle(createdAt: createdAtValue, updatedAt: updatedAtValue);
}
