// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'nested_bundle.dart';

const DeepCollectionEquality _deepCollectionEquality = DeepCollectionEquality();

mixin _$NestedBundle {
  @override
  String toString() {
    final self = this as NestedBundle;
    return 'NestedBundle('
        'groups: ${self.groups}, '
        'metrics: ${self.metrics}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as NestedBundle;
    return identical(this, other) ||
        other is NestedBundle &&
            runtimeType == other.runtimeType &&
            _deepCollectionEquality.equals(other.groups, self.groups) &&
            _deepCollectionEquality.equals(other.metrics, self.metrics);
  }

  @override
  int get hashCode {
    final self = this as NestedBundle;
    return Object.hashAll([
      runtimeType,
      _deepCollectionEquality.hash(self.groups),
      _deepCollectionEquality.hash(self.metrics),
    ]);
  }

  NestedBundle copyWith({
    List<List<String>>? groups,
    Map<String, List<int>>? metrics,
  }) {
    final self = this as NestedBundle;
    final nextGroups = List<List<String>>.of(
      (groups ?? self.groups).map((item_0) => List<String>.of(item_0)),
    );
    final nextMetrics = Map<String, List<int>>.fromEntries(
      (metrics ?? self.metrics).entries.map(
        (entry_1) => MapEntry(entry_1.key, List<int>.of(entry_1.value)),
      ),
    );

    return NestedBundle(
      groups: nextGroups,
      metrics: nextMetrics,
    );
  }
}
