// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'optional_note.dart';

const DeepCollectionEquality _optionalNoteAliasesEquality = DeepCollectionEquality();

mixin _$OptionalNote {
  @override
  String toString() {
    final self = this as OptionalNote;
    return 'OptionalNote('
        'id: ${self.id}, '
        'note: ${self.note}, '
        'aliases: ${self.aliases}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as OptionalNote;
    return identical(this, other) ||
        other is OptionalNote &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.note == self.note &&
            _optionalNoteAliasesEquality.equals(other.aliases, self.aliases);
  }

  @override
  int get hashCode {
    final self = this as OptionalNote;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.note,
      _optionalNoteAliasesEquality.hash(self.aliases),
    ]);
  }

  OptionalNote copyWith({
    String? id,
    Option<String?> note = const None(),
    Option<List<String>?> aliases = const None(),
  }) {
    final self = this as OptionalNote;
    final nextNote = switch (note) {
      None<String?>() => self.note,
      Some<String?>(:final value) => value,
    };
    final nextAliasesSource = switch (aliases) {
      None<List<String>?>() => self.aliases,
      Some<List<String>?>(:final value) => value,
    };
    final nextAliases = nextAliasesSource == null ? null : List<String>.of(nextAliasesSource);

    return OptionalNote(
      id: id ?? self.id,
      note: nextNote,
      aliases: nextAliases,
    );
  }
}
