// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'price.dart';

const DeepCollectionEquality _priceTagsEquality = DeepCollectionEquality();

mixin _$Price {
  @override
  String toString() {
    final self = this as Price;
    return 'Price('
        'currency: ${self.currency}, '
        'cents: ${self.cents}, '
        'tags: ${self.tags}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Price;
    return identical(this, other) ||
        other is Price &&
            runtimeType == other.runtimeType &&
            other.currency == self.currency &&
            other.cents == self.cents &&
            _priceTagsEquality.equals(other.tags, self.tags);
  }

  @override
  int get hashCode {
    final self = this as Price;
    return Object.hashAll([
      runtimeType,
      self.currency,
      self.cents,
      _priceTagsEquality.hash(self.tags),
    ]);
  }

  /// Creates a copy of this `Price` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = price.copyWith(currency: 'John');
  /// ```
  @pragma('vm:prefer-inline')
  _$PriceCopyWith<Price> get copyWith => _$PriceCopyWithImpl<Price>(this as Price, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$PriceCopyWith<$Res> {
  $Res call({
    String? currency,
    int? cents,
    List<String>? tags,
  });
}

/// @nodoc
final class _$PriceCopyWithImpl<$Res> implements _$PriceCopyWith<$Res> {
  const _$PriceCopyWithImpl(this._self, this._then);

  final Price _self;
  final $Res Function(Price) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? currency = null,
    Object? cents = null,
    Object? tags = null,
  }) {
    return _then(
      Price(
        currency: currency == null ? _self.currency : currency as String,
        cents: cents == null ? _self.cents : cents as int,
        tags: tags == null ? _self.tags : tags as List<String>,
      )
    );
  }
}
