// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'remote_comment.dart';

mixin _$RemoteComment {
  @override
  String toString() {
    final self = this as RemoteComment;
    return 'RemoteComment('
        'postId: ${self.postId}, '
        'id: ${self.id}, '
        'name: ${self.name}, '
        'email: ${self.email}, '
        'body: ${self.body}'
        ')';
  }

  RemoteComment copyWith({
    int? postId,
    int? id,
    String? name,
    String? email,
    String? body,
  }) {
    final self = this as RemoteComment;
    return RemoteComment(
      postId: postId ?? self.postId,
      id: id ?? self.id,
      name: name ?? self.name,
      email: email ?? self.email,
      body: body ?? self.body,
    );
  }

  Map<String, Object?> toJson() => _$RemoteCommentToJson(this as RemoteComment);
}

Map<String, Object?> _$RemoteCommentToJson(RemoteComment instance) {
  return <String, Object?>{
    'postId': instance.postId,
    'id': instance.id,
    'name': instance.name,
    'email': instance.email,
    'body': instance.body,
  };
}
// factory RemoteComment.fromJson(Map<String, Object?> json) => _$RemoteCommentFromJson(json);
RemoteComment _$RemoteCommentFromJson(Map<String, Object?> json) {
  final postIdValue = JsonHelper.as<int>(json['postId'], 'postId', 'int');
  final idValue = JsonHelper.as<int>(json['id'], 'id', 'int');
  final nameValue = JsonHelper.as<String>(json['name'], 'name', 'String');
  final emailValue = JsonHelper.as<String>(json['email'], 'email', 'String');
  final bodyValue = JsonHelper.as<String>(json['body'], 'body', 'String');

  return RemoteComment(
    postId: postIdValue,
    id: idValue,
    name: nameValue,
    email: emailValue,
    body: bodyValue,
  );
}
