// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'tagged_value.dart';

const DeepCollectionEquality _deepCollectionEquality = DeepCollectionEquality();

mixin _$TaggedValue {
  @override
  String toString() {
    final self = this as TaggedValue;
    return 'TaggedValue('
        'code: ${self.code}, '
        'aliases: ${self.aliases}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as TaggedValue;
    return identical(this, other) ||
        other is TaggedValue &&
            runtimeType == other.runtimeType &&
            other.code == self.code &&
            _deepCollectionEquality.equals(other.aliases, self.aliases);
  }

  @override
  int get hashCode {
    final self = this as TaggedValue;
    return Object.hashAll([
      runtimeType,
      self.code,
      _deepCollectionEquality.hash(self.aliases),
    ]);
  }

  TaggedValue copyWith({
    String? code,
    List<String>? aliases,
  }) {
    final self = this as TaggedValue;
    final nextAliases = List<String>.of(aliases ?? self.aliases);

    return TaggedValue(
      code: code ?? self.code,
      aliases: nextAliases,
    );
  }
}
