// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by dust.

part of 'tagged_value.dart';

const DeepCollectionEquality _dustDeepCollectionEquality = DeepCollectionEquality();

mixin _$TaggedValueDust {
  TaggedValue get _dustSelf => this as TaggedValue;

  @override
  String toString() {
    return 'TaggedValue('
        'code: ${_dustSelf.code}, '
        'aliases: ${_dustSelf.aliases}'
        ')';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaggedValue &&
          runtimeType == other.runtimeType &&
          other.code == _dustSelf.code &&
          _dustDeepCollectionEquality.equals(other.aliases, _dustSelf.aliases);

  @override
  int get hashCode => Object.hashAll([
    runtimeType,
    _dustSelf.code,
    _dustDeepCollectionEquality.hash(_dustSelf.aliases),
  ]);

  TaggedValue copyWith({
    String? code,
    List<String>? aliases,
  }) {
    final nextAliases = List<String>.of(aliases ?? _dustSelf.aliases);

    return TaggedValue(
      code: code ?? _dustSelf.code,
      aliases: nextAliases,
    );
  }
}
