// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'todo.dart';

final class _TodoUpdateCopyWithUnset {
  const _TodoUpdateCopyWithUnset();
}

const _todoUpdateCopyWithUnset = _TodoUpdateCopyWithUnset();

mixin _$Todo {
  @override
  String toString() {
    final self = this as Todo;
    return 'Todo('
        'id: ${self.id}, '
        'title: ${self.title}, '
        'isCompleted: ${self.isCompleted}'
        ')';
  }

  /// Creates a copy of this `Todo` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = todo.copyWith(id: 'John');
  /// ```
  @pragma('vm:prefer-inline')
  _$TodoCopyWith<Todo> get copyWith => _$TodoCopyWithImpl<Todo>(this as Todo, (value) => value);

  Map<String, Object?> toJson() => _$TodoToJson(this as Todo);
}

mixin _$TodoCreate {
  @override
  String toString() {
    final self = this as TodoCreate;
    return 'TodoCreate('
        'title: ${self.title}, '
        'isCompleted: ${self.isCompleted}'
        ')';
  }

  /// Creates a copy of this `TodoCreate` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = todoCreate.copyWith(title: 'John');
  /// ```
  @pragma('vm:prefer-inline')
  _$TodoCreateCopyWith<TodoCreate> get copyWith => _$TodoCreateCopyWithImpl<TodoCreate>(this as TodoCreate, (value) => value);

  Map<String, Object?> toJson() => _$TodoCreateToJson(this as TodoCreate);
}

mixin _$TodoUpdate {
  @override
  String toString() {
    final self = this as TodoUpdate;
    return 'TodoUpdate('
        'title: ${self.title}, '
        'isCompleted: ${self.isCompleted}'
        ')';
  }

  /// Creates a copy of this `TodoUpdate` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = todoUpdate.copyWith();
  /// final cleared = todoUpdate.copyWith(title: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$TodoUpdateCopyWith<TodoUpdate> get copyWith => _$TodoUpdateCopyWithImpl<TodoUpdate>(this as TodoUpdate, (value) => value);

  Map<String, Object?> toJson() => _$TodoUpdateToJson(this as TodoUpdate);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$TodoCopyWith<$Res> {
  $Res call({
    String? id,
    String? title,
    bool? isCompleted,
  });
}

/// @nodoc
final class _$TodoCopyWithImpl<$Res> implements _$TodoCopyWith<$Res> {
  const _$TodoCopyWithImpl(this._self, this._then);

  final Todo _self;
  final $Res Function(Todo) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? id = null,
    Object? title = null,
    Object? isCompleted = null,
  }) {
    return _then(
      Todo(
        id: id == null ? _self.id : id as String,
        title: title == null ? _self.title : title as String,
        isCompleted: isCompleted == null ? _self.isCompleted : isCompleted as bool,
      )
    );
  }
}
/// @nodoc
abstract class _$TodoCreateCopyWith<$Res> {
  $Res call({
    String? title,
    bool? isCompleted,
  });
}

/// @nodoc
final class _$TodoCreateCopyWithImpl<$Res> implements _$TodoCreateCopyWith<$Res> {
  const _$TodoCreateCopyWithImpl(this._self, this._then);

  final TodoCreate _self;
  final $Res Function(TodoCreate) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? title = null,
    Object? isCompleted = null,
  }) {
    return _then(
      TodoCreate(
        title: title == null ? _self.title : title as String,
        isCompleted: isCompleted == null ? _self.isCompleted : isCompleted as bool,
      )
    );
  }
}
/// @nodoc
abstract class _$TodoUpdateCopyWith<$Res> {
  $Res call({
    String? title,
    bool? isCompleted,
  });
}

/// @nodoc
final class _$TodoUpdateCopyWithImpl<$Res> implements _$TodoUpdateCopyWith<$Res> {
  const _$TodoUpdateCopyWithImpl(this._self, this._then);

  final TodoUpdate _self;
  final $Res Function(TodoUpdate) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? title = _todoUpdateCopyWithUnset,
    Object? isCompleted = _todoUpdateCopyWithUnset,
  }) {
    return _then(
      TodoUpdate(
        title: identical(title, _todoUpdateCopyWithUnset)
            ? _self.title
            : title as String?,
        isCompleted: identical(isCompleted, _todoUpdateCopyWithUnset)
            ? _self.isCompleted
            : isCompleted as bool?,
      )
    );
  }
}

Map<String, Object?> _$TodoToJson(Todo instance) {
  return <String, Object?>{
    'id': instance.id,
    'title': instance.title,
    'isCompleted': instance.isCompleted,
  };
}
// factory Todo.fromJson(Map<String, Object?> json) => _$TodoFromJson(json);
Todo _$TodoFromJson(Map<String, Object?> json) {
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final titleValue = JsonHelper.as<String>(json['title'], 'title', 'String');
  final isCompletedValue = JsonHelper.as<bool>(
    json['isCompleted'],
    'isCompleted',
    'bool',
  );

  return Todo(id: idValue, title: titleValue, isCompleted: isCompletedValue);
}
Map<String, Object?> _$TodoCreateToJson(TodoCreate instance) {
  return <String, Object?>{
    'title': instance.title,
    'isCompleted': instance.isCompleted,
  };
}
// factory TodoCreate.fromJson(Map<String, Object?> json) => _$TodoCreateFromJson(json);
TodoCreate _$TodoCreateFromJson(Map<String, Object?> json) {
  final titleValue = JsonHelper.as<String>(json['title'], 'title', 'String');
  final isCompletedValue = JsonHelper.as<bool>(
    json['isCompleted'],
    'isCompleted',
    'bool',
  );

  return TodoCreate(title: titleValue, isCompleted: isCompletedValue);
}
Map<String, Object?> _$TodoUpdateToJson(TodoUpdate instance) {
  return <String, Object?>{
    'title': instance.title,
    'isCompleted': instance.isCompleted,
  };
}
// factory TodoUpdate.fromJson(Map<String, Object?> json) => _$TodoUpdateFromJson(json);
TodoUpdate _$TodoUpdateFromJson(Map<String, Object?> json) {
  final titleValue = json['title'] == null
      ? null
      : JsonHelper.as<String>(json['title'], 'title', 'String');
  final isCompletedValue = json['isCompleted'] == null
      ? null
      : JsonHelper.as<bool>(json['isCompleted'], 'isCompleted', 'bool');

  return TodoUpdate(title: titleValue, isCompleted: isCompletedValue);
}
