name: Feature Request
description: Suggest an idea or a new annotation for Dust.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        We are always looking for ways to make Dust more powerful!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        Provide an example of the Dart API you'd like to use and what code should be generated.
      placeholder: |
        @MyNewAnnotation()
        class User { ... }
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
