// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by dust.
//
// ignore_for_file: unused_import, unnecessary_import

import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:dust_flutter/route.dart';

import 'paths.g.dart';
import '../route.dart';
import 'package:shopping_app/features/admin/views/admin_dashboard_screen.dart';
import 'package:shopping_app/features/admin/views/staff_dashboard_screen.dart';
import 'package:shopping_app/features/auth/views/login_screen.dart';
import 'package:shopping_app/features/auth/views/register_screen.dart';
import 'package:shopping_app/features/cart/views/cart_screen.dart';
import 'package:shopping_app/features/checkout/views/checkout_screen.dart';
import 'package:shopping_app/features/checkout/views/order_confirmation_screen.dart';
import 'package:shopping_app/features/demo_cart/views/demo_carts_screen.dart';
import 'package:shopping_app/features/orders/views/order_detail_screen.dart';
import 'package:shopping_app/features/orders/views/orders_screen.dart';
import 'package:shopping_app/features/product_detail/views/product_detail_screen.dart';
import 'package:shopping_app/features/products/views/products_screen.dart';
import 'package:shopping_app/features/profile/views/profile_screen.dart';
import 'package:shopping_app/features/shared/not_found_screen.dart';
import 'package:shopping_app/features/support/views/support_chat_screen.dart';
import 'package:shopping_app/features/wishlist/views/wishlist_screen.dart';

const List<GeneratedRoute> $shoppingRoutes = [
  GeneratedRoute(
    '/',
    page: ProductsScreen,
    name: 'products',
    resultType: 'void',
    guards: [],
    transition: FadeUpwardsPageTransitionsBuilder(),
  ),
  GeneratedRoute(
    '/404',
    page: NotFoundScreen,
    name: 'notFound',
    resultType: 'void',
    guards: [],
  ),
  GeneratedRoute(
    '/admin',
    page: AdminDashboardScreen,
    name: 'admin',
    resultType: 'void',
    guards: [AdminGuard],
  ),
  GeneratedRoute(
    '/cart',
    page: CartScreen,
    name: 'cart',
    resultType: 'void',
    guards: [],
    transition: BottomToTopPageTransitionsBuilder(),
  ),
  GeneratedRoute(
    '/checkout',
    page: CheckoutScreen,
    name: 'checkout',
    resultType: 'void',
    transition: BottomToTopPageTransitionsBuilder(),
    fullscreenDialog: true,
  ),
  GeneratedRoute(
    '/demo-carts',
    page: DemoCartsScreen,
    name: 'demoCarts',
    resultType: 'void',
    guards: [],
  ),
  GeneratedRoute(
    '/login',
    page: LoginScreen,
    name: 'login',
    resultType: 'void',
    guards: [],
  ),
  GeneratedRoute(
    '/order-confirmation',
    routes: [
      GeneratedRoute(
        ':orderId',
        page: OrderConfirmationScreen,
        name: 'orderConfirmation',
        resultType: 'void',
        guards: [],
        transition: ZoomPageTransitionsBuilder(),
      ),
    ],
  ),
  GeneratedRoute(
    '/orders',
    page: OrdersScreen,
    name: 'orders',
    resultType: 'void',
    routes: [
      GeneratedRoute(
        ':orderId',
        page: OrderDetailScreen,
        name: 'orderDetail',
        resultType: 'void',
      ),
    ],
  ),
  GeneratedRoute(
    '/product',
    routes: [
      GeneratedRoute(
        ':productId',
        page: ProductDetailScreen,
        name: 'productDetail',
        resultType: 'void',
        guards: [],
      ),
    ],
  ),
  GeneratedRoute(
    '/profile',
    page: ProfileScreen,
    name: 'profile',
    resultType: 'void',
  ),
  GeneratedRoute(
    '/register',
    page: RegisterScreen,
    name: 'register',
    resultType: 'void',
    guards: [],
  ),
  GeneratedRoute(
    '/staff',
    page: StaffDashboardScreen,
    name: 'staff',
    resultType: 'void',
    guards: [StaffGuard],
  ),
  GeneratedRoute(
    '/support',
    routes: [
      GeneratedRoute(
        'chat',
        page: SupportChatScreen,
        name: 'supportChat',
        resultType: 'bool',
        guards: [],
      ),
    ],
  ),
  GeneratedRoute(
    '/wishlist',
    page: WishlistScreen,
    name: 'wishlist',
    resultType: 'void',
    guards: [],
  ),
];

bool shoppingRouteRequiresAuth(ShoppingRoute route) => route.requiresAuth;

String? shoppingRouteBranch(ShoppingRoute route) {
  return switch (route) {
    _ => null,
  };
}

RouteDebugInfo shoppingRouteDebugInfo(ShoppingRoute route) {
  return switch (route) {
    ProductsRoute() => const RouteDebugInfo(name: 'products', shell: null, branch: null, resultType: 'void'),
    NotFoundRoute(path: _) => const RouteDebugInfo(name: 'notFound', shell: null, branch: null, resultType: 'void'),
    AdminRoute() => const RouteDebugInfo(name: 'admin', shell: null, branch: null, resultType: 'void'),
    CartRoute() => const RouteDebugInfo(name: 'cart', shell: null, branch: null, resultType: 'void'),
    CheckoutRoute() => const RouteDebugInfo(name: 'checkout', shell: null, branch: null, resultType: 'void'),
    DemoCartsRoute() => const RouteDebugInfo(name: 'demoCarts', shell: null, branch: null, resultType: 'void'),
    LoginRoute(redirectPath: _) => const RouteDebugInfo(name: 'login', shell: null, branch: null, resultType: 'void'),
    OrderConfirmationRoute(orderId: _) => const RouteDebugInfo(name: 'orderConfirmation', shell: null, branch: null, resultType: 'void'),
    OrdersRoute() => const RouteDebugInfo(name: 'orders', shell: null, branch: null, resultType: 'void'),
    OrderDetailRoute(orderId: _) => const RouteDebugInfo(name: 'orderDetail', shell: null, branch: null, resultType: 'void'),
    ProductDetailRoute(productId: _) => const RouteDebugInfo(name: 'productDetail', shell: null, branch: null, resultType: 'void'),
    ProfileRoute() => const RouteDebugInfo(name: 'profile', shell: null, branch: null, resultType: 'void'),
    RegisterRoute(redirectPath: _) => const RouteDebugInfo(name: 'register', shell: null, branch: null, resultType: 'void'),
    StaffRoute(access: _, from: _, returnTo: _, sections: _, orderIds: _) => const RouteDebugInfo(name: 'staff', shell: null, branch: null, resultType: 'void'),
    SupportChatRoute() => const RouteDebugInfo(name: 'supportChat', shell: null, branch: null, resultType: 'bool'),
    WishlistRoute() => const RouteDebugInfo(name: 'wishlist', shell: null, branch: null, resultType: 'void'),
  };
}

List<RouteGuardBase<ShoppingRoute>> shoppingRouteGuards(
  ShoppingRoute route,
  Object router,
) {
  return switch (route) {
    AdminRoute() => [AdminGuard((router as dynamic).auth)],
    StaffRoute() => [StaffGuard((router as dynamic).auth)],
    _ => const [],
  };
}
