// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by dust.
//
// ignore_for_file: unused_import, unnecessary_import

import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:dust_flutter/route.dart';

import 'paths.g.dart';
import '../route.dart';
import 'package:shopping_app/features/admin/views/admin_dashboard_screen.dart';
import 'package:shopping_app/features/admin/views/staff_dashboard_screen.dart';
import 'package:shopping_app/features/auth/views/login_screen.dart';
import 'package:shopping_app/features/auth/views/register_screen.dart';
import 'package:shopping_app/features/cart/views/cart_screen.dart';
import 'package:shopping_app/features/checkout/views/checkout_screen.dart';
import 'package:shopping_app/features/checkout/views/order_confirmation_screen.dart';
import 'package:shopping_app/features/demo_cart/views/demo_carts_screen.dart';
import 'package:shopping_app/features/orders/views/order_detail_screen.dart';
import 'package:shopping_app/features/orders/views/orders_screen.dart';
import 'package:shopping_app/features/product_detail/views/product_detail_screen.dart';
import 'package:shopping_app/features/products/views/products_screen.dart';
import 'package:shopping_app/features/profile/views/profile_screen.dart';
import 'package:shopping_app/features/shared/not_found_screen.dart';
import 'package:shopping_app/features/support/views/support_chat_screen.dart';
import 'package:shopping_app/features/wishlist/views/wishlist_screen.dart';

const List<GeneratedRoute> $shoppingRoutes = [
  GeneratedRoute(
    '/',
    page: ProductsScreen,
    name: 'products',
    guards: [],
    transition: FadeUpwardsPageTransitionsBuilder(),
  ),
  GeneratedRoute(
    '/404',
    page: NotFoundScreen,
    name: 'notFound',
    guards: [],
  ),
  GeneratedRoute(
    '/admin',
    page: AdminDashboardScreen,
    name: 'admin',
    guards: [AdminGuard],
  ),
  GeneratedRoute(
    '/cart',
    page: CartScreen,
    name: 'cart',
    guards: [],
    transition: BottomToTopPageTransitionsBuilder(),
  ),
  GeneratedRoute(
    '/checkout',
    page: CheckoutScreen,
    name: 'checkout',
    transition: BottomToTopPageTransitionsBuilder(),
    fullscreenDialog: true,
  ),
  GeneratedRoute(
    '/demo-carts',
    page: DemoCartsScreen,
    name: 'demoCarts',
    guards: [],
  ),
  GeneratedRoute(
    '/login',
    page: LoginScreen,
    name: 'login',
    guards: [],
  ),
  GeneratedRoute(
    '/order-confirmation',
    routes: [
      GeneratedRoute(
        ':orderId',
        page: OrderConfirmationScreen,
        name: 'orderConfirmation',
        guards: [],
        transition: ZoomPageTransitionsBuilder(),
      ),
    ],
  ),
  GeneratedRoute(
    '/orders',
    page: OrdersScreen,
    name: 'orders',
    routes: [
      GeneratedRoute(
        ':orderId',
        page: OrderDetailScreen,
        name: 'orderDetail',
      ),
    ],  ),
  GeneratedRoute(
    '/product',
    routes: [
      GeneratedRoute(
        ':productId',
        page: ProductDetailScreen,
        name: 'productDetail',
        guards: [],
      ),
    ],
  ),
  GeneratedRoute(
    '/profile',
    page: ProfileScreen,
    name: 'profile',
  ),
  GeneratedRoute(
    '/register',
    page: RegisterScreen,
    name: 'register',
    guards: [],
  ),
  GeneratedRoute(
    '/staff',
    page: StaffDashboardScreen,
    name: 'staff',
    guards: [StaffGuard],
  ),
  GeneratedRoute(
    '/support',
    routes: [
      GeneratedRoute(
        'chat',
        page: SupportChatScreen,
        name: 'supportChat',
        guards: [],
      ),
    ],
  ),
  GeneratedRoute(
    '/wishlist',
    page: WishlistScreen,
    name: 'wishlist',
    guards: [],
  ),
];

bool shoppingRouteRequiresAuth(ShoppingRoutePath route) => route.requiresAuth;

String? shoppingRouteBranch(ShoppingRoutePath route) {
  return switch (route) {
    _ => null,
  };
}

RouteDebugInfo shoppingRouteDebugInfo(ShoppingRoutePath route) {
  return switch (route) {
    ShoppingProductsRoute() => const RouteDebugInfo(name: 'products', shell: null, branch: null),
    ShoppingNotFoundRoute(path: _) => const RouteDebugInfo(name: 'notFound', shell: null, branch: null),
    ShoppingAdminRoute() => const RouteDebugInfo(name: 'admin', shell: null, branch: null),
    ShoppingCartRoute() => const RouteDebugInfo(name: 'cart', shell: null, branch: null),
    ShoppingCheckoutRoute() => const RouteDebugInfo(name: 'checkout', shell: null, branch: null),
    ShoppingDemoCartsRoute() => const RouteDebugInfo(name: 'demoCarts', shell: null, branch: null),
    ShoppingLoginRoute(redirectPath: _) => const RouteDebugInfo(name: 'login', shell: null, branch: null),
    ShoppingOrderConfirmationRoute(orderId: _) => const RouteDebugInfo(name: 'orderConfirmation', shell: null, branch: null),
    ShoppingOrdersRoute() => const RouteDebugInfo(name: 'orders', shell: null, branch: null),
    ShoppingOrderDetailRoute(orderId: _) => const RouteDebugInfo(name: 'orderDetail', shell: null, branch: null),
    ShoppingProductDetailRoute(productId: _) => const RouteDebugInfo(name: 'productDetail', shell: null, branch: null),
    ShoppingProfileRoute() => const RouteDebugInfo(name: 'profile', shell: null, branch: null),
    ShoppingRegisterRoute(redirectPath: _) => const RouteDebugInfo(name: 'register', shell: null, branch: null),
    ShoppingStaffRoute() => const RouteDebugInfo(name: 'staff', shell: null, branch: null),
    ShoppingSupportChatRoute() => const RouteDebugInfo(name: 'supportChat', shell: null, branch: null),
    ShoppingWishlistRoute() => const RouteDebugInfo(name: 'wishlist', shell: null, branch: null),
  };
}

List<Object> shoppingRouteGuards(
  ShoppingRoutePath route,
  Object router,
) {
  return switch (route) {
    ShoppingAdminRoute() => [AdminGuard((router as dynamic).auth)],
    ShoppingStaffRoute() => [StaffGuard((router as dynamic).auth)],
    _ => const [],
  };
}
