// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'database.dart';

final class _$AppDatabase implements AppDatabase {
  _$AppDatabase._(this.connection);

  factory _$AppDatabase.open(
    String path, {
    SqliteConnectOptions? options,
  }) {
    final connection = Sqlite3Driver.open(
      path,
      migrations: _$appDatabaseMigrations,
      options: options,
    );
    return _$AppDatabase._(connection);
  }

  final DatabaseConnection connection;

  Pool get pool => connection as Pool;
}

const Map<String, String> _$appDatabaseMigrations = <String, String>{
  '0001_create_accounts.sql': '-- Accounts and the tokens that authenticate them.\n--\n-- A password is never stored, only a PBKDF2 hash and the salt it used. A token\n-- is never stored either: only its SHA-256, so a stolen database read does not\n-- hand over working credentials.\nCREATE TABLE accounts (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  email TEXT NOT NULL UNIQUE,\n  password_hash TEXT NOT NULL,\n  password_salt TEXT NOT NULL,\n  scopes TEXT NOT NULL DEFAULT \'\'\n);\n\nCREATE TABLE api_tokens (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  account_id INTEGER NOT NULL REFERENCES accounts (id),\n  -- The hash, never the token. Unique so a lookup is one index hit.\n  token_hash TEXT NOT NULL UNIQUE,\n  expires_at TEXT NOT NULL\n);\n\nCREATE INDEX api_tokens_account ON api_tokens (account_id);\n',
  '0002_create_orders.sql': '-- Orders, owned by the account that placed them.\nCREATE TABLE orders (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  account_id INTEGER NOT NULL REFERENCES accounts (id),\n  item TEXT NOT NULL,\n  quantity INTEGER NOT NULL CHECK (quantity > 0),\n  placed_at TEXT NOT NULL\n);\n\nCREATE INDEX orders_account ON orders (account_id);\n',
};
