// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'chat_message.dart';

const DeepCollectionEquality _chatRequestHistoryEquality = DeepCollectionEquality();

mixin _$ChatMessage {
  @override
  String toString() {
    final self = this as ChatMessage;
    return 'ChatMessage('
        'id: ${self.id}, '
        'role: ${self.role}, '
        'text: ${self.text}, '
        'createdAt: ${self.createdAt}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ChatMessage;
    return identical(this, other) ||
        other is ChatMessage &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.role == self.role &&
            other.text == self.text &&
            other.createdAt == self.createdAt;
  }

  @override
  int get hashCode {
    final self = this as ChatMessage;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.role,
      self.text,
      self.createdAt,
    ]);
  }

  ChatMessage copyWith({
    String? id,
    ChatRole? role,
    String? text,
    DateTime? createdAt,
  }) {
    final self = this as ChatMessage;
    return ChatMessage(
      id: id ?? self.id,
      role: role ?? self.role,
      text: text ?? self.text,
      createdAt: createdAt ?? self.createdAt,
    );
  }

  Map<String, Object?> toJson() => _$ChatMessageToJson(this as ChatMessage);
}

mixin _$ChatRequest {
  @override
  String toString() {
    final self = this as ChatRequest;
    return 'ChatRequest('
        'message: ${self.message}, '
        'history: ${self.history}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ChatRequest;
    return identical(this, other) ||
        other is ChatRequest &&
            runtimeType == other.runtimeType &&
            other.message == self.message &&
            _chatRequestHistoryEquality.equals(other.history, self.history);
  }

  @override
  int get hashCode {
    final self = this as ChatRequest;
    return Object.hashAll([
      runtimeType,
      self.message,
      _chatRequestHistoryEquality.hash(self.history),
    ]);
  }

  ChatRequest copyWith({
    String? message,
    List<ChatMessage>? history,
  }) {
    final self = this as ChatRequest;
    final nextHistory = List<ChatMessage>.of(
      (history ?? self.history).map((item_1) => item_1.copyWith()),
    );

    return ChatRequest(
      message: message ?? self.message,
      history: nextHistory,
    );
  }

  Map<String, Object?> toJson() => _$ChatRequestToJson(this as ChatRequest);
}

mixin _$ChatResponse {
  @override
  String toString() {
    final self = this as ChatResponse;
    return 'ChatResponse('
        'message: ${self.message}, '
        'escalated: ${self.escalated}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ChatResponse;
    return identical(this, other) ||
        other is ChatResponse &&
            runtimeType == other.runtimeType &&
            other.message == self.message &&
            other.escalated == self.escalated;
  }

  @override
  int get hashCode {
    final self = this as ChatResponse;
    return Object.hashAll([
      runtimeType,
      self.message,
      self.escalated,
    ]);
  }

  ChatResponse copyWith({
    ChatMessage? message,
    bool? escalated,
  }) {
    final self = this as ChatResponse;
    final nextMessage = (message ?? self.message).copyWith();

    return ChatResponse(
      message: nextMessage,
      escalated: escalated ?? self.escalated,
    );
  }

  Map<String, Object?> toJson() => _$ChatResponseToJson(this as ChatResponse);
}

Map<String, Object?> _$ChatMessageToJson(ChatMessage instance) {
  return <String, Object?>{
    'id': instance.id,
    'role': _$ChatRoleToJson(instance.role),
    'text': instance.text,
    'createdAt': instance.createdAt.toIso8601String(),
  };
}
// factory ChatMessage.fromJson(Map<String, Object?> json) => _$ChatMessageFromJson(json);
ChatMessage _$ChatMessageFromJson(Map<String, Object?> json) {
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final roleValue = _$ChatRoleFromJson(json['role']);
  final textValue = JsonHelper.as<String>(json['text'], 'text', 'String');
  final createdAtValue = JsonHelper.asDateTime(json['createdAt'], 'createdAt');

  return ChatMessage(
    id: idValue,
    role: roleValue,
    text: textValue,
    createdAt: createdAtValue,
  );
}
Map<String, Object?> _$ChatRequestToJson(ChatRequest instance) {
  return <String, Object?>{
    'message': instance.message,
    'history': instance.history
        .map((item) => _$ChatMessageToJson(item))
        .toList(),
  };
}
// factory ChatRequest.fromJson(Map<String, Object?> json) => _$ChatRequestFromJson(json);
ChatRequest _$ChatRequestFromJson(Map<String, Object?> json) {
  final messageValue = JsonHelper.as<String>(
    json['message'],
    'message',
    'String',
  );
  final historyValue = JsonHelper.asList(json['history'], 'history')
      .map((item) => _$ChatMessageFromJson(JsonHelper.asMap(item, 'history')))
      .toList();

  return ChatRequest(message: messageValue, history: historyValue);
}
Map<String, Object?> _$ChatResponseToJson(ChatResponse instance) {
  return <String, Object?>{
    'message': _$ChatMessageToJson(instance.message),
    'escalated': instance.escalated,
  };
}
// factory ChatResponse.fromJson(Map<String, Object?> json) => _$ChatResponseFromJson(json);
ChatResponse _$ChatResponseFromJson(Map<String, Object?> json) {
  final messageValue = _$ChatMessageFromJson(JsonHelper.asMap(json['message'], 'message'));
  final escalatedValue = JsonHelper.as<bool>(
    json['escalated'],
    'escalated',
    'bool',
  );

  return ChatResponse(message: messageValue, escalated: escalatedValue);
}
Object? _$ChatRoleToJson(ChatRole instance) {
  return switch (instance) {
    ChatRole.user => 'user',
    ChatRole.assistant => 'assistant',
  };
}
ChatRole _$ChatRoleFromJson(Object? json) {
  return switch (json) {
    'user' => ChatRole.user,
    'assistant' => ChatRole.assistant,
    _ => throw ArgumentError.value(json, 'json', 'unknown value for ChatRole'),
  };
}
