// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'chat_message.dart';

const DeepCollectionEquality _deepCollectionEquality = DeepCollectionEquality();
Never _jsonTypeError(Object? value, String key, String expected) =>
    throw ArgumentError.value(value, key, 'expected $expected');
T _jsonAs<T>(Object? value, String key, String expected) =>
    value is T ? value : _jsonTypeError(value, key, expected);
T _jsonParseString<T>(
  Object? value,
  String key,
  String expected,
  T? Function(String value) parse,
) =>
    parse(_jsonAs<String>(value, key, 'String')) ??
    _jsonTypeError(value, key, expected);
List<Object?> _jsonAsList(Object? value, String key) =>
    _jsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _jsonAsMap(Object? value, String key) {
  final map = _jsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _jsonTypeError(value, key, 'Map<String, Object?>');
  }
}

DateTime _jsonAsDateTime(Object? value, String key) =>
    _jsonParseString(value, key, 'ISO-8601 DateTime string', DateTime.tryParse);
Uri _jsonAsUri(Object? value, String key) =>
    _jsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _jsonAsBigInt(Object? value, String key) =>
    _jsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _jsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

mixin _$ChatMessage {
  @override
  String toString() {
    final self = this as ChatMessage;
    return 'ChatMessage('
        'id: ${self.id}, '
        'role: ${self.role}, '
        'text: ${self.text}, '
        'createdAt: ${self.createdAt}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ChatMessage;
    return identical(this, other) ||
        other is ChatMessage &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.role == self.role &&
            other.text == self.text &&
            other.createdAt == self.createdAt;
  }

  @override
  int get hashCode {
    final self = this as ChatMessage;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.role,
      self.text,
      self.createdAt,
    ]);
  }

  ChatMessage copyWith({
    String? id,
    ChatRole? role,
    String? text,
    DateTime? createdAt,
  }) {
    final self = this as ChatMessage;
    return ChatMessage(
      id: id ?? self.id,
      role: role ?? self.role,
      text: text ?? self.text,
      createdAt: createdAt ?? self.createdAt,
    );
  }

  Map<String, Object?> toJson() => _$ChatMessageToJson(this as ChatMessage);
}

mixin _$ChatRequest {
  @override
  String toString() {
    final self = this as ChatRequest;
    return 'ChatRequest('
        'message: ${self.message}, '
        'history: ${self.history}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ChatRequest;
    return identical(this, other) ||
        other is ChatRequest &&
            runtimeType == other.runtimeType &&
            other.message == self.message &&
            _deepCollectionEquality.equals(other.history, self.history);
  }

  @override
  int get hashCode {
    final self = this as ChatRequest;
    return Object.hashAll([
      runtimeType,
      self.message,
      _deepCollectionEquality.hash(self.history),
    ]);
  }

  ChatRequest copyWith({
    String? message,
    List<ChatMessage>? history,
  }) {
    final self = this as ChatRequest;
    final nextHistory = List<ChatMessage>.of(
      (history ?? self.history).map((item_1) => item_1.copyWith()),
    );

    return ChatRequest(
      message: message ?? self.message,
      history: nextHistory,
    );
  }

  Map<String, Object?> toJson() => _$ChatRequestToJson(this as ChatRequest);
}

mixin _$ChatResponse {
  @override
  String toString() {
    final self = this as ChatResponse;
    return 'ChatResponse('
        'message: ${self.message}, '
        'escalated: ${self.escalated}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ChatResponse;
    return identical(this, other) ||
        other is ChatResponse &&
            runtimeType == other.runtimeType &&
            other.message == self.message &&
            other.escalated == self.escalated;
  }

  @override
  int get hashCode {
    final self = this as ChatResponse;
    return Object.hashAll([
      runtimeType,
      self.message,
      self.escalated,
    ]);
  }

  ChatResponse copyWith({
    ChatMessage? message,
    bool? escalated,
  }) {
    final self = this as ChatResponse;
    final nextMessage = (message ?? self.message).copyWith();

    return ChatResponse(
      message: nextMessage,
      escalated: escalated ?? self.escalated,
    );
  }

  Map<String, Object?> toJson() => _$ChatResponseToJson(this as ChatResponse);
}

Map<String, Object?> _$ChatMessageToJson(ChatMessage instance) {
  return <String, Object?>{
    'id': instance.id,
    'role': _$ChatRoleToJson(instance.role),
    'text': instance.text,
    'createdAt': instance.createdAt.toIso8601String(),
  };
}
// factory ChatMessage.fromJson(Map<String, Object?> json) => _$ChatMessageFromJson(json);
ChatMessage _$ChatMessageFromJson(Map<String, Object?> json) {
  final idValue = _jsonAs<String>(json['id'], 'id', 'String');
  final roleValue = _$ChatRoleFromJson(json['role']);
  final textValue = _jsonAs<String>(json['text'], 'text', 'String');
  final createdAtValue = _jsonAsDateTime(json['createdAt'], 'createdAt');

  return ChatMessage(
    id: idValue,
    role: roleValue,
    text: textValue,
    createdAt: createdAtValue,
  );
}
Map<String, Object?> _$ChatRequestToJson(ChatRequest instance) {
  return <String, Object?>{
    'message': instance.message,
    'history': instance.history
        .map((item) => _$ChatMessageToJson(item))
        .toList(),
  };
}
// factory ChatRequest.fromJson(Map<String, Object?> json) => _$ChatRequestFromJson(json);
ChatRequest _$ChatRequestFromJson(Map<String, Object?> json) {
  final messageValue = _jsonAs<String>(json['message'], 'message', 'String');
  final historyValue = _jsonAsList(json['history'], 'history')
      .map((item) => _$ChatMessageFromJson(_jsonAsMap(item, 'history')))
      .toList();

  return ChatRequest(message: messageValue, history: historyValue);
}
Map<String, Object?> _$ChatResponseToJson(ChatResponse instance) {
  return <String, Object?>{
    'message': _$ChatMessageToJson(instance.message),
    'escalated': instance.escalated,
  };
}
// factory ChatResponse.fromJson(Map<String, Object?> json) => _$ChatResponseFromJson(json);
ChatResponse _$ChatResponseFromJson(Map<String, Object?> json) {
  final messageValue = _$ChatMessageFromJson(_jsonAsMap(json['message'], 'message'));
  final escalatedValue = _jsonAs<bool>(json['escalated'], 'escalated', 'bool');

  return ChatResponse(message: messageValue, escalated: escalatedValue);
}
Object? _$ChatRoleToJson(ChatRole instance) {
  return switch (instance) {
    ChatRole.user => 'user',
    ChatRole.assistant => 'assistant',
  };
}
ChatRole _$ChatRoleFromJson(Object? json) {
  return switch (json) {
    'user' => ChatRole.user,
    'assistant' => ChatRole.assistant,
    _ => throw ArgumentError.value(json, 'json', 'unknown value for ChatRole'),
  };
}
