name: dust_flutter
description: Annotations and runtime support for generating Flutter code with dust.
version: 0.1.0
repository: https://github.com/y3l1n4ung/dust
issue_tracker: https://github.com/y3l1n4ung/dust/issues
topics:
  - codegen
  - annotations
  - routing
  - state-management
  - flutter

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.0
  very_good_analysis: ^10.3.0
