// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'demo_cart_api_view_model.dart';

enum _DemoCartApiViewModelAspect { status, carts, errorMessage }

abstract class $DemoCartApiViewModel extends ViewModelBase<DemoCartState, DemoCartApiViewModelArgs> {
  $DemoCartApiViewModel(super.args) : super(initialState: const DemoCartState());

  DemoCartStatus get status => state.status;
  List<Object?> get carts => state.carts;
  String? get errorMessage => state.errorMessage;
  ShoppingRepository get repository => args.repository;
}

class _$DemoCartApiViewModelProxy {
  _$DemoCartApiViewModelProxy(this._context);

  final BuildContext _context;

  DemoCartState get value {
    return DemoCartApiViewModelScope.of(_context).value;
  }

  DemoCartStatus get status {
    return DemoCartApiViewModelScope.of(_context, aspect: _DemoCartApiViewModelAspect.status).state.status;
  }

  List<Object?> get carts {
    return DemoCartApiViewModelScope.of(_context, aspect: _DemoCartApiViewModelAspect.carts).state.carts;
  }

  String? get errorMessage {
    return DemoCartApiViewModelScope.of(_context, aspect: _DemoCartApiViewModelAspect.errorMessage).state.errorMessage;
  }
}

class DemoCartApiViewModelScope extends StatefulWidget {
  const DemoCartApiViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
  }) : value = null;

  const DemoCartApiViewModelScope.value({
    super.key,
    required DemoCartApiViewModel this.value,
    required this.child,
  }) : args = null,
       create = null;

  final DemoCartApiViewModelArgs Function(BuildContext context)? args;
  final DemoCartApiViewModel Function(BuildContext context, DemoCartApiViewModelArgs args)? create;
  final DemoCartApiViewModel? value;
  final Widget child;

  static DemoCartApiViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_DemoCartApiViewModelInherited>()
        ?.widget as _DemoCartApiViewModelInherited?;
    if (scope == null) throw StateError('No DemoCartApiViewModelScope found in context.');
    return scope.viewModel;
  }

  static DemoCartApiViewModel of(BuildContext context, {_DemoCartApiViewModelAspect? aspect}) {
    final scope = context.dependOnInheritedWidgetOfExactType<_DemoCartApiViewModelInherited>(
      aspect: aspect,
    );
    if (scope == null) throw StateError('No DemoCartApiViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<DemoCartApiViewModelScope> createState() => _DemoCartApiViewModelScopeState();
}

class _DemoCartApiViewModelScopeState extends State<DemoCartApiViewModelScope> {
  DemoCartApiViewModel? _viewModel;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (_viewModel == null) {
      _replaceViewModel(_resolveViewModel(), ownsViewModel: widget.value == null, notify: false);
    }
  }

  @override
  void didUpdateWidget(DemoCartApiViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    }
  }

  DemoCartApiViewModel _resolveViewModel() {
    return widget.value ?? _createOwnedViewModel();
  }

  DemoCartApiViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned DemoCartApiViewModelScope requires args and create.');
    }
    late final DemoCartApiViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(
        StateError(
          'DemoCartApiViewModelScope failed to create its view model. Check the generated '
          'scope args/create dependency injection. Original error: $error',
        ),
        stackTrace,
      );
    }
    return created;
  }

  void _replaceViewModel(
    DemoCartApiViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    if (ownsViewModel) {
      scheduleMicrotask(() {
        if (mounted && identical(_viewModel, nextViewModel)) {
          nextViewModel.init();
        }
      });
    }
    if (notify && mounted) setState(() {});
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('DemoCartApiViewModelScope built before its view model was initialized.');
    }
    return _DemoCartApiViewModelInherited(
      viewModel: viewModel,
      state: viewModel.value,
      child: widget.child,
    );
  }
}

class _DemoCartApiViewModelInherited extends InheritedModel<_DemoCartApiViewModelAspect> {
  const _DemoCartApiViewModelInherited({required this.viewModel, required this.state, required super.child});

  final DemoCartApiViewModel viewModel;
  final DemoCartState state;

  /// Requires DemoCartState to implement == and hashCode. Without value equality,
  /// every emitted state is treated as changed and granular rebuilds degrade to
  /// full dependent subtree rebuilds.
  @override
  bool updateShouldNotify(_DemoCartApiViewModelInherited oldWidget) => state != oldWidget.state;

  @override
  bool updateShouldNotifyDependent(_DemoCartApiViewModelInherited oldWidget, Set<_DemoCartApiViewModelAspect> dependencies) {
    for (final aspect in dependencies) {
      switch (aspect) {
        case _DemoCartApiViewModelAspect.status:
          if (state.status != oldWidget.state.status) {
            return true;
          }
        case _DemoCartApiViewModelAspect.carts:
          if (state.carts != oldWidget.state.carts) {
            return true;
          }
        case _DemoCartApiViewModelAspect.errorMessage:
          if (state.errorMessage != oldWidget.state.errorMessage) {
            return true;
          }
      }
    }
    return false;
  }
}

/// Listens to one-shot effects from DemoCartApiViewModel.
///
/// TODO: effects are Stream<Object> until ViewModelBase supports typed effect
/// payloads through the @ViewModel annotation.
class DemoCartApiViewModelListener extends StatefulWidget {
  const DemoCartApiViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<DemoCartApiViewModelListener> createState() => _DemoCartApiViewModelListenerState();
}

class _DemoCartApiViewModelListenerState extends State<DemoCartApiViewModelListener> {
  StreamSubscription<Object>? _sub;
  DemoCartApiViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = DemoCartApiViewModelScope.read(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

extension DemoCartApiViewModelBuildContext on BuildContext {
  _$DemoCartApiViewModelProxy watchDemoCartApiViewModel() {
    return _$DemoCartApiViewModelProxy(this);
  }

  DemoCartApiViewModel readDemoCartApiViewModel() => DemoCartApiViewModelScope.read(this);
}
