use std::collections::BTreeSet;
use std::path::Path;

use dust_ir::DartFileIr;

use crate::plugin::model::{RouteImport, RouterSpec};

use super::formatting::package_import_uri;

/// Renders imports required by generated route metadata and runtime files.
pub(super) fn render_route_imports(library: &DartFileIr, spec: &RouterSpec) -> String {
    let current_import = package_import_uri(library);
    let mut imports = BTreeSet::new();
    imports.insert(format!(
        "import '{}';\n",
        source_import_from_generated_dir(library)
    ));
    for route in &spec.routes {
        if let Some(import) = &route.import_uri
            && Some(import.as_str()) != current_import.as_deref()
            && !is_internal_route_import(import)
        {
            imports.insert(format!("import '{import}';\n"));
        }
        for import in &route.imports {
            if Some(import.uri.as_str()) == current_import.as_deref()
                || is_internal_route_import(&import.uri)
            {
                continue;
            }
            imports.insert(render_import(import));
        }
    }
    let imports = imports.into_iter().collect::<String>();
    if imports.is_empty() {
        imports
    } else {
        format!("{imports}\n")
    }
}

/// Returns whether an import is generated by the route plugin itself.
fn is_internal_route_import(import: &str) -> bool {
    matches!(
        import,
        "route.g.dart"
            | "routing_core.dart"
            | "route/routes.g.dart"
            | "route/runtime.g.dart"
            | "route/paths.g.dart"
            | "route/metadata.g.dart"
            | "route/navigation.g.dart"
    )
}

/// Returns the router source import URI from generated files under `route/`.
fn source_import_from_generated_dir(library: &DartFileIr) -> String {
    let source_path = Path::new(&library.source_path);
    let source_name = source_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("route.dart");
    format!("../{source_name}")
}

/// Renders a Dart import while preserving prefix, deferred, show, and hide clauses.
fn render_import(import: &RouteImport) -> String {
    let mut rendered = format!("import '{}'", import.uri);
    if let Some(prefix) = &import.prefix {
        if import.is_deferred {
            rendered.push_str(" deferred");
        }
        rendered.push_str(&format!(" as {prefix}"));
    }
    if !import.show.is_empty() {
        rendered.push_str(&format!(" show {}", import.show.join(", ")));
    }
    if !import.hide.is_empty() {
        rendered.push_str(&format!(" hide {}", import.hide.join(", ")));
    }
    rendered.push_str(";\n");
    rendered
}
