use std::collections::BTreeSet;
use std::path::Path;

use dust_ir::DartFileIr;

use crate::plugin::model::{RouteImport, RouteSpec, RouterSpec};

use super::formatting::package_import_uri;
use super::import_references::{RouteImportReferences, route_import_references};

/// Selects which generated route file dependencies should be imported.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum RouteImportKind {
    /// Imports used by route metadata.
    Metadata,
    /// Imports used by page-building runtime code.
    Runtime,
    /// Imports used by typed route data and navigation helper signatures.
    RouteTypes,
}

/// Renders imports required by one generated route file family.
pub(super) fn render_route_imports(
    library: &DartFileIr,
    spec: &RouterSpec,
    kind: RouteImportKind,
) -> String {
    let current_import = package_import_uri(library);
    let mut imports = BTreeSet::new();
    if matches!(kind, RouteImportKind::Metadata | RouteImportKind::Runtime) {
        imports.insert(format!(
            "import '{}';\n",
            source_import_from_generated_dir(library)
        ));
    }
    for route in &spec.routes {
        if matches!(kind, RouteImportKind::Metadata | RouteImportKind::Runtime)
            && let Some(import) = &route.import_uri
            && Some(import.as_str()) != current_import.as_deref()
            && !is_internal_route_import(import)
        {
            imports.insert(format!("import '{import}';\n"));
        }
        let references = route_import_references(route, kind);
        if matches!(kind, RouteImportKind::RouteTypes)
            && route_type_needs_source_import(current_import.as_deref(), route, &references)
        {
            imports.insert(format!(
                "import '{}';\n",
                source_import_from_generated_dir(library)
            ));
        }
        for import in &route.imports {
            if Some(import.uri.as_str()) == current_import.as_deref()
                || is_internal_route_import(&import.uri)
                || !route_import_is_referenced(import, &references)
            {
                continue;
            }
            imports.insert(render_import(import));
        }
    }
    let imports = imports.into_iter().collect::<String>();
    if imports.is_empty() {
        imports
    } else {
        format!("{imports}\n")
    }
}

/// Returns true when generated route types need the user route entrypoint.
fn route_type_needs_source_import(
    current_import: Option<&str>,
    route: &RouteSpec,
    references: &RouteImportReferences,
) -> bool {
    if references.is_empty() {
        return false;
    }
    route.import_uri.is_none()
        || route.imports.iter().any(|import| {
            Some(import.uri.as_str()) == current_import
                && route_current_import_is_referenced(import, references)
        })
}

/// Returns true when a route page import of the user entrypoint exposes references.
fn route_current_import_is_referenced(
    import: &RouteImport,
    references: &RouteImportReferences,
) -> bool {
    if let Some(prefix) = &import.prefix {
        return references.prefixes.contains(prefix);
    }
    if !import.show.is_empty() {
        return import
            .show
            .iter()
            .any(|name| references.names.contains(name) && !import.hide.contains(name));
    }
    references
        .names
        .iter()
        .any(|name| !import.hide.contains(name))
}

/// Returns true when a page-library import exposes a generated-code reference.
fn route_import_is_referenced(import: &RouteImport, references: &RouteImportReferences) -> bool {
    if let Some(prefix) = &import.prefix {
        return references.prefixes.contains(prefix);
    }
    if references.names.is_empty() {
        return false;
    }
    if !import.show.is_empty() {
        return import
            .show
            .iter()
            .any(|name| references.names.contains(name) && !import.hide.contains(name));
    }
    import_uri_type_name(&import.uri)
        .is_some_and(|name| references.names.contains(&name) && !import.hide.contains(&name))
}

/// Returns whether an import is generated by the route plugin itself.
fn is_internal_route_import(import: &str) -> bool {
    matches!(
        import,
        "route.g.dart"
            | "routing_core.dart"
            | "route/routes.g.dart"
            | "route/runtime.g.dart"
            | "route/paths.g.dart"
            | "route/metadata.g.dart"
            | "route/navigation.g.dart"
    )
}

/// Returns the router source import URI from generated files under `route/`.
fn source_import_from_generated_dir(library: &DartFileIr) -> String {
    let source_path = Path::new(&library.source_path);
    let source_name = source_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("route.dart");
    format!("../{source_name}")
}

/// Infers a conventional public type name from a Dart import file name.
fn import_uri_type_name(uri: &str) -> Option<String> {
    let stem = uri.rsplit('/').next()?.strip_suffix(".dart")?;
    Some(upper_camel(stem))
}

/// Converts snake, kebab, and spaced file stems to UpperCamelCase.
fn upper_camel(value: &str) -> String {
    value
        .split(|ch: char| ch == '_' || ch == '-' || ch.is_whitespace())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => {
                    first.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase()
                }
                None => String::new(),
            }
        })
        .collect()
}

/// Renders a Dart import while preserving prefix, deferred, show, and hide clauses.
fn render_import(import: &RouteImport) -> String {
    let mut rendered = format!("import '{}'", import.uri);
    if let Some(prefix) = &import.prefix {
        if import.is_deferred {
            rendered.push_str(" deferred");
        }
        rendered.push_str(&format!(" as {prefix}"));
    }
    if !import.show.is_empty() {
        rendered.push_str(&format!(" show {}", import.show.join(", ")));
    }
    if !import.hide.is_empty() {
        rendered.push_str(&format!(" hide {}", import.hide.join(", ")));
    }
    rendered.push_str(";\n");
    rendered
}
