// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'auth_view_model.dart';

/// Base class generated for AuthViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class AuthViewModel extends $AuthViewModel {
///   AuthViewModel(super.args);
/// }
/// ```
abstract class $AuthViewModel extends ViewModelBase<AuthState, AuthViewModelArgs> {
  $AuthViewModel(super.args) : super(initialState: AuthState(status: AuthStatus.unauthenticated));
}

/// Reads AuthViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchAuthViewModel().value;
/// ```
class _$AuthViewModelProxy {
  _$AuthViewModelProxy(this._context);

  final BuildContext _context;

  AuthState get value {
    return AuthViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected AuthState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class AuthViewModelSelector<R> extends StatefulWidget {
  const AuthViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(AuthState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<AuthViewModelSelector<R>> createState() => _AuthViewModelSelectorState<R>();
}

class _AuthViewModelSelectorState<R> extends State<AuthViewModelSelector<R>> {
  AuthViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AuthViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(AuthViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides AuthViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// AuthViewModelScope(
///   args: (context) => AuthViewModelArgs(...),
///   create: (context, args) => AuthViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class AuthViewModelScope extends StatefulWidget {
  /// Creates and owns AuthViewModel from typed args.
  const AuthViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned AuthViewModel without disposing it.
  const AuthViewModelScope.value({
    super.key,
    required AuthViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final AuthViewModelArgs Function(BuildContext context)? args;
  final AuthViewModel Function(BuildContext context, AuthViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final AuthViewModel? value;
  final Widget child;

  /// Reads AuthViewModel without rebuilding when state changes.
  static AuthViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_AuthViewModelInstance>()
        ?.widget as _AuthViewModelInstance?;
    if (scope == null) throw StateError('No AuthViewModelScope found in context.');
    return scope.viewModel;
  }

  static AuthViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AuthViewModelInstance>();
    if (scope == null) throw StateError('No AuthViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches AuthViewModel and rebuilds when state changes.
  static AuthViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AuthViewModelInherited>();
    if (scope == null) throw StateError('No AuthViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<AuthViewModelScope> createState() => _AuthViewModelScopeState();
}

class _AuthViewModelScopeState extends State<AuthViewModelScope> {
  AuthViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(AuthViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  AuthViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned AuthViewModelScope requires args and create.');
    }
    late final AuthViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(
        StateError(
          'AuthViewModelScope failed to create its view model. Check the generated '
          'scope args/create dependency injection. Original error: $error',
        ),
        stackTrace,
      );
    }
    return created;
  }

  void _replaceViewModel(
    AuthViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(AuthViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('AuthViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('AuthViewModelScope built before its view model was initialized.');
    }
    return _AuthViewModelInstance(
      viewModel: viewModel,
      child: _AuthViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _AuthViewModelInstance extends InheritedWidget {
  const _AuthViewModelInstance({required this.viewModel, required super.child});

  final AuthViewModel viewModel;

  @override
  bool updateShouldNotify(_AuthViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _AuthViewModelInherited extends InheritedWidget {
  const _AuthViewModelInherited({required this.viewModel, required this.state, required super.child});

  final AuthViewModel viewModel;
  final AuthState state;

  @override
  bool updateShouldNotify(_AuthViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from AuthViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// AuthViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class AuthViewModelListener extends StatefulWidget {
  const AuthViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<AuthViewModelListener> createState() => _AuthViewModelListenerState();
}

class _AuthViewModelListenerState extends State<AuthViewModelListener> {
  StreamSubscription<Object>? _sub;
  AuthViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AuthViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for AuthViewModel.
///
/// ```dart
/// final vm = context.readAuthViewModel();
/// final state = context.watchAuthViewModel().value;
/// ```
extension AuthViewModelBuildContext on BuildContext {
  _$AuthViewModelProxy watchAuthViewModel() {
    return _$AuthViewModelProxy(this);
  }

  AuthViewModel readAuthViewModel() => AuthViewModelScope.read(this);
}
