// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'checkout_view_model.dart';

abstract class $CheckoutViewModel extends ViewModelBase<CheckoutState, CheckoutViewModelArgs> {
  $CheckoutViewModel(super.args) : super(initialState: const CheckoutState());
  ShoppingRepository get repository => args.repository;
}

class _$CheckoutViewModelProxy {
  _$CheckoutViewModelProxy(this._context, this._vm);

  final BuildContext _context;
  final CheckoutViewModel _vm;

  CheckoutState get value {
    CheckoutViewModelScope.of(_context);
    return _vm.value;
  }
}

class CheckoutViewModelScope extends StatefulWidget {
  const CheckoutViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
  }) : value = null;

  const CheckoutViewModelScope.value({
    super.key,
    required CheckoutViewModel this.value,
    required this.child,
  }) : args = null,
       create = null;

  final CheckoutViewModelArgs Function(BuildContext context)? args;
  final CheckoutViewModel Function(BuildContext context, CheckoutViewModelArgs args)? create;
  final CheckoutViewModel? value;
  final Widget child;

  static CheckoutViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_CheckoutViewModelInherited>()
        ?.widget as _CheckoutViewModelInherited?;
    if (scope == null) throw StateError('No CheckoutViewModelScope found in context.');
    return scope.viewModel;
  }

  static CheckoutViewModel of(BuildContext context, {Object? aspect}) {
    final scope = context.dependOnInheritedWidgetOfExactType<_CheckoutViewModelInherited>(
      aspect: aspect,
    );
    if (scope == null) throw StateError('No CheckoutViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<CheckoutViewModelScope> createState() => _CheckoutViewModelScopeState();
}

class _CheckoutViewModelScopeState extends State<CheckoutViewModelScope> {
  @override
  Widget build(BuildContext context) {
    final external = widget.value;
    return external == null
        ? ViewModelOwner<CheckoutViewModel, CheckoutViewModelArgs>(
            debugName: 'CheckoutViewModelScope',
            args: widget.args!,
            create: widget.create!,
            builder: _buildInherited,
          )
        : ViewModelOwner<CheckoutViewModel, CheckoutViewModelArgs>.value(
            debugName: 'CheckoutViewModelScope.value',
            value: external,
            builder: _buildInherited,
          );
  }

  Widget _buildInherited(BuildContext context, CheckoutViewModel viewModel) {
    return ListenableBuilder(
      listenable: viewModel,
      builder: (context, child) => _CheckoutViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: child!,
      ),
      child: widget.child,
    );
  }
}

class _CheckoutViewModelInherited extends InheritedModel<Object> {
  const _CheckoutViewModelInherited({required this.viewModel, required this.state, required super.child});

  final CheckoutViewModel viewModel;
  final CheckoutState state;

  @override
  bool updateShouldNotify(_CheckoutViewModelInherited oldWidget) => state != oldWidget.state;

  @override
  bool updateShouldNotifyDependent(_CheckoutViewModelInherited oldWidget, Set<Object> dependencies) {
    return false;
  }
}

class CheckoutViewModelListener extends StatefulWidget {
  const CheckoutViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<CheckoutViewModelListener> createState() => _CheckoutViewModelListenerState();
}

class _CheckoutViewModelListenerState extends State<CheckoutViewModelListener> {
  StreamSubscription<Object>? _sub;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _sub?.cancel();
    _sub = CheckoutViewModelScope.read(context).effects.listen((effect) {
      if (mounted) widget.listener(context, effect);
    });
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

extension CheckoutViewModelBuildContext on BuildContext {
  CheckoutViewModel get checkoutViewModel => CheckoutViewModelScope.of(this);

  _$CheckoutViewModelProxy watchCheckoutViewModel() {
    return _$CheckoutViewModelProxy(this, CheckoutViewModelScope.read(this));
  }

  CheckoutViewModel readCheckoutViewModel() => CheckoutViewModelScope.read(this);
}
