// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'checkout_view_model.dart';

final class _CheckoutViewModelAspect<R> {
  const _CheckoutViewModelAspect(this.selector);

  final R Function(CheckoutState state) selector;

  bool hasChanged(CheckoutState previous, CheckoutState next) {
    return selector(previous) != selector(next);
  }
}

CheckoutStatus _checkoutViewModelSelectStatus(CheckoutState state) => state.status;
final _checkoutViewModelStatusAspect = _CheckoutViewModelAspect<CheckoutStatus>(
  _checkoutViewModelSelectStatus,
);

Object? _checkoutViewModelSelectShippingAddress(CheckoutState state) => state.shippingAddress;
final _checkoutViewModelShippingAddressAspect = _CheckoutViewModelAspect<Object?>(
  _checkoutViewModelSelectShippingAddress,
);

String? _checkoutViewModelSelectErrorMessage(CheckoutState state) => state.errorMessage;
final _checkoutViewModelErrorMessageAspect = _CheckoutViewModelAspect<String?>(
  _checkoutViewModelSelectErrorMessage,
);

String? _checkoutViewModelSelectOrderId(CheckoutState state) => state.orderId;
final _checkoutViewModelOrderIdAspect = _CheckoutViewModelAspect<String?>(
  _checkoutViewModelSelectOrderId,
);

String? _checkoutViewModelSelectCouponCode(CheckoutState state) => state.couponCode;
final _checkoutViewModelCouponCodeAspect = _CheckoutViewModelAspect<String?>(
  _checkoutViewModelSelectCouponCode,
);

Object? _checkoutViewModelSelectQuote(CheckoutState state) => state.quote;
final _checkoutViewModelQuoteAspect = _CheckoutViewModelAspect<Object?>(
  _checkoutViewModelSelectQuote,
);

bool _checkoutViewModelSelectIsQuoteLoading(CheckoutState state) => state.isQuoteLoading;
final _checkoutViewModelIsQuoteLoadingAspect = _CheckoutViewModelAspect<bool>(
  _checkoutViewModelSelectIsQuoteLoading,
);

abstract class $CheckoutViewModel extends ViewModelBase<CheckoutState, CheckoutViewModelArgs> {
  $CheckoutViewModel(super.args) : super(initialState: const CheckoutState());
}

class _$CheckoutViewModelProxy {
  _$CheckoutViewModelProxy(this._context);

  final BuildContext _context;

  CheckoutState get value {
    return CheckoutViewModelScope.of(_context).value;
  }

  CheckoutStatus get status {
    return CheckoutViewModelScope.of(
      _context,
      aspect: _checkoutViewModelStatusAspect,
    ).state.status;
  }

  Object? get shippingAddress {
    return CheckoutViewModelScope.of(
      _context,
      aspect: _checkoutViewModelShippingAddressAspect,
    ).state.shippingAddress;
  }

  String? get errorMessage {
    return CheckoutViewModelScope.of(
      _context,
      aspect: _checkoutViewModelErrorMessageAspect,
    ).state.errorMessage;
  }

  String? get orderId {
    return CheckoutViewModelScope.of(
      _context,
      aspect: _checkoutViewModelOrderIdAspect,
    ).state.orderId;
  }

  String? get couponCode {
    return CheckoutViewModelScope.of(
      _context,
      aspect: _checkoutViewModelCouponCodeAspect,
    ).state.couponCode;
  }

  Object? get quote {
    return CheckoutViewModelScope.of(
      _context,
      aspect: _checkoutViewModelQuoteAspect,
    ).state.quote;
  }

  bool get isQuoteLoading {
    return CheckoutViewModelScope.of(
      _context,
      aspect: _checkoutViewModelIsQuoteLoadingAspect,
    ).state.isQuoteLoading;
  }

  R select<R>(R Function(CheckoutState state) selector) {
    final aspect = _CheckoutViewModelAspect<R>(selector);
    return selector(CheckoutViewModelScope.of(_context, aspect: aspect).value);
  }
}

class CheckoutViewModelScope extends StatefulWidget {
  const CheckoutViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
  }) : value = null;

  const CheckoutViewModelScope.value({
    super.key,
    required CheckoutViewModel this.value,
    required this.child,
  }) : args = null,
       create = null;

  final CheckoutViewModelArgs Function(BuildContext context)? args;
  final CheckoutViewModel Function(BuildContext context, CheckoutViewModelArgs args)? create;
  final CheckoutViewModel? value;
  final Widget child;

  static CheckoutViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_CheckoutViewModelInherited>()
        ?.widget as _CheckoutViewModelInherited?;
    if (scope == null) throw StateError('No CheckoutViewModelScope found in context.');
    return scope.viewModel;
  }

  static CheckoutViewModel of(BuildContext context, {_CheckoutViewModelAspect<Object?>? aspect}) {
    final scope = context.dependOnInheritedWidgetOfExactType<_CheckoutViewModelInherited>(
      aspect: aspect,
    );
    if (scope == null) throw StateError('No CheckoutViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<CheckoutViewModelScope> createState() => _CheckoutViewModelScopeState();
}

class _CheckoutViewModelScopeState extends State<CheckoutViewModelScope> {
  CheckoutViewModel? _viewModel;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (_viewModel == null) {
      _replaceViewModel(_resolveViewModel(), ownsViewModel: widget.value == null, notify: false);
    }
  }

  @override
  void didUpdateWidget(CheckoutViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    }
  }

  CheckoutViewModel _resolveViewModel() {
    return widget.value ?? _createOwnedViewModel();
  }

  CheckoutViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned CheckoutViewModelScope requires args and create.');
    }
    late final CheckoutViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(
        StateError(
          'CheckoutViewModelScope failed to create its view model. Check the generated '
          'scope args/create dependency injection. Original error: $error',
        ),
        stackTrace,
      );
    }
    return created;
  }

  void _replaceViewModel(
    CheckoutViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    if (ownsViewModel) {
      scheduleMicrotask(() {
        if (mounted && identical(_viewModel, nextViewModel)) {
          nextViewModel.init();
        }
      });
    }
    if (notify && mounted) setState(() {});
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('CheckoutViewModelScope built before its view model was initialized.');
    }
    return _CheckoutViewModelInherited(
      viewModel: viewModel,
      state: viewModel.value,
      child: widget.child,
    );
  }
}

class _CheckoutViewModelInherited extends InheritedModel<_CheckoutViewModelAspect<Object?>> {
  const _CheckoutViewModelInherited({required this.viewModel, required this.state, required super.child});

  final CheckoutViewModel viewModel;
  final CheckoutState state;

  /// Requires CheckoutState to implement == and hashCode. Without value equality,
  /// every emitted state is treated as changed and granular rebuilds degrade to
  /// full dependent subtree rebuilds.
  @override
  bool updateShouldNotify(_CheckoutViewModelInherited oldWidget) => state != oldWidget.state;

  @override
  bool updateShouldNotifyDependent(
    _CheckoutViewModelInherited oldWidget,
    Set<_CheckoutViewModelAspect<Object?>> dependencies,
  ) {
    for (final aspect in dependencies) {
      if (aspect.hasChanged(oldWidget.state, state)) {
        return true;
      }
    }
    return false;
  }
}

/// Listens to one-shot effects from CheckoutViewModel.
///
/// TODO: effects are Stream<Object> until ViewModelBase supports typed effect
/// payloads through the @ViewModel annotation.
class CheckoutViewModelListener extends StatefulWidget {
  const CheckoutViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<CheckoutViewModelListener> createState() => _CheckoutViewModelListenerState();
}

class _CheckoutViewModelListenerState extends State<CheckoutViewModelListener> {
  StreamSubscription<Object>? _sub;
  CheckoutViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = CheckoutViewModelScope.read(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

extension CheckoutViewModelBuildContext on BuildContext {
  _$CheckoutViewModelProxy watchCheckoutViewModel() {
    return _$CheckoutViewModelProxy(this);
  }

  CheckoutViewModel readCheckoutViewModel() => CheckoutViewModelScope.read(this);
}
