// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'remote_todo.dart';

Never _dustJsonTypeError(Object? value, String key, String expected) => throw ArgumentError.value(value, key, 'expected $expected');
T _dustJsonAs<T>(Object? value, String key, String expected) => value is T ? value : _dustJsonTypeError(value, key, expected);
T _dustJsonParseString<T>(Object? value, String key, String expected, T? Function(String value) parse) => parse(_dustJsonAs<String>(value, key, 'String')) ?? _dustJsonTypeError(value, key, expected);
List<Object?> _dustJsonAsList(Object? value, String key) => _dustJsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _dustJsonAsMap(Object? value, String key) {
  final map = _dustJsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _dustJsonTypeError(value, key, 'Map<String, Object?>');
  }
}
DateTime _dustJsonAsDateTime(Object? value, String key) => _dustJsonParseString(value, key, 'ISO-8601 DateTime string', DateTime.tryParse);
Uri _dustJsonAsUri(Object? value, String key) => _dustJsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _dustJsonAsBigInt(Object? value, String key) => _dustJsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _dustJsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

mixin _$RemoteTodoDust {
  RemoteTodo get _dustSelf => this as RemoteTodo;

  @override
  String toString() {
    return 'RemoteTodo('
        'userId: ${_dustSelf.userId}, '
        'id: ${_dustSelf.id}, '
        'title: ${_dustSelf.title}, '
        'completed: ${_dustSelf.completed}'
        ')';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteTodo &&
          runtimeType == other.runtimeType &&
          other.userId == _dustSelf.userId &&
          other.id == _dustSelf.id &&
          other.title == _dustSelf.title &&
          other.completed == _dustSelf.completed;

  @override
  int get hashCode => Object.hashAll([
    runtimeType,
    _dustSelf.userId,
    _dustSelf.id,
    _dustSelf.title,
    _dustSelf.completed,
  ]);

  RemoteTodo copyWith({
    int? userId,
    int? id,
    String? title,
    bool? completed,
  }) {
    return RemoteTodo(
      userId: userId ?? _dustSelf.userId,
      id: id ?? _dustSelf.id,
      title: title ?? _dustSelf.title,
      completed: completed ?? _dustSelf.completed,
    );
  }

  Map<String, Object?> toJson() => _$RemoteTodoToJson(_dustSelf);
}

Map<String, Object?> _$RemoteTodoToJson(RemoteTodo instance) {
  return <String, Object?>{
    'userId': instance.userId,
    'id': instance.id,
    'title': instance.title,
    'completed': instance.completed,
  };
}
// factory RemoteTodo.fromJson(Map<String, Object?> json) => _$RemoteTodoFromJson(json);
RemoteTodo _$RemoteTodoFromJson(Map<String, Object?> json) {
  final userIdValue = _dustJsonAs<int>(json['userId'], 'userId', 'int');
  final idValue = _dustJsonAs<int>(json['id'], 'id', 'int');
  final titleValue = _dustJsonAs<String>(json['title'], 'title', 'String');
  final completedValue = _dustJsonAs<bool>(json['completed'], 'completed', 'bool');

  return RemoteTodo(
    userId: userIdValue,
    id: idValue,
    title: titleValue,
    completed: completedValue,
  );
}
