// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'remote_user.dart';

Never _dustJsonTypeError(Object? value, String key, String expected) =>
    throw ArgumentError.value(value, key, 'expected $expected');
T _dustJsonAs<T>(Object? value, String key, String expected) =>
    value is T ? value : _dustJsonTypeError(value, key, expected);
T _dustJsonParseString<T>(
  Object? value,
  String key,
  String expected,
  T? Function(String value) parse,
) =>
    parse(_dustJsonAs<String>(value, key, 'String')) ??
    _dustJsonTypeError(value, key, expected);
List<Object?> _dustJsonAsList(Object? value, String key) =>
    _dustJsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _dustJsonAsMap(Object? value, String key) {
  final map = _dustJsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _dustJsonTypeError(value, key, 'Map<String, Object?>');
  }
}

DateTime _dustJsonAsDateTime(Object? value, String key) => _dustJsonParseString(
  value,
  key,
  'ISO-8601 DateTime string',
  DateTime.tryParse,
);
Uri _dustJsonAsUri(Object? value, String key) =>
    _dustJsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _dustJsonAsBigInt(Object? value, String key) =>
    _dustJsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _dustJsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

mixin _$RemoteCompany {
  RemoteCompany get _dustSelf => this as RemoteCompany;

  @override
  String toString() {
    return 'RemoteCompany('
        'name: ${_dustSelf.name}, '
        'catchPhrase: ${_dustSelf.catchPhrase}'
        ')';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteCompany &&
          runtimeType == other.runtimeType &&
          other.name == _dustSelf.name &&
          other.catchPhrase == _dustSelf.catchPhrase;

  @override
  int get hashCode =>
      Object.hashAll([runtimeType, _dustSelf.name, _dustSelf.catchPhrase]);

  RemoteCompany copyWith({String? name, String? catchPhrase}) {
    return RemoteCompany(
      name: name ?? _dustSelf.name,
      catchPhrase: catchPhrase ?? _dustSelf.catchPhrase,
    );
  }

  Map<String, Object?> toJson() => _$RemoteCompanyToJson(_dustSelf);
}

mixin _$RemoteUser {
  RemoteUser get _dustSelf => this as RemoteUser;

  @override
  String toString() {
    return 'RemoteUser('
        'id: ${_dustSelf.id}, '
        'name: ${_dustSelf.name}, '
        'username: ${_dustSelf.username}, '
        'email: ${_dustSelf.email}, '
        'phone: ${_dustSelf.phone}, '
        'website: ${_dustSelf.website}, '
        'company: ${_dustSelf.company}'
        ')';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteUser &&
          runtimeType == other.runtimeType &&
          other.id == _dustSelf.id &&
          other.name == _dustSelf.name &&
          other.username == _dustSelf.username &&
          other.email == _dustSelf.email &&
          other.phone == _dustSelf.phone &&
          other.website == _dustSelf.website &&
          other.company == _dustSelf.company;

  @override
  int get hashCode => Object.hashAll([
    runtimeType,
    _dustSelf.id,
    _dustSelf.name,
    _dustSelf.username,
    _dustSelf.email,
    _dustSelf.phone,
    _dustSelf.website,
    _dustSelf.company,
  ]);

  RemoteUser copyWith({
    int? id,
    String? name,
    String? username,
    String? email,
    String? phone,
    String? website,
    RemoteCompany? company,
  }) {
    final nextCompany = (company ?? _dustSelf.company).copyWith();

    return RemoteUser(
      id: id ?? _dustSelf.id,
      name: name ?? _dustSelf.name,
      username: username ?? _dustSelf.username,
      email: email ?? _dustSelf.email,
      phone: phone ?? _dustSelf.phone,
      website: website ?? _dustSelf.website,
      company: nextCompany,
    );
  }

  Map<String, Object?> toJson() => _$RemoteUserToJson(_dustSelf);
}

Map<String, Object?> _$RemoteCompanyToJson(RemoteCompany instance) {
  return <String, Object?>{
    'name': instance.name,
    'catchPhrase': instance.catchPhrase,
  };
}

// factory RemoteCompany.fromJson(Map<String, Object?> json) => _$RemoteCompanyFromJson(json);
RemoteCompany _$RemoteCompanyFromJson(Map<String, Object?> json) {
  final nameValue = _dustJsonAs<String>(json['name'], 'name', 'String');
  final catchPhraseValue = _dustJsonAs<String>(
    json['catchPhrase'],
    'catchPhrase',
    'String',
  );

  return RemoteCompany(name: nameValue, catchPhrase: catchPhraseValue);
}

Map<String, Object?> _$RemoteUserToJson(RemoteUser instance) {
  return <String, Object?>{
    'id': instance.id,
    'name': instance.name,
    'username': instance.username,
    'email': instance.email,
    'phone': instance.phone,
    'website': instance.website,
    'company': _$RemoteCompanyToJson(instance.company),
  };
}

// factory RemoteUser.fromJson(Map<String, Object?> json) => _$RemoteUserFromJson(json);
RemoteUser _$RemoteUserFromJson(Map<String, Object?> json) {
  final idValue = _dustJsonAs<int>(json['id'], 'id', 'int');
  final nameValue = _dustJsonAs<String>(json['name'], 'name', 'String');
  final usernameValue = _dustJsonAs<String>(
    json['username'],
    'username',
    'String',
  );
  final emailValue = _dustJsonAs<String>(json['email'], 'email', 'String');
  final phoneValue = _dustJsonAs<String>(json['phone'], 'phone', 'String');
  final websiteValue = _dustJsonAs<String>(
    json['website'],
    'website',
    'String',
  );
  final companyValue = _$RemoteCompanyFromJson(
    _dustJsonAsMap(json['company'], 'company'),
  );

  return RemoteUser(
    id: idValue,
    name: nameValue,
    username: usernameValue,
    email: emailValue,
    phone: phoneValue,
    website: websiteValue,
    company: companyValue,
  );
}
