// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'create_todo.dart';

mixin _$CreateTodo implements Validatable {
  @override
  String toString() {
    final self = this as CreateTodo;
    return 'CreateTodo('
        'title: ${self.title}, '
        'assignTo: ${self.assignTo}, '
        'done: ${self.done}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CreateTodo;
    return identical(this, other) ||
        other is CreateTodo &&
            runtimeType == other.runtimeType &&
            other.title == self.title &&
            other.assignTo == self.assignTo &&
            other.done == self.done;
  }

  @override
  int get hashCode {
    final self = this as CreateTodo;
    return Object.hashAll([
      runtimeType,
      self.title,
      self.assignTo,
      self.done,
    ]);
  }

  /// Validates this `CreateTodo`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as CreateTodo;
    final errors = <ValidationError>[];
    _CreateTodoValidation._validateTitle(self.title, errors);
    _CreateTodoValidation._validateAssignTo(self.assignTo, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `CreateTodo` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }
}

extension _CreateTodoValidation on CreateTodo {
  static void _validateTitle(String title, List<ValidationError> errors) {
    if (title.length < 1) {
      errors.add(ValidationError(field: 'title', message: 'must be 1 to 200 characters'));
    }
    if (title.length > 200) {
      errors.add(ValidationError(field: 'title', message: 'must be 1 to 200 characters'));
    }
  }

  static void _validateAssignTo(String assignTo, List<ValidationError> errors) {
    if (!ValidationHelper.isEmail(assignTo)) {
      errors.add(ValidationError(field: 'assignTo', message: 'must be an email address'));
    }
  }

}
final class $CreateTodoDeserializer implements Deserializer<CreateTodo, Map<String, Object?>> {
  const $CreateTodoDeserializer();

  @override
  CreateTodo deserialize(Map<String, Object?> json) => _$CreateTodoDeserialize(json);
}

// factory CreateTodo.fromJson(Map<String, Object?> json) => _$CreateTodoFromJson(json);
CreateTodo _$CreateTodoDeserialize(Map<String, Object?> json) {
  final titleValue = JsonHelper.as<String>(json['title'], 'title', 'String');
  final assignToValue = JsonHelper.as<String>(
    json['assignTo'],
    'assignTo',
    'String',
  );
  final doneValue = json.containsKey('done')
      ? JsonHelper.as<bool>(json['done'], 'done', 'bool')
      : false;

  return CreateTodo(
    title: titleValue,
    assignTo: assignToValue,
    done: doneValue,
  );
}

CreateTodo _$CreateTodoFromJson(Map<String, Object?> json) =>
    _$CreateTodoDeserialize(json);
