// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

import 'package:dio/dio.dart';
import 'package:test/test.dart';
import 'todo_api.dart';

void main() {
  group('TodoApi request mapping', () {
    test('GET list', () async {
      RequestOptions? captured;
      final dio = Dio();
      dio.interceptors.add(
        InterceptorsWrapper(
          onRequest: (options, handler) {
            captured = options;
            handler.resolve(Response<dynamic>(requestOptions: options, data: const <dynamic>[]));
          },
        ),
      );
      final api = TodoApi(dio);
      try {
        await api.list(userId: 42, page: 42, traceId: 'dust-id');
      } catch (_) {}
      expect(captured, isNotNull);
      final request = captured!;
      expect(request.method, 'GET');
      expect(request.path, '/todos');
      expect(request.queryParameters, isA<Map<String, dynamic>>());
      expect(request.headers, isA<Map<String, dynamic>>());
      expect(request.queryParameters['userId'], equals(42));
      expect(request.queryParameters['page'], equals(42));
      expect(request.headers['x-trace-id'], equals('dust-id'));
      expect(request.headers['x-api-version'], equals('2026-05'));
      expect(request.headers['x-endpoint'], equals('todos'));
    });
    test('GET fetchRaw', () async {
      RequestOptions? captured;
      final dio = Dio();
      dio.interceptors.add(
        InterceptorsWrapper(
          onRequest: (options, handler) {
            captured = options;
            handler.resolve(Response<dynamic>(requestOptions: options, data: const <String, dynamic>{}));
          },
        ),
      );
      final api = TodoApi(dio);
      try {
        await api.fetchRaw('dust-id', cancelToken: null, retryable: true);
      } catch (_) {}
      expect(captured, isNotNull);
      final request = captured!;
      expect(request.method, 'GET');
      expect(request.path, '/todos/dust-id');
      expect(request.queryParameters, isA<Map<String, dynamic>>());
      expect(request.headers, isA<Map<String, dynamic>>());
      expect(request.headers['x-api-version'], equals('2026-05'));
    });
    test('POST create', () {}, skip: 'Dust could not synthesize fixtures for one or more parameters');
    test('PATCH rename', () async {
      RequestOptions? captured;
      final dio = Dio();
      dio.interceptors.add(
        InterceptorsWrapper(
          onRequest: (options, handler) {
            captured = options;
            handler.resolve(Response<dynamic>(requestOptions: options, data: const <String, dynamic>{}));
          },
        ),
      );
      final api = TodoApi(dio);
      try {
        await api.rename('dust-id', 'dust-id');
      } catch (_) {}
      expect(captured, isNotNull);
      final request = captured!;
      expect(request.method, 'PATCH');
      expect(request.path, '/todos/dust-id');
      expect(request.queryParameters, isA<Map<String, dynamic>>());
      expect(request.headers, isA<Map<String, dynamic>>());
      expect((request.data as Map<String, dynamic>)['title'], equals('dust-id'));
      expect(request.headers['x-api-version'], equals('2026-05'));
    });
    test('PUT update', () {}, skip: 'Dust could not synthesize fixtures for one or more parameters');
    test('DELETE delete', () async {
      RequestOptions? captured;
      final dio = Dio();
      dio.interceptors.add(
        InterceptorsWrapper(
          onRequest: (options, handler) {
            captured = options;
            handler.resolve(Response<dynamic>(requestOptions: options, data: null));
          },
        ),
      );
      final api = TodoApi(dio);
      try {
        await api.delete('dust-id', audit: const <String, dynamic>{'value': 'dust'});
      } catch (_) {}
      expect(captured, isNotNull);
      final request = captured!;
      expect(request.method, 'DELETE');
      expect(request.path, '/todos/dust-id');
      expect(request.queryParameters, isA<Map<String, dynamic>>());
      expect(request.headers, isA<Map<String, dynamic>>());
      expect(request.headers['x-api-version'], equals('2026-05'));
    });
  });
}
