// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'demo_cart_state.dart';

const DeepCollectionEquality _deepCollectionEquality = DeepCollectionEquality();

mixin _$DemoCartState {
  @override
  String toString() {
    final self = this as DemoCartState;
    return 'DemoCartState('
        'status: ${self.status}, '
        'carts: ${self.carts}, '
        'errorMessage: ${self.errorMessage}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as DemoCartState;
    return identical(this, other) ||
        other is DemoCartState &&
            runtimeType == other.runtimeType &&
            other.status == self.status &&
            _deepCollectionEquality.equals(other.carts, self.carts) &&
            other.errorMessage == self.errorMessage;
  }

  @override
  int get hashCode {
    final self = this as DemoCartState;
    return Object.hashAll([
      runtimeType,
      self.status,
      _deepCollectionEquality.hash(self.carts),
      self.errorMessage,
    ]);
  }

  DemoCartState copyWith({
    DemoCartStatus? status,
    List<StoreCart>? carts,
    Option<String?> errorMessage = const None(),
  }) {
    final self = this as DemoCartState;
    final nextCarts = List<StoreCart>.of(
      (carts ?? self.carts).map((item_1) => item_1.copyWith()),
    );
    final nextErrorMessage = switch (errorMessage) {
      None<String?>() => self.errorMessage,
      Some<String?>(:final value) => value,
    };

    return DemoCartState(
      status: status ?? self.status,
      carts: nextCarts,
      errorMessage: nextErrorMessage,
    );
  }
}
