// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'demo_cart_state.dart';

const DeepCollectionEquality _demoCartStateCartsEquality = DeepCollectionEquality();
final class _DemoCartStateCopyWithUnset {
  const _DemoCartStateCopyWithUnset();
}

const _demoCartStateCopyWithUnset = _DemoCartStateCopyWithUnset();

mixin _$DemoCartState {
  @override
  String toString() {
    final self = this as DemoCartState;
    return 'DemoCartState('
        'status: ${self.status}, '
        'carts: ${self.carts}, '
        'errorMessage: ${self.errorMessage}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as DemoCartState;
    return identical(this, other) ||
        other is DemoCartState &&
            runtimeType == other.runtimeType &&
            other.status == self.status &&
            _demoCartStateCartsEquality.equals(other.carts, self.carts) &&
            other.errorMessage == self.errorMessage;
  }

  @override
  int get hashCode {
    final self = this as DemoCartState;
    return Object.hashAll([
      runtimeType,
      self.status,
      _demoCartStateCartsEquality.hash(self.carts),
      self.errorMessage,
    ]);
  }

  /// Creates a copy of this `DemoCartState` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = demoCartState.copyWith();
  /// final cleared = demoCartState.copyWith(errorMessage: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$DemoCartStateCopyWith<DemoCartState> get copyWith => _$DemoCartStateCopyWithImpl<DemoCartState>(this as DemoCartState, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$DemoCartStateCopyWith<$Res> {
  $Res call({
    DemoCartStatus? status,
    List<StoreCart>? carts,
    String? errorMessage,
  });
}

/// @nodoc
final class _$DemoCartStateCopyWithImpl<$Res> implements _$DemoCartStateCopyWith<$Res> {
  const _$DemoCartStateCopyWithImpl(this._self, this._then);

  final DemoCartState _self;
  final $Res Function(DemoCartState) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? status = null,
    Object? carts = null,
    Object? errorMessage = _demoCartStateCopyWithUnset,
  }) {
    return _then(
      DemoCartState(
        status: status == null ? _self.status : status as DemoCartStatus,
        carts: carts == null ? _self.carts : carts as List<StoreCart>,
        errorMessage: identical(errorMessage, _demoCartStateCopyWithUnset)
            ? _self.errorMessage
            : errorMessage as String?,
      )
    );
  }
}
