// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'http_post.dart';

Never _dustJsonTypeError(Object? value, String key, String expected) =>
    throw ArgumentError.value(value, key, 'expected $expected');
T _dustJsonAs<T>(Object? value, String key, String expected) =>
    value is T ? value : _dustJsonTypeError(value, key, expected);
T _dustJsonParseString<T>(
  Object? value,
  String key,
  String expected,
  T? Function(String value) parse,
) =>
    parse(_dustJsonAs<String>(value, key, 'String')) ??
    _dustJsonTypeError(value, key, expected);
List<Object?> _dustJsonAsList(Object? value, String key) =>
    _dustJsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _dustJsonAsMap(Object? value, String key) {
  final map = _dustJsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _dustJsonTypeError(value, key, 'Map<String, Object?>');
  }
}

DateTime _dustJsonAsDateTime(Object? value, String key) => _dustJsonParseString(
  value,
  key,
  'ISO-8601 DateTime string',
  DateTime.tryParse,
);
Uri _dustJsonAsUri(Object? value, String key) =>
    _dustJsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _dustJsonAsBigInt(Object? value, String key) =>
    _dustJsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _dustJsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

mixin _$HttpPost {
  HttpPost get _dustSelf => this as HttpPost;

  @override
  String toString() {
    return 'HttpPost('
        'userId: ${_dustSelf.userId}, '
        'id: ${_dustSelf.id}, '
        'title: ${_dustSelf.title}, '
        'body: ${_dustSelf.body}'
        ')';
  }

  HttpPost copyWith({int? userId, int? id, String? title, String? body}) {
    return HttpPost(
      userId: userId ?? _dustSelf.userId,
      id: id ?? _dustSelf.id,
      title: title ?? _dustSelf.title,
      body: body ?? _dustSelf.body,
    );
  }

  Map<String, Object?> toJson() => _$HttpPostToJson(_dustSelf);
}

Map<String, Object?> _$HttpPostToJson(HttpPost instance) {
  return <String, Object?>{
    'userId': instance.userId,
    'id': instance.id,
    'title': instance.title,
    'body': instance.body,
  };
}

// factory HttpPost.fromJson(Map<String, Object?> json) => _$HttpPostFromJson(json);
HttpPost _$HttpPostFromJson(Map<String, Object?> json) {
  final userIdValue = _dustJsonAs<int>(json['userId'], 'userId', 'int');
  final idValue = _dustJsonAs<int>(json['id'], 'id', 'int');
  final titleValue = _dustJsonAs<String>(json['title'], 'title', 'String');
  final bodyValue = _dustJsonAs<String>(json['body'], 'body', 'String');

  return HttpPost(
    userId: userIdValue,
    id: idValue,
    title: titleValue,
    body: bodyValue,
  );
}
