name: shopping_app
description: Dust shopping app example using Dust router, state, HTTP client, and serde.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0
  shared_preferences: ^2.3.4
  dust_dart:
    path: ../../packages/dust_dart
  dust_flutter:
    path: ../../packages/dust_flutter
  dust_db_sqlite3:
    path: ../../packages/dust_db_sqlite3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

hooks:
  user_defines:
    sqlite3:
      source: system
      name: sqlite3
      name_windows: winsqlite3
