use std::{fs, process::Command, thread, time::Duration};

use dust_cli::run_cli;
use tempfile::tempdir;

fn write_file(path: &std::path::Path, contents: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create parent dirs");
    }
    fs::write(path, contents).expect("write file");
}

fn make_workspace() -> tempfile::TempDir {
    let root = tempdir().unwrap();
    write_file(&root.path().join("pubspec.yaml"), "name: dust_test\n");
    write_file(&root.path().join(".dart_tool/package_config.json"), "{}\n");
    root
}

#[test]
fn cli_build_writes_real_output() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/user.dart"),
        "part 'user.g.dart';\n\
         @Debug()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let run = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);

    assert_eq!(run.exit_code, 0);
    assert!(run.stderr.is_empty());
    assert!(run.stdout.contains("scanned: 1"));
    assert!(run.stdout.contains("generated: 1"));
    assert!(run.stdout.contains("skipped: 0"));
    assert!(!run.stdout.contains(workspace.path().to_str().unwrap()));
    assert!(workspace.path().join("lib/user.g.dart").exists());
}

#[test]
fn cli_second_build_reports_cached_output() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/user.dart"),
        "part 'user.g.dart';\n\
         @Debug()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let first = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);
    let second = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);

    assert_eq!(first.exit_code, 0);
    assert_eq!(second.exit_code, 0);
    assert!(second.stdout.contains("scanned: 1"));
    assert!(second.stdout.contains("generated: 0"));
    assert!(second.stdout.contains("skipped: 1"));
    assert!(!second.stdout.contains("cache "));
}

#[test]
fn cli_clean_removes_dust_outputs_and_cache() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/user.dart"),
        "part 'user.g.dart';\n\
         @Debug()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let built = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);
    assert_eq!(built.exit_code, 0);
    assert!(workspace.path().join("lib/user.g.dart").exists());
    assert!(
        workspace
            .path()
            .join(".dart_tool/dust/build_cache_v1.json")
            .exists()
    );

    write_file(
        &workspace.path().join("lib/foreign.g.dart"),
        "// generated by someone else\n",
    );

    let run = run_cli(["clean", "--root", workspace.path().to_str().unwrap()]);

    assert_eq!(run.exit_code, 0);
    assert!(run.stderr.is_empty());
    assert!(run.stdout.contains("clean  scanned: 2"));
    assert!(run.stdout.contains("removed: 1"));
    assert!(run.stdout.contains("cache: cleared"));
    assert!(!workspace.path().join("lib/user.g.dart").exists());
    assert!(workspace.path().join("lib/foreign.g.dart").exists());
    assert!(!workspace.path().join(".dart_tool/dust").exists());
}

#[test]
fn cli_check_returns_stale_exit_code_before_build() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/user.dart"),
        "part 'user.g.dart';\n\
         @Debug()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let run = run_cli(["check", "--root", workspace.path().to_str().unwrap()]);

    assert_eq!(run.exit_code, 2);
    assert!(run.stdout.is_empty());
    assert!(run.stderr.contains("stale"));
}

#[test]
fn cli_watch_reports_rebuilt_library() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/user.dart"),
        "part 'user.g.dart';\n\
         @Debug()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let root = workspace.path().to_path_buf();
    let user_path = root.join("lib/user.dart");
    let modifier = thread::spawn(move || {
        thread::sleep(Duration::from_millis(25));
        write_file(
            &user_path,
            "part 'user.g.dart';\n\
             @Debug()\n\
             class User {\n\
               final String id;\n\
               final int age;\n\
               const User(this.id, this.age);\n\
             }\n",
        );
    });

    let run = run_cli([
        "watch",
        "--root",
        workspace.path().to_str().unwrap(),
        "--poll-ms",
        "20",
        "--max-cycles",
        "3",
    ]);
    modifier.join().unwrap();

    assert_eq!(run.exit_code, 0);
    assert!(run.stdout.contains("watch  scanned:"));
    assert!(run.stdout.contains("rebuilds: 1"));
}

#[test]
fn binary_help_smoke_test() {
    let binary = env!("CARGO_BIN_EXE_dust");
    let output = Command::new(binary).arg("help").output().unwrap();

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("dust 0.1.0"));
    assert!(stdout.contains("Commands:"));
    assert!(stdout.contains("build     Scan Dart sources and generate `.g.dart` outputs"));
    assert!(stdout.contains("watch     Keep running and regenerate affected outputs"));
    assert!(stdout.contains("clean     Remove Dust-generated outputs and cache"));
    assert!(!stdout.contains("doctor"));
    assert!(!stdout.contains("check"));
    assert!(!stdout.contains("--jobs <n>"));
}
