use dust_cli::run_cli;

use super::helpers::{make_pub_workspace_member, make_workspace, write_file};

#[test]
fn cli_build_writes_real_output() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/user.dart"),
        "part 'user.g.dart';\n\
         @ToString()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let run = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);

    assert_eq!(run.exit_code, 0);
    assert!(run.stderr.is_empty());
    assert!(run.stdout.contains("scanned: 1"));
    assert!(run.stdout.contains("generated: 1"));
    assert!(run.stdout.contains("skipped: 0"));
    assert!(!run.stdout.contains(workspace.path().to_str().unwrap()));
    assert!(workspace.path().join("lib/user.g.dart").exists());
}

#[test]
fn cli_build_reports_route_contributors_separately() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/route.dart"),
        "import 'pages/dashboard_page.dart';\n\
         import 'pages/not_found_page.dart';\n\
         import 'route.g.dart';\n\
         @AppRouter(initial: '/', notFound: '/404')\n\
         final class TestRouter extends $TestRouter {\n\
           const TestRouter();\n\
         }\n",
    );
    write_file(
        &workspace.path().join("lib/pages/dashboard_page.dart"),
        "@AppRoute('/', name: 'dashboard')\n\
         final class DashboardPage {\n\
           const DashboardPage();\n\
         }\n",
    );
    write_file(
        &workspace.path().join("lib/pages/not_found_page.dart"),
        "@AppRoute('/404', name: 'notFound', guards: [])\n\
         final class NotFoundPage {\n\
           const NotFoundPage({this.path = ''});\n\
           final String path;\n\
         }\n",
    );

    let first = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);
    let second = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);

    assert_eq!(first.exit_code, 0, "{}", first.stderr);
    assert!(first.stdout.contains("scanned: 3"));
    assert!(first.stdout.contains("generated: 3"));
    assert!(!first.stdout.contains("routed:"));
    assert!(first.stdout.contains("skipped: 0"));
    assert_eq!(second.exit_code, 0, "{}", second.stderr);
    assert!(second.stdout.contains("scanned: 3"));
    assert!(second.stdout.contains("generated: 2"));
    assert!(!second.stdout.contains("routed:"));
    assert!(second.stdout.contains("cached: 1"));
    assert!(second.stdout.contains("skipped: 0"));
    assert!(workspace.path().join("lib/route.g.dart").exists());
    assert!(
        !workspace
            .path()
            .join("lib/pages/dashboard_page.g.dart")
            .exists()
    );
    assert!(
        !workspace
            .path()
            .join("lib/pages/not_found_page.g.dart")
            .exists()
    );
}

#[test]
fn cli_second_build_reports_cached_output() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/user.dart"),
        "part 'user.g.dart';\n\
         @ToString()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let first = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);
    let second = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);

    assert_eq!(first.exit_code, 0);
    assert_eq!(second.exit_code, 0);
    assert!(second.stdout.contains("scanned: 1"));
    assert!(second.stdout.contains("generated: 0"));
    assert!(second.stdout.contains("cached: 1"));
    assert!(second.stdout.contains("skipped: 0"));
    assert!(!second.stdout.contains("cache "));
}

#[test]
fn cli_build_clean_regenerates_without_previous_cache_hit() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/user.dart"),
        "part 'user.g.dart';\n\
         @ToString()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let first = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);
    let cached = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);
    let foreign_output = workspace.path().join("lib/foreign.g.dart");
    write_file(&foreign_output, "// generated by someone else\n");
    let clean = run_cli([
        "build",
        "--clean",
        "--root",
        workspace.path().to_str().unwrap(),
    ]);
    let later = run_cli(["build", "--root", workspace.path().to_str().unwrap()]);

    assert_eq!(first.exit_code, 0, "{}", first.stderr);
    assert_eq!(cached.exit_code, 0, "{}", cached.stderr);
    assert!(cached.stdout.contains("cached: 1"));
    assert_eq!(clean.exit_code, 0, "{}", clean.stderr);
    assert!(clean.stdout.contains("generated: 1"));
    assert!(clean.stdout.contains("cached: 0"));
    assert!(workspace.path().join("lib/user.g.dart").exists());
    assert!(foreign_output.exists());
    assert!(
        workspace
            .path()
            .join(".dart_tool/dust/build_cache_v1.json")
            .exists()
    );
    assert_eq!(later.exit_code, 0, "{}", later.stderr);
    assert!(later.stdout.contains("cached: 1"));
}

#[test]
fn cli_build_supports_pub_workspace_member_package_graph() {
    let (workspace, package_root) = make_pub_workspace_member();
    write_file(
        &package_root.join("lib/user.dart"),
        "part 'user.g.dart';\n\
         @ToString()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let first = run_cli(["build", "--root", package_root.to_str().unwrap()]);
    let second = run_cli(["build", "--root", package_root.to_str().unwrap()]);

    assert_eq!(first.exit_code, 0, "{}", first.stderr);
    assert_eq!(second.exit_code, 0, "{}", second.stderr);
    assert!(package_root.join("lib/user.g.dart").exists());
    assert!(
        package_root
            .join(".dart_tool/dust/build_cache_v1.json")
            .exists()
    );
    assert!(
        !workspace
            .path()
            .join(".dart_tool/dust/build_cache_v1.json")
            .exists()
    );
    assert!(second.stdout.contains("generated: 0"));
    assert!(second.stdout.contains("cached: 1"));
    assert!(second.stdout.contains("skipped: 0"));
}
