// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'wishlist_view_model.dart';

/// Base class generated for WishlistViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class WishlistViewModel extends $WishlistViewModel {
///   WishlistViewModel(super.args);
/// }
/// ```
abstract class $WishlistViewModel extends ViewModelBase<WishlistState, WishlistViewModelArgs> {
  $WishlistViewModel(super.args) : super(initialState: const WishlistState());
}

/// Reads WishlistViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchWishlistViewModel().value;
/// ```
class _$WishlistViewModelProxy {
  _$WishlistViewModelProxy(this._context);

  final BuildContext _context;

  WishlistState get value {
    return WishlistViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected WishlistState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class WishlistViewModelSelector<R> extends StatefulWidget {
  const WishlistViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(WishlistState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<WishlistViewModelSelector<R>> createState() => _WishlistViewModelSelectorState<R>();
}

class _WishlistViewModelSelectorState<R> extends State<WishlistViewModelSelector<R>> {
  WishlistViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = WishlistViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(WishlistViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides WishlistViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// WishlistViewModelScope(
///   args: (context) => WishlistViewModelArgs(...),
///   create: (context, args) => WishlistViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class WishlistViewModelScope extends StatefulWidget {
  /// Creates and owns WishlistViewModel from typed args.
  const WishlistViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned WishlistViewModel without disposing it.
  const WishlistViewModelScope.value({
    super.key,
    required WishlistViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final WishlistViewModelArgs Function(BuildContext context)? args;
  final WishlistViewModel Function(BuildContext context, WishlistViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final WishlistViewModel? value;
  final Widget child;

  /// Reads WishlistViewModel without rebuilding when state changes.
  static WishlistViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_WishlistViewModelInstance>()
        ?.widget as _WishlistViewModelInstance?;
    if (scope == null) throw StateError('No WishlistViewModelScope found in context.');
    return scope.viewModel;
  }

  static WishlistViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_WishlistViewModelInstance>();
    if (scope == null) throw StateError('No WishlistViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches WishlistViewModel and rebuilds when state changes.
  static WishlistViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_WishlistViewModelInherited>();
    if (scope == null) throw StateError('No WishlistViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<WishlistViewModelScope> createState() => _WishlistViewModelScopeState();
}

class _WishlistViewModelScopeState extends State<WishlistViewModelScope> {
  WishlistViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(WishlistViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  WishlistViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned WishlistViewModelScope requires args and create.');
    }
    late final WishlistViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(
        StateError(
          'WishlistViewModelScope failed to create its view model. Check the generated '
          'scope args/create dependency injection. Original error: $error',
        ),
        stackTrace,
      );
    }
    return created;
  }

  void _replaceViewModel(
    WishlistViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(WishlistViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('WishlistViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('WishlistViewModelScope built before its view model was initialized.');
    }
    return _WishlistViewModelInstance(
      viewModel: viewModel,
      child: _WishlistViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _WishlistViewModelInstance extends InheritedWidget {
  const _WishlistViewModelInstance({required this.viewModel, required super.child});

  final WishlistViewModel viewModel;

  @override
  bool updateShouldNotify(_WishlistViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _WishlistViewModelInherited extends InheritedWidget {
  const _WishlistViewModelInherited({required this.viewModel, required this.state, required super.child});

  final WishlistViewModel viewModel;
  final WishlistState state;

  @override
  bool updateShouldNotify(_WishlistViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from WishlistViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// WishlistViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class WishlistViewModelListener extends StatefulWidget {
  const WishlistViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<WishlistViewModelListener> createState() => _WishlistViewModelListenerState();
}

class _WishlistViewModelListenerState extends State<WishlistViewModelListener> {
  StreamSubscription<Object>? _sub;
  WishlistViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = WishlistViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for WishlistViewModel.
///
/// ```dart
/// final vm = context.readWishlistViewModel();
/// final state = context.watchWishlistViewModel().value;
/// ```
extension WishlistViewModelBuildContext on BuildContext {
  _$WishlistViewModelProxy watchWishlistViewModel() {
    return _$WishlistViewModelProxy(this);
  }

  WishlistViewModel readWishlistViewModel() => WishlistViewModelScope.read(this);
}
