name: dust_db_sqlite3
description: sqlite3 runtime for Dust DB.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  dust_db_runtime:
    path: ../dust_db_runtime
  sqlite3: ^3.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
