// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'accounts_repo.dart';

final class _$AccountsRepo implements AccountsRepo {
  const _$AccountsRepo(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<Account?, SqlxError>> accountForToken(String tokenHash, String now) {
    return _db.fetchOptional<Account>(
      r'''
SELECT a.id, a.email, a.password_hash, a.password_salt, a.scopes
FROM accounts a
JOIN api_tokens t ON t.account_id = a.id
WHERE t.token_hash = ? AND t.expires_at > ?
''',
      [tokenHash, now],
      AccountFromRow.fromRow,
    );
  }

  @override
  Future<Result<Account?, SqlxError>> accountByEmail(String email) {
    return _db.fetchOptional<Account>(
      r'''
SELECT id, email, password_hash, password_salt, scopes FROM accounts
WHERE email = ?
''',
      [email],
      AccountFromRow.fromRow,
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> insertAccount(String email, String passwordHash, String passwordSalt, String scopes) {
    return _db.execute(
      r'''
INSERT INTO accounts (email, password_hash, password_salt, scopes)
VALUES (?, ?, ?, ?)
''',
      [email, passwordHash, passwordSalt, scopes],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> insertToken(int accountId, String tokenHash, String expiresAt) {
    return _db.execute(
      r'''
INSERT INTO api_tokens (account_id, token_hash, expires_at)
VALUES (?, ?, ?)
''',
      [accountId, tokenHash, expiresAt],
    );
  }
}
