// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'shopping_cache_rows.dart';

extension CachedProductRowFromRow on CachedProductRow {
  static CachedProductRow fromRow(Row row) {
    return CachedProductRow(
      id: row.read<int>('id'),
      title: row.read<String>('title'),
      price: row.read<double>('price'),
      description: row.read<String>('description'),
      category: row.read<String>('category'),
      imageUrl: row.read<String>('image'),
      rating: CachedProductRatingRowFromRow.fromRow(row),
      pinned: false,
      payload: CachedProductPayload.fromJson(decodeJsonObject(row.read<String>('payload'))),
      source: CacheSourceFromString().decode(row.read<String>('source')),
    );
  }
}

final bool _$cachedProductRowFromRowRegistered = registerRowMapper<CachedProductRow>(CachedProductRowFromRow.fromRow);

extension CachedProductRatingRowFromRow on CachedProductRatingRow {
  static CachedProductRatingRow fromRow(Row row) {
    return CachedProductRatingRow(
      rate: row.read<double>('rating_rate'),
      count: row.read<int>('rating_count'),
    );
  }
}

final bool _$cachedProductRatingRowFromRowRegistered = registerRowMapper<CachedProductRatingRow>(CachedProductRatingRowFromRow.fromRow);

extension CachedWishlistRowFromRow on CachedWishlistRow {
  static CachedWishlistRow fromRow(Row row) {
    return CachedWishlistRow(
      productId: row.read<int>('product_id'),
      title: row.read<String>('title'),
      savedAt: row.readDateTime('saved_at'),
    );
  }
}

final bool _$cachedWishlistRowFromRowRegistered = registerRowMapper<CachedWishlistRow>(CachedWishlistRowFromRow.fromRow);
