part of 'routing_core.dart';

/// Maximum redirect hops before the router reports a debug-cycle assertion.
const int maxRedirects = 8;

/// Mutable route stack maintained by the generated router delegate.
typedef RouteStack<T extends Object> = List<T>;

/// Converts an incoming browser or platform URI into a typed route object.
typedef RouteParser<T extends Object> = T Function(Uri uri);

/// Builds a Flutter page for one typed route object and stack entry key.
typedef RoutePageBuilder<T extends Object> = Page<dynamic> Function(
  T route,
  LocalKey key,
  PopInvokedWithResultCallback<Object?> onPopInvoked,
);

/// Resolves route-level guards for one typed route object.
typedef RouteGuardResolver<T extends Object> = List<RouteGuardBase<T>> Function(
    T route);

/// Converts a typed route object back into a URL location.
typedef RouteLocation<T extends Object> = String Function(T route);

/// Returns whether a route participates in auth checks.
typedef RouteRequiresAuth<T extends Object> = bool Function(T route);

/// Returns the stateful navigation branch for a route, if any.
typedef RouteBranch<T extends Object> = String? Function(T route);

/// Returns debug metadata for a typed route.
typedef RouteDebugInfoResolver<T extends Object> = RouteDebugInfo Function(
  T route,
);

/// Restores the Navigator page stack for a browser/deep-link route.
typedef RouteStackRestorer<T extends Object> = RouteStack<T> Function(T route);

/// Human-readable route facts used by diagnostics.
final class RouteDebugInfo {
  /// Creates debug metadata for one route.
  const RouteDebugInfo({
    this.name,
    this.shell,
    this.branch,
    this.resultType = 'void',
  });

  /// Generated route name.
  final String? name;

  /// Effective shell type name.
  final String? shell;

  /// Stateful navigation branch name.
  final String? branch;

  /// Generated route result type source.
  final String resultType;
}

/// Base class for user-owned generated routers.
abstract class RouterBase<T extends Object> {
  /// Optional listenable that triggers redirect and guard reevaluation.
  Listenable? get refreshListenable => null;

  /// Navigator observers attached to the generated root Navigator.
  List<NavigatorObserver> get observers => const [];

  /// Whether generated routing should print runtime diagnostics.
  bool get debugLogDiagnostics => false;

  /// Normalizes incoming route information before generated route matching.
  ///
  /// Override this to map host-specific, prefixed, or legacy URLs into the
  /// app's typed route space while preserving Flutter's [RouteInformation]
  /// shape.
  RouteInformation parseRouteInformation(RouteInformation information) {
    return information;
  }

  /// Returns a replacement route before guards run, or `null` to continue.
  T? redirect(T route) => null;

  /// Handles asynchronous router failures from unawaited navigation work.
  void onException(Object error, StackTrace stackTrace) {
    FlutterError.reportError(
      FlutterErrorDetails(
        exception: error,
        stack: stackTrace,
        library: 'dust_flutter routing',
        context: ErrorDescription('while navigating with a generated router'),
      ),
    );
  }

  /// Called after the generated router commits a route stack change.
  ///
  /// [previous] and [next] are immutable snapshots of the typed route stack.
  /// The callback is not called for refreshes or replacements that keep the
  /// same route locations.
  void didChangeRouteStack(RouteStack<T> previous, RouteStack<T> next) {}
}

/// Runtime configuration generated for one router.
final class RouterRuntimeConfig<T extends Object> {
  /// Creates a router runtime configuration.
  const RouterRuntimeConfig({
    required this.router,
    required this.initialRoute,
    required this.parseRoute,
    required this.routeLocation,
    required this.requiresAuth,
    this.routeBranch = _noRouteBranch,
    required this.resolveGuards,
    required this.buildPage,
    this.restoreStack,
    this.debugInfo,
    this.debugRoutes = const [],
  });

  /// User-owned router instance.
  final RouterBase<T> router;

  /// Route used when the app starts with no explicit route.
  final T initialRoute;

  /// URI-to-route parser generated by Dust.
  final RouteParser<T> parseRoute;

  /// Route-to-location formatter generated by Dust.
  final RouteLocation<T> routeLocation;

  /// Auth requirement lookup generated by Dust.
  final RouteRequiresAuth<T> requiresAuth;

  /// Branch lookup generated by Dust.
  final RouteBranch<T> routeBranch;

  /// Route guard lookup generated by Dust.
  final RouteGuardResolver<T> resolveGuards;

  /// Page builder generated by Dust.
  final RoutePageBuilder<T> buildPage;

  /// Optional stack builder used for browser refresh and deep links.
  final RouteStackRestorer<T>? restoreStack;

  /// Optional route debug metadata lookup generated by Dust.
  final RouteDebugInfoResolver<T>? debugInfo;

  /// Generated route metadata printed when diagnostics are enabled.
  final List<GeneratedRoute> debugRoutes;
}

String? _noRouteBranch(Object route) => null;

/// Inherited scope used by generated BuildContext extensions.
class RouterScope extends InheritedNotifier<Listenable> {
  /// Creates a router scope.
  const RouterScope({
    required this.controller,
    required super.notifier,
    required super.child,
    super.key,
  });

  /// Router controller stored as Object.
  ///
  /// Generated routers keep their route type private.
  final Object controller;
}
