part of 'routing_core.dart';

/// Navigator 2.0 route information parser for generated routes.
final class GeneratedRouteInformationParser<T extends Object>
    extends RouteInformationParser<T> {
  /// Creates a route information parser.
  const GeneratedRouteInformationParser({
    required this.parseRoute,
    required this.routeLocation,
  });

  /// URI-to-route parser generated by Dust.
  final RouteParser<T> parseRoute;

  /// Route-to-location formatter generated by Dust.
  final RouteLocation<T> routeLocation;

  @override
  Future<T> parseRouteInformation(RouteInformation routeInformation) async {
    return parseRoute(routeInformation.uri);
  }

  @override
  RouteInformation restoreRouteInformation(T configuration) {
    return RouteInformation(uri: Uri.parse(routeLocation(configuration)));
  }
}
