part of 'routing_core.dart';

/// Navigator 2.0 route information parser for generated routes.
final class GeneratedRouteInformationParser<T extends Object>
    extends RouteInformationParser<T> {
  /// Creates a route information parser.
  const GeneratedRouteInformationParser({
    required this.parseRoute,
    required this.routeLocation,
  });

  /// URI-to-route parser generated by Dust.
  final RouteParser<T> parseRoute;

  /// Route-to-location formatter generated by Dust.
  final RouteLocation<T> routeLocation;

  @override
  Future<T> parseRouteInformation(RouteInformation routeInformation) async {
    return parseRoute(routeInformation.uri);
  }

  @override
  RouteInformation restoreRouteInformation(T configuration) {
    return RouteInformation(uri: Uri.parse(routeLocation(configuration)));
  }
}

/// Internal navigation action mode.
enum NavigationMode {
  /// Replace the current stack with the target route.
  go,

  /// Add the target route to the top of the stack.
  push,

  /// Replace the current top route with the target route.
  replace,

  /// Restore a route from platform route information.
  restore,
}

/// Navigator 2.0 delegate used by generated routers.
final class GeneratedRouterDelegate<T extends Object> extends RouterDelegate<T>
    with ChangeNotifier, PopNavigatorRouterDelegateMixin<T> {
  /// Creates a router delegate from generated [config].
  GeneratedRouterDelegate(this.config) {
    _controller = RouterController<T>._(this);
    _entries.add(_RouteEntry(config.initialRoute));
    _rebuildPageKeyMap();
    config.router.refreshListenable?.addListener(_scheduleRefresh);
    _scheduleRefresh();
  }

  /// Generated router runtime configuration.
  final RouterRuntimeConfig<T> config;

  /// Mutable route stack used by `Navigator.pages`.
  RouteStack<T> get stack =>
      _entries.map((entry) => entry.route).toList(growable: false);

  /// Stack entry keys exposed for router runtime tests.
  @visibleForTesting
  List<LocalKey> get debugPageKeys =>
      _entries.map((entry) => entry.key).toList(growable: false);

  final List<_RouteEntry<T>> _entries = <_RouteEntry<T>>[];
  final Map<Key, int> _keyToStackIndex = <Key, int>{};
  late final RouterController<T> _controller;
  bool _refreshScheduled = false;
  int _navigationEpoch = 0;

  /// Last route in the stack, or the configured initial route.
  T get currentRoute =>
      _entries.isEmpty ? config.initialRoute : _entries.last.route;

  @override
  final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

  @override
  T get currentConfiguration => currentRoute;

  @override
  Widget build(BuildContext context) {
    return RouterScope(
      controller: _controller,
      notifier: this,
      child: Navigator(
        key: navigatorKey,
        pages: [
          for (final entry in _entries)
            config.buildPage(entry.route, entry.key),
        ],
        onDidRemovePage: (page) {
          final key = page.key;
          final index = key == null ? null : _keyToStackIndex[key];
          if (index != null && index >= 0 && index < _entries.length) {
            _entries.removeAt(index);
            _rebuildPageKeyMap();
            notifyListeners();
          }
        },
      ),
    );
  }

  @override
  Future<void> setNewRoutePath(T configuration) {
    return _applyRoute(configuration, NavigationMode.restore);
  }

  @override
  Future<bool> popRoute() async {
    if (_entries.length <= 1) return false;
    _entries.removeLast();
    _rebuildPageKeyMap();
    notifyListeners();
    return true;
  }

  /// Navigates to [route], replacing the current stack.
  void go(T route) => unawaited(_applyRoute(route, NavigationMode.go));

  /// Pushes [route] on top of the current stack.
  void push(T route) => unawaited(_applyRoute(route, NavigationMode.push));

  /// Replaces the current top route with [route].
  void replace(T route) =>
      unawaited(_applyRoute(route, NavigationMode.replace));

  @override
  void dispose() {
    config.router.refreshListenable?.removeListener(_scheduleRefresh);
    super.dispose();
  }

  void _scheduleRefresh() {
    if (_refreshScheduled) return;
    _refreshScheduled = true;
    scheduleMicrotask(() {
      _refreshScheduled = false;
      unawaited(_applyRoute(currentRoute, NavigationMode.replace));
    });
  }

  Future<void> _applyRoute(
    T requested,
    NavigationMode mode, [
    int guardRedirects = 0,
  ]) async {
    final epoch = ++_navigationEpoch;
    var candidate = requested;

    if (guardRedirects >= maxRedirects) {
      throw StateError(
        'Router guard redirects hit the redirect cap ($maxRedirects) '
        'navigating to "${config.routeLocation(requested)}". '
        'Check for a guard redirect cycle.',
      );
    }

    var redirects = 0;
    for (; redirects < maxRedirects; redirects += 1) {
      final redirected = config.router.redirect(candidate);
      if (redirected == null ||
          config.routeLocation(redirected) == config.routeLocation(candidate)) {
        break;
      }
      candidate = redirected;
    }
    if (redirects >= maxRedirects) {
      throw StateError(
        'Router hit the redirect cap ($maxRedirects) navigating to '
        '"${config.routeLocation(requested)}". Check for a redirect cycle.',
      );
    }
    assert(
      redirects < maxRedirects,
      'Router hit the redirect cap ($maxRedirects) navigating to '
      '"${config.routeLocation(requested)}". Check for a redirect cycle.',
    );

    if (epoch != _navigationEpoch) return;

    final guards = config.resolveGuards(candidate);
    if (guards.isNotEmpty) {
      final redirected = await RouteGuardChain<T>(
        guards,
      ).canActivate(candidate);
      if (epoch != _navigationEpoch) return;
      if (redirected != null) {
        await _applyRoute(redirected, mode, guardRedirects + 1);
        return;
      }
    }

    _commitRoute(candidate, mode);
  }

  void _commitRoute(T route, NavigationMode mode) {
    switch (mode) {
      case NavigationMode.go:
        _entries
          ..clear()
          ..add(_RouteEntry(route));
      case NavigationMode.push:
        _entries.add(_RouteEntry(route));
      case NavigationMode.replace:
        if (_entries.isEmpty) {
          _entries.add(_RouteEntry(route));
        } else {
          _entries[_entries.length - 1] = _entryForReplacement(
            _entries.last,
            route,
          );
        }
      case NavigationMode.restore:
        final restored = config.restoreStack?.call(route);
        _entries
          ..clear()
          ..addAll(
            (restored == null || restored.isEmpty ? <T>[route] : restored)
                .map(_RouteEntry<T>.new),
          );
    }
    _rebuildPageKeyMap();
    notifyListeners();
  }

  _RouteEntry<T> _entryForReplacement(_RouteEntry<T> previous, T route) {
    if (config.routeLocation(previous.route) == config.routeLocation(route)) {
      return previous.withRoute(route);
    }
    return _RouteEntry(route);
  }

  void _rebuildPageKeyMap() {
    _keyToStackIndex
      ..clear()
      ..addEntries(
        _entries.indexed.map((entry) {
          final (index, routeEntry) = entry;
          return MapEntry<Key, int>(routeEntry.key, index);
        }),
      );
  }
}

final class _RouteEntry<T extends Object> {
  _RouteEntry(T route) : this._(route, UniqueKey());

  const _RouteEntry._(this.route, this.key);

  final T route;
  final LocalKey key;

  _RouteEntry<T> withRoute(T route) => _RouteEntry<T>._(route, key);
}
