part of 'routing_core.dart';

/// Maximum redirect hops before the router reports a debug-cycle assertion.
const int maxRedirects = 8;

/// Mutable route stack maintained by the generated router delegate.
typedef RouteStack<T extends Object> = List<T>;

/// Converts an incoming browser or platform URI into a typed route object.
typedef RouteParser<T extends Object> = T Function(Uri uri);

/// Builds a Flutter page for one typed route object.
typedef RoutePageBuilder<T extends Object> = Page<dynamic> Function(T route);

/// Resolves route-level guards for one typed route object.
typedef RouteGuardResolver<T extends Object> = List<Object> Function(T route);

/// Converts a typed route object back into a URL location.
typedef RouteLocation<T extends Object> = String Function(T route);

/// Returns whether a route participates in auth checks.
typedef RouteRequiresAuth<T extends Object> = bool Function(T route);

/// Restores the Navigator page stack for a browser/deep-link route.
typedef RouteStackRestorer<T extends Object> = RouteStack<T> Function(T route);

/// Base class for user-owned generated routers.
abstract class RouterBase<T extends Object> {
  /// Optional listenable that triggers redirect and guard reevaluation.
  Listenable? get refreshListenable => null;

  /// Returns a replacement route before guards run, or `null` to continue.
  T? redirect(T route) => null;
}

/// Runtime configuration generated for one router.
final class RouterRuntimeConfig<T extends Object> {
  /// Creates a router runtime configuration.
  const RouterRuntimeConfig({
    required this.router,
    required this.initialRoute,
    required this.parseRoute,
    required this.routeLocation,
    required this.requiresAuth,
    required this.resolveGuards,
    required this.buildPage,
    this.restoreStack,
  });

  /// User-owned router instance.
  final RouterBase<T> router;

  /// Route used when the app starts with no explicit route.
  final T initialRoute;

  /// URI-to-route parser generated by Dust.
  final RouteParser<T> parseRoute;

  /// Route-to-location formatter generated by Dust.
  final RouteLocation<T> routeLocation;

  /// Auth requirement lookup generated by Dust.
  final RouteRequiresAuth<T> requiresAuth;

  /// Route guard lookup generated by Dust.
  final RouteGuardResolver<T> resolveGuards;

  /// Page builder generated by Dust.
  final RoutePageBuilder<T> buildPage;

  /// Optional stack builder used for browser refresh and deep links.
  final RouteStackRestorer<T>? restoreStack;
}

/// Inherited scope used by generated BuildContext extensions.
class RouterScope extends InheritedNotifier<Listenable> {
  /// Creates a router scope.
  const RouterScope({
    required this.controller,
    required super.notifier,
    required super.child,
    super.key,
  });

  /// Router controller stored as Object so generated routers can keep T private.
  final Object controller;
}
