part of 'routing_core.dart';

/// Navigator 2.0 route information parser for generated routes.
final class GeneratedRouteInformationParser<T extends Object>
    extends RouteInformationParser<T> {
  /// Creates a route information parser.
  const GeneratedRouteInformationParser({
    required this.parseRoute,
    required this.routeLocation,
  });

  /// URI-to-route parser generated by Dust.
  final RouteParser<T> parseRoute;

  /// Route-to-location formatter generated by Dust.
  final RouteLocation<T> routeLocation;

  @override
  Future<T> parseRouteInformation(RouteInformation routeInformation) async {
    return parseRoute(routeInformation.uri);
  }

  @override
  RouteInformation restoreRouteInformation(T configuration) {
    return RouteInformation(uri: Uri.parse(routeLocation(configuration)));
  }
}

/// Internal navigation action mode.
enum NavigationMode { go, push, replace, restore }

/// Navigator 2.0 delegate used by generated routers.
final class GeneratedRouterDelegate<T extends Object> extends RouterDelegate<T>
    with ChangeNotifier, PopNavigatorRouterDelegateMixin<T> {
  /// Creates a router delegate from generated [config].
  GeneratedRouterDelegate(this.config) {
    _controller = RouterController<T>._(this);
    stack.add(config.initialRoute);
    _rebuildPageKeyMap();
    config.router.refreshListenable?.addListener(_scheduleRefresh);
    _scheduleRefresh();
  }

  /// Generated router runtime configuration.
  final RouterRuntimeConfig<T> config;

  /// Mutable route stack used by `Navigator.pages`.
  final RouteStack<T> stack = <T>[];
  final Map<Key, int> _keyToStackIndex = <Key, int>{};
  late final RouterController<T> _controller;
  bool _refreshScheduled = false;
  int _navigationEpoch = 0;

  T get currentRoute => stack.isEmpty ? config.initialRoute : stack.last;

  @override
  final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

  @override
  T get currentConfiguration => currentRoute;

  @override
  Widget build(BuildContext context) {
    return RouterScope(
      controller: _controller,
      notifier: this,
      child: Navigator(
        key: navigatorKey,
        pages: [for (final route in stack) config.buildPage(route)],
        onDidRemovePage: (page) {
          final key = page.key;
          final index = key == null ? null : _keyToStackIndex[key];
          if (index != null && index >= 0 && index < stack.length) {
            stack.removeAt(index);
            _rebuildPageKeyMap();
            notifyListeners();
          }
        },
      ),
    );
  }

  @override
  Future<void> setNewRoutePath(T configuration) {
    return _applyRoute(configuration, NavigationMode.restore);
  }

  @override
  Future<bool> popRoute() async {
    if (stack.length <= 1) return false;
    stack.removeLast();
    _rebuildPageKeyMap();
    notifyListeners();
    return true;
  }

  void go(T route) => unawaited(_applyRoute(route, NavigationMode.go));

  void push(T route) => unawaited(_applyRoute(route, NavigationMode.push));

  void replace(T route) =>
      unawaited(_applyRoute(route, NavigationMode.replace));

  @override
  void dispose() {
    config.router.refreshListenable?.removeListener(_scheduleRefresh);
    super.dispose();
  }

  void _scheduleRefresh() {
    if (_refreshScheduled) return;
    _refreshScheduled = true;
    scheduleMicrotask(() {
      _refreshScheduled = false;
      unawaited(_applyRoute(currentRoute, NavigationMode.replace));
    });
  }

  Future<void> _applyRoute(T requested, NavigationMode mode) async {
    final epoch = ++_navigationEpoch;
    var candidate = requested;

    var redirects = 0;
    for (; redirects < maxRedirects; redirects += 1) {
      final redirected = config.router.redirect(candidate);
      if (redirected == null ||
          config.routeLocation(redirected) == config.routeLocation(candidate)) {
        break;
      }
      candidate = redirected;
    }
    assert(
      redirects < maxRedirects,
      'Router hit the redirect cap ($maxRedirects) navigating to '
      '"${config.routeLocation(requested)}". Check for a redirect cycle.',
    );

    if (epoch != _navigationEpoch) return;

    final guards = config.resolveGuards(candidate);
    if (guards.isNotEmpty) {
      final redirected = await RouteGuardChain<T>(
        guards,
      ).canActivate(candidate);
      if (epoch != _navigationEpoch) return;
      if (redirected != null) {
        await _applyRoute(redirected, mode);
        return;
      }
    }

    _commitRoute(candidate, mode);
  }

  void _commitRoute(T route, NavigationMode mode) {
    switch (mode) {
      case NavigationMode.go:
        stack
          ..clear()
          ..add(route);
      case NavigationMode.push:
        stack.add(route);
      case NavigationMode.replace:
        if (stack.isEmpty) {
          stack.add(route);
        } else {
          stack[stack.length - 1] = route;
        }
      case NavigationMode.restore:
        final restored = config.restoreStack?.call(route);
        stack
          ..clear()
          ..addAll(
            restored == null || restored.isEmpty ? <T>[route] : restored,
          );
    }
    _rebuildPageKeyMap();
    notifyListeners();
  }

  void _rebuildPageKeyMap() {
    _keyToStackIndex
      ..clear()
      ..addEntries(
        stack.indexed.map((entry) {
          final (index, route) = entry;
          return MapEntry<Key, int>(_pageKey(route), index);
        }),
      );
  }

  Key _pageKey(T route) => ValueKey<String>(config.routeLocation(route));
}
