use dust_driver::{BuildRequest, CleanRequest, run_build, run_clean};

use super::support::{make_workspace, write_file};

#[test]
fn second_build_uses_persistent_cache_under_dot_dart_tool() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/user.dart"),
        "part 'user.g.dart';\n\
         @ToString()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let first = run_build(BuildRequest {
        cwd: workspace.path().to_path_buf(),
        fail_fast: false,
        jobs: Some(4),
    });
    let second = run_build(BuildRequest {
        cwd: workspace.path().to_path_buf(),
        fail_fast: false,
        jobs: Some(4),
    });

    assert!(!first.has_errors());
    assert!(!second.has_errors());
    assert!(
        workspace
            .path()
            .join(".dart_tool/dust/build_cache_v1.json")
            .exists()
    );
    assert!(first.build_artifacts[0].written);
    assert!(!second.build_artifacts[0].written);
    assert!(second.build_artifacts[0].cached);
    assert_eq!(second.cache.as_ref().unwrap().hits, 1);
    assert_eq!(second.cache.as_ref().unwrap().misses, 0);
}

#[test]
fn clean_removes_dust_outputs_and_cache_but_keeps_foreign_generated_files() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/user.dart"),
        "part 'user.g.dart';\n\
         @ToString()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let built = run_build(BuildRequest {
        cwd: workspace.path().to_path_buf(),
        fail_fast: false,
        jobs: None,
    });
    assert!(!built.has_errors());

    let foreign_output = workspace.path().join("lib/foreign.g.dart");
    write_file(&foreign_output, "// generated by someone else\n");
    assert!(
        workspace
            .path()
            .join(".dart_tool/dust/build_cache_v1.json")
            .exists()
    );

    let result = run_clean(CleanRequest {
        cwd: workspace.path().to_path_buf(),
    });

    assert!(!result.has_errors());
    let clean = result.clean.as_ref().unwrap();
    assert_eq!(clean.scanned_files, 2);
    assert_eq!(clean.removed_files, 1);
    assert!(clean.cache_cleared);
    assert!(!workspace.path().join("lib/user.g.dart").exists());
    assert!(foreign_output.exists());
    assert!(!workspace.path().join(".dart_tool/dust").exists());
}

#[test]
fn parallel_build_keeps_artifact_order_deterministic() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/z_team.dart"),
        "part 'z_team.g.dart';\n\
         @CopyWith()\n\
         class Team {\n\
           final String id;\n\
           const Team(this.id);\n\
         }\n",
    );
    write_file(
        &workspace.path().join("lib/a_user.dart"),
        "part 'a_user.g.dart';\n\
         @ToString()\n\
         class User {\n\
           final String id;\n\
           const User(this.id);\n\
         }\n",
    );

    let result = run_build(BuildRequest {
        cwd: workspace.path().to_path_buf(),
        fail_fast: false,
        jobs: Some(4),
    });

    let outputs = result
        .build_artifacts
        .iter()
        .map(|artifact| artifact.output_path.clone())
        .collect::<Vec<_>>();

    assert_eq!(
        outputs,
        vec![
            workspace.path().join("lib/a_user.g.dart"),
            workspace.path().join("lib/z_team.g.dart"),
        ]
    );
}

#[test]
fn build_skips_invalid_library_and_continues_when_fail_fast_is_false() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/bad.dart"),
        "part 'bad.g.dart';\n\
         @CopyWith()\n\
         class Broken {\n\
           final String id;\n\
           final int age;\n\
           const Broken(this.id);\n\
         }\n",
    );
    write_file(
        &workspace.path().join("lib/good.dart"),
        "part 'good.g.dart';\n\
         @CopyWith()\n\
         class Good {\n\
           final String id;\n\
           const Good(this.id);\n\
         }\n",
    );

    let result = run_build(BuildRequest {
        cwd: workspace.path().to_path_buf(),
        fail_fast: false,
        jobs: None,
    });

    assert!(result.has_errors());
    assert!(result.diagnostics.iter().any(|diagnostic| {
        diagnostic.message.contains(
            "`CopyWith` requires a constructor that accepts every field on class `Broken`",
        )
    }));
    assert!(!workspace.path().join("lib/bad.g.dart").exists());
    assert!(workspace.path().join("lib/good.g.dart").exists());
}

#[test]
fn build_stops_after_first_error_when_fail_fast_is_true() {
    let workspace = make_workspace();
    write_file(
        &workspace.path().join("lib/a_bad.dart"),
        "part 'a_bad.g.dart';\n\
         @CopyWith()\n\
         class Broken {\n\
           final String id;\n\
           final int age;\n\
           const Broken(this.id);\n\
         }\n",
    );
    write_file(
        &workspace.path().join("lib/z_good.dart"),
        "part 'z_good.g.dart';\n\
         @CopyWith()\n\
         class Good {\n\
           final String id;\n\
           const Good(this.id);\n\
         }\n",
    );

    let result = run_build(BuildRequest {
        cwd: workspace.path().to_path_buf(),
        fail_fast: true,
        jobs: None,
    });

    assert!(result.has_errors());
    assert_eq!(result.build_artifacts.len(), 1);
    assert!(!workspace.path().join("lib/z_good.g.dart").exists());
}
