use std::path::Path;

use dust_diagnostics::Diagnostic;
use dust_ir::LibraryIr;
use dust_plugin_api::{PluginRegistry, SymbolPlan};

use crate::{format::format_generated_source, merge::MergedSections, writer::DartWriter};

/// The in-memory result of emitting one generated library.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmitResult {
    /// The assembled `.g.dart` source text.
    pub source: String,
    /// The reserved generated helper symbols for this file.
    pub symbols: SymbolPlan,
    /// Diagnostics emitted during validation or emission.
    pub diagnostics: Vec<Diagnostic>,
    /// Whether the newly emitted source differs from the previous output.
    pub changed: bool,
}

/// Emits one generated library without touching the filesystem.
pub fn emit_library(
    library: &LibraryIr,
    registry: &PluginRegistry,
    previous_output: Option<&str>,
) -> EmitResult {
    let plan = registry.build_symbol_plan(library);
    emit_library_with_plan(library, registry, plan, previous_output)
}

/// Emits one generated library with an explicitly prepared symbol plan.
pub fn emit_library_with_plan(
    library: &LibraryIr,
    registry: &PluginRegistry,
    plan: SymbolPlan,
    previous_output: Option<&str>,
) -> EmitResult {
    let diagnostics = registry.validate_library(library);
    let contributions = registry.emit_contributions(library, &plan);
    let merged = MergedSections::from_contributions(&contributions);
    let source = assemble_source(library, &plan, &merged);
    let source = format_generated_source(&source);
    let changed = previous_output != Some(source.as_str());

    EmitResult {
        source,
        symbols: plan,
        diagnostics,
        changed,
    }
}

fn assemble_source(library: &LibraryIr, plan: &SymbolPlan, merged: &MergedSections) -> String {
    let source_name = Path::new(&library.source_path)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("source.dart");

    let mut writer = DartWriter::new();
    writer.line("// GENERATED CODE - DO NOT MODIFY BY HAND");
    writer.line("// coverage:ignore-file");
    writer.line("// ignore_for_file: type=lint");
    writer.line("// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark");
    writer.line("// Generated by dust.");
    writer.blank_line();
    writer.line(format!("part of '{source_name}';"));

    let symbol_helpers = render_reserved_helpers(plan);
    if !symbol_helpers.is_empty() {
        writer.blank_line();
        for helper in symbol_helpers {
            writer.line(helper);
        }
    }
    if !merged.shared_helpers.is_empty() {
        writer.blank_line();
        for helper in &merged.shared_helpers {
            writer.raw_block(helper);
        }
    }

    for class in &library.classes {
        let members = merged.members_for_class(&class.name);
        if !members.is_empty() {
            writer.blank_line();
            render_mixin_block(&mut writer, &class.name, members);
        }
    }

    if !merged.support_types.is_empty() {
        writer.blank_line();
        for support in &merged.support_types {
            writer.raw_block(support);
        }
    }
    if !merged.top_level_functions.is_empty() {
        writer.blank_line();
        for function in &merged.top_level_functions {
            writer.raw_block(function);
        }
    }

    writer.finish()
}

fn render_reserved_helpers(plan: &SymbolPlan) -> Vec<String> {
    let mut helpers = Vec::new();

    if plan.contains("_undefined") {
        helpers.push("const Object _undefined = Object();".to_owned());
    }

    helpers
}

fn render_mixin_block(writer: &mut DartWriter, class_name: &str, members: &[String]) {
    let mixin_name = format!("_${class_name}Dust");
    writer.start_block(format!("mixin {mixin_name}"));
    writer.line(format!(
        "{class_name} get _dustSelf => this as {class_name};"
    ));

    if !members.is_empty() {
        writer.blank_line();
        for (index, member) in members.iter().enumerate() {
            if index > 0 {
                writer.blank_line();
            }
            writer.raw_block(member);
        }
    }

    writer.end_block();
}
