name: derive_annotation
description: Base Dust derive annotations for Dart models and future extension packages.
version: 0.1.0
homepage: https://github.com/y3l1n4ung/dust
repository: https://github.com/y3l1n4ung/dust
issue_tracker: https://github.com/y3l1n4ung/dust/issues

environment:
  sdk: ^3.11.0

resolution: workspace

topics:
  - codegen
  - annotations
  - dust

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
