// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'order.dart';

const DeepCollectionEquality _orderItemsEquality = DeepCollectionEquality();

mixin _$Order {
  @override
  String toString() {
    final self = this as Order;
    return 'Order('
        'id: ${self.id}, '
        'items: ${self.items}, '
        'totalAmount: ${self.totalAmount}, '
        'status: ${self.status}, '
        'createdAt: ${self.createdAt}, '
        'shippingAddress: ${self.shippingAddress}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Order;
    return identical(this, other) ||
        other is Order &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            _orderItemsEquality.equals(other.items, self.items) &&
            other.totalAmount == self.totalAmount &&
            other.status == self.status &&
            other.createdAt == self.createdAt &&
            other.shippingAddress == self.shippingAddress;
  }

  @override
  int get hashCode {
    final self = this as Order;
    return Object.hashAll([
      runtimeType,
      self.id,
      _orderItemsEquality.hash(self.items),
      self.totalAmount,
      self.status,
      self.createdAt,
      self.shippingAddress,
    ]);
  }

  /// Creates a copy of this `Order` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = order.copyWith(id: 'John');
  /// final nested = order.copyWith.shippingAddress(fullName: 'London');
  /// ```
  @pragma('vm:prefer-inline')
  _$OrderCopyWith<Order> get copyWith => _$OrderCopyWithImpl<Order>(this as Order, (value) => value);

  Map<String, Object?> toJson() => _$OrderToJson(this as Order);
}

mixin _$ShippingAddress {
  @override
  String toString() {
    final self = this as ShippingAddress;
    return 'ShippingAddress('
        'fullName: ${self.fullName}, '
        'address: ${self.address}, '
        'city: ${self.city}, '
        'zipCode: ${self.zipCode}, '
        'phone: ${self.phone}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ShippingAddress;
    return identical(this, other) ||
        other is ShippingAddress &&
            runtimeType == other.runtimeType &&
            other.fullName == self.fullName &&
            other.address == self.address &&
            other.city == self.city &&
            other.zipCode == self.zipCode &&
            other.phone == self.phone;
  }

  @override
  int get hashCode {
    final self = this as ShippingAddress;
    return Object.hashAll([
      runtimeType,
      self.fullName,
      self.address,
      self.city,
      self.zipCode,
      self.phone,
    ]);
  }

  /// Creates a copy of this `ShippingAddress` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = shippingAddress.copyWith(fullName: 'John');
  /// ```
  @pragma('vm:prefer-inline')
  _$ShippingAddressCopyWith<ShippingAddress> get copyWith => _$ShippingAddressCopyWithImpl<ShippingAddress>(this as ShippingAddress, (value) => value);

  Map<String, Object?> toJson() =>
      _$ShippingAddressToJson(this as ShippingAddress);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$OrderCopyWith<$Res> {
  $Res call({
    String? id,
    List<CartItem>? items,
    double? totalAmount,
    OrderStatus? status,
    DateTime? createdAt,
    ShippingAddress? shippingAddress,
  });

  _$ShippingAddressCopyWith<$Res> get shippingAddress;
}

/// @nodoc
final class _$OrderCopyWithImpl<$Res> implements _$OrderCopyWith<$Res> {
  const _$OrderCopyWithImpl(this._self, this._then);

  final Order _self;
  final $Res Function(Order) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? id = null,
    Object? items = null,
    Object? totalAmount = null,
    Object? status = null,
    Object? createdAt = null,
    Object? shippingAddress = null,
  }) {
    return _then(
      Order(
        id: id == null ? _self.id : id as String,
        items: items == null ? _self.items : items as List<CartItem>,
        totalAmount: totalAmount == null ? _self.totalAmount : totalAmount as double,
        status: status == null ? _self.status : status as OrderStatus,
        createdAt: createdAt == null ? _self.createdAt : createdAt as DateTime,
        shippingAddress: shippingAddress == null ? _self.shippingAddress : shippingAddress as ShippingAddress,
      )
    );
  }

  @override
  @pragma('vm:prefer-inline')
  _$ShippingAddressCopyWith<$Res> get shippingAddress {
    return _$ShippingAddressCopyWithImpl<$Res>(
      _self.shippingAddress,
      (value) => call(shippingAddress: value),
    );
  }
}
/// @nodoc
abstract class _$ShippingAddressCopyWith<$Res> {
  $Res call({
    String? fullName,
    String? address,
    String? city,
    String? zipCode,
    String? phone,
  });
}

/// @nodoc
final class _$ShippingAddressCopyWithImpl<$Res> implements _$ShippingAddressCopyWith<$Res> {
  const _$ShippingAddressCopyWithImpl(this._self, this._then);

  final ShippingAddress _self;
  final $Res Function(ShippingAddress) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? fullName = null,
    Object? address = null,
    Object? city = null,
    Object? zipCode = null,
    Object? phone = null,
  }) {
    return _then(
      ShippingAddress(
        fullName: fullName == null ? _self.fullName : fullName as String,
        address: address == null ? _self.address : address as String,
        city: city == null ? _self.city : city as String,
        zipCode: zipCode == null ? _self.zipCode : zipCode as String,
        phone: phone == null ? _self.phone : phone as String,
      )
    );
  }
}

Map<String, Object?> _$OrderToJson(Order instance) {
  return <String, Object?>{
    'id': instance.id,
    'items': instance.items
        .map((item) => item.toJson())
        .toList(),
    'totalAmount': instance.totalAmount,
    'status': _$OrderStatusToJson(instance.status),
    'createdAt': instance.createdAt.toIso8601String(),
    'shippingAddress': _$ShippingAddressToJson(instance.shippingAddress),
  };
}

// factory Order.fromJson(Map<String, Object?> json) => _$OrderFromJson(json);
Order _$OrderFromJson(Map<String, Object?> json) {
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final itemsValue = JsonHelper.decodeList(json['items'], 'items',
      (item, itemKey) => CartItem.fromJson(JsonHelper.asMap(item, itemKey)));
  final totalAmountValue = JsonHelper.as<num>(json['totalAmount'], 'totalAmount', 'num').toDouble();
  final statusValue = _$OrderStatusFromJson(json['status'], 'status');
  final createdAtValue = JsonHelper.asDateTime(json['createdAt'], 'createdAt');
  final shippingAddressValue = _$ShippingAddressFromJson(
    JsonHelper.asMap(json['shippingAddress'], 'shippingAddress'),
  );

  return Order(
    id: idValue,
    items: itemsValue,
    totalAmount: totalAmountValue,
    status: statusValue,
    createdAt: createdAtValue,
    shippingAddress: shippingAddressValue,
  );
}

Map<String, Object?> _$ShippingAddressToJson(ShippingAddress instance) {
  return <String, Object?>{
    'fullName': instance.fullName,
    'address': instance.address,
    'city': instance.city,
    'zipCode': instance.zipCode,
    'phone': instance.phone,
  };
}

// factory ShippingAddress.fromJson(Map<String, Object?> json) => _$ShippingAddressFromJson(json);
ShippingAddress _$ShippingAddressFromJson(Map<String, Object?> json) {
  final fullNameValue = JsonHelper.as<String>(
    json['fullName'],
    'fullName',
    'String',
  );
  final addressValue = JsonHelper.as<String>(
    json['address'],
    'address',
    'String',
  );
  final cityValue = JsonHelper.as<String>(json['city'], 'city', 'String');
  final zipCodeValue = JsonHelper.as<String>(
    json['zipCode'],
    'zipCode',
    'String',
  );
  final phoneValue = JsonHelper.as<String>(json['phone'], 'phone', 'String');

  return ShippingAddress(
    fullName: fullNameValue,
    address: addressValue,
    city: cityValue,
    zipCode: zipCodeValue,
    phone: phoneValue,
  );
}

Object? _$OrderStatusToJson(OrderStatus instance) {
  return switch (instance) {
    OrderStatus.pending => 'pending',
    OrderStatus.processing => 'processing',
    OrderStatus.shipped => 'shipped',
    OrderStatus.delivered => 'delivered',
    OrderStatus.cancelled => 'cancelled',
  };
}

OrderStatus _$OrderStatusFromJson(Object? json, [String key = 'json']) {
  return switch (json) {
    'pending' => OrderStatus.pending,
    'processing' => OrderStatus.processing,
    'shipped' => OrderStatus.shipped,
    'delivered' => OrderStatus.delivered,
    'cancelled' => OrderStatus.cancelled,
    _ => throw ArgumentError.value(json, key, 'unknown value for OrderStatus at $key'),
  };
}
