// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'order_tracking.dart';

Never _jsonTypeError(Object? value, String key, String expected) =>
    throw ArgumentError.value(value, key, 'expected $expected');
T _jsonAs<T>(Object? value, String key, String expected) =>
    value is T ? value : _jsonTypeError(value, key, expected);
T _jsonParseString<T>(
  Object? value,
  String key,
  String expected,
  T? Function(String value) parse,
) =>
    parse(_jsonAs<String>(value, key, 'String')) ??
    _jsonTypeError(value, key, expected);
List<Object?> _jsonAsList(Object? value, String key) =>
    _jsonAs<List>(value, key, 'List<Object?>').cast<Object?>();

Map<String, Object?> _jsonAsMap(Object? value, String key) {
  final map = _jsonAs<Map>(value, key, 'Map<String, Object?>');
  try {
    return Map<String, Object?>.from(map);
  } on TypeError {
    _jsonTypeError(value, key, 'Map<String, Object?>');
  }
}

DateTime _jsonAsDateTime(Object? value, String key) =>
    _jsonParseString(value, key, 'ISO-8601 DateTime string', DateTime.tryParse);
Uri _jsonAsUri(Object? value, String key) =>
    _jsonParseString(value, key, 'Uri string', Uri.tryParse);
BigInt _jsonAsBigInt(Object? value, String key) =>
    _jsonParseString(value, key, 'BigInt string', BigInt.tryParse);
T _jsonDecodeWithCodec<T>(dynamic codec, Object? value, String key) {
  if (value == null) {
    throw ArgumentError.value(value, key, 'expected value for SerDeCodec');
  }
  try {
    return codec.deserialize(value as dynamic) as T;
  } catch (error) {
    throw ArgumentError.value(value, key, 'failed SerDeCodec decode: $error');
  }
}

mixin _$TrackingEvent {
  @override
  String toString() {
    final self = this as TrackingEvent;
    return 'TrackingEvent('
        'id: ${self.id}, '
        'orderId: ${self.orderId}, '
        'title: ${self.title}, '
        'description: ${self.description}, '
        'location: ${self.location}, '
        'occurredAt: ${self.occurredAt}, '
        'completed: ${self.completed}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as TrackingEvent;
    return identical(this, other) ||
        other is TrackingEvent &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.orderId == self.orderId &&
            other.title == self.title &&
            other.description == self.description &&
            other.location == self.location &&
            other.occurredAt == self.occurredAt &&
            other.completed == self.completed;
  }

  @override
  int get hashCode {
    final self = this as TrackingEvent;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.orderId,
      self.title,
      self.description,
      self.location,
      self.occurredAt,
      self.completed,
    ]);
  }

  TrackingEvent copyWith({
    String? id,
    String? orderId,
    String? title,
    String? description,
    String? location,
    DateTime? occurredAt,
    bool? completed,
  }) {
    final self = this as TrackingEvent;
    return TrackingEvent(
      id: id ?? self.id,
      orderId: orderId ?? self.orderId,
      title: title ?? self.title,
      description: description ?? self.description,
      location: location ?? self.location,
      occurredAt: occurredAt ?? self.occurredAt,
      completed: completed ?? self.completed,
    );
  }

  Map<String, Object?> toJson() => _$TrackingEventToJson(this as TrackingEvent);
}

Map<String, Object?> _$TrackingEventToJson(TrackingEvent instance) {
  return <String, Object?>{
    'id': instance.id,
    'orderId': instance.orderId,
    'title': instance.title,
    'description': instance.description,
    'location': instance.location,
    'occurredAt': instance.occurredAt.toIso8601String(),
    'completed': instance.completed,
  };
}
// factory TrackingEvent.fromJson(Map<String, Object?> json) => _$TrackingEventFromJson(json);
TrackingEvent _$TrackingEventFromJson(Map<String, Object?> json) {
  final idValue = _jsonAs<String>(json['id'], 'id', 'String');
  final orderIdValue = _jsonAs<String>(json['orderId'], 'orderId', 'String');
  final titleValue = _jsonAs<String>(json['title'], 'title', 'String');
  final descriptionValue = _jsonAs<String>(
    json['description'],
    'description',
    'String',
  );
  final locationValue = _jsonAs<String>(json['location'], 'location', 'String');
  final occurredAtValue = _jsonAsDateTime(json['occurredAt'], 'occurredAt');
  final completedValue = _jsonAs<bool>(json['completed'], 'completed', 'bool');

  return TrackingEvent(
    id: idValue,
    orderId: orderIdValue,
    title: titleValue,
    description: descriptionValue,
    location: locationValue,
    occurredAt: occurredAtValue,
    completed: completedValue,
  );
}
