// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'orders_state.dart';

const DeepCollectionEquality _ordersStateOrdersEquality = DeepCollectionEquality();

mixin _$OrdersState {
  @override
  String toString() {
    final self = this as OrdersState;
    return 'OrdersState('
        'orders: ${self.orders}, '
        'isLoading: ${self.isLoading}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as OrdersState;
    return identical(this, other) ||
        other is OrdersState &&
            runtimeType == other.runtimeType &&
            _ordersStateOrdersEquality.equals(other.orders, self.orders) &&
            other.isLoading == self.isLoading;
  }

  @override
  int get hashCode {
    final self = this as OrdersState;
    return Object.hashAll([
      runtimeType,
      _ordersStateOrdersEquality.hash(self.orders),
      self.isLoading,
    ]);
  }

  OrdersState copyWith({
    List<Order>? orders,
    bool? isLoading,
  }) {
    final self = this as OrdersState;
    final nextOrders = List<Order>.of(
      (orders ?? self.orders).map((item_0) => item_0.copyWith()),
    );

    return OrdersState(
      orders: nextOrders,
      isLoading: isLoading ?? self.isLoading,
    );
  }
}
