name: dust_db_annotation
description: Dust DB annotations for sqlx-style database generation.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  derive_annotation:
    path: ../derive_annotation

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
