// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'task_board_state.dart';

const Object _undefined = Object();

const DeepCollectionEquality _dustDeepCollectionEquality =
    DeepCollectionEquality();

mixin _$TaskBoardState {
  TaskBoardState get _dustSelf => this as TaskBoardState;

  @override
  String toString() {
    return 'TaskBoardState('
        'todos: ${_dustSelf.todos}, '
        'query: ${_dustSelf.query}, '
        'filter: ${_dustSelf.filter}, '
        'isLoading: ${_dustSelf.isLoading}, '
        'isRefreshing: ${_dustSelf.isRefreshing}, '
        'isInitialized: ${_dustSelf.isInitialized}, '
        'errorMessage: ${_dustSelf.errorMessage}'
        ')';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskBoardState &&
          runtimeType == other.runtimeType &&
          _dustDeepCollectionEquality.equals(other.todos, _dustSelf.todos) &&
          other.query == _dustSelf.query &&
          other.filter == _dustSelf.filter &&
          other.isLoading == _dustSelf.isLoading &&
          other.isRefreshing == _dustSelf.isRefreshing &&
          other.isInitialized == _dustSelf.isInitialized &&
          other.errorMessage == _dustSelf.errorMessage;

  @override
  int get hashCode => Object.hashAll([
    runtimeType,
    _dustDeepCollectionEquality.hash(_dustSelf.todos),
    _dustSelf.query,
    _dustSelf.filter,
    _dustSelf.isLoading,
    _dustSelf.isRefreshing,
    _dustSelf.isInitialized,
    _dustSelf.errorMessage,
  ]);

  TaskBoardState copyWith({
    List<RemoteTodo>? todos,
    String? query,
    TodoFilter? filter,
    bool? isLoading,
    bool? isRefreshing,
    bool? isInitialized,
    Object? errorMessage = _undefined,
  }) {
    final nextTodos = List<RemoteTodo>.of(
      (todos ?? _dustSelf.todos).map((item_0) => item_0.copyWith()),
    );

    return TaskBoardState(
      todos: nextTodos,
      query: query ?? _dustSelf.query,
      filter: filter ?? _dustSelf.filter,
      isLoading: isLoading ?? _dustSelf.isLoading,
      isRefreshing: isRefreshing ?? _dustSelf.isRefreshing,
      isInitialized: isInitialized ?? _dustSelf.isInitialized,
      errorMessage: identical(errorMessage, _undefined)
          ? _dustSelf.errorMessage
          : errorMessage as String?,
    );
  }
}
