// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// Generated by dust.

part of 'task_board_state.dart';

const Object _undefined = Object();

const DeepCollectionEquality _deepCollectionEquality = DeepCollectionEquality();

mixin _$TaskBoardState {
  @override
  String toString() {
    final self = this as TaskBoardState;
    return 'TaskBoardState('
        'todos: ${self.todos}, '
        'query: ${self.query}, '
        'filter: ${self.filter}, '
        'isLoading: ${self.isLoading}, '
        'isRefreshing: ${self.isRefreshing}, '
        'isInitialized: ${self.isInitialized}, '
        'errorMessage: ${self.errorMessage}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as TaskBoardState;
    return identical(this, other) ||
        other is TaskBoardState &&
            runtimeType == other.runtimeType &&
            _deepCollectionEquality.equals(other.todos, self.todos) &&
            other.query == self.query &&
            other.filter == self.filter &&
            other.isLoading == self.isLoading &&
            other.isRefreshing == self.isRefreshing &&
            other.isInitialized == self.isInitialized &&
            other.errorMessage == self.errorMessage;
  }

  @override
  int get hashCode {
    final self = this as TaskBoardState;
    return Object.hashAll([
      runtimeType,
      _deepCollectionEquality.hash(self.todos),
      self.query,
      self.filter,
      self.isLoading,
      self.isRefreshing,
      self.isInitialized,
      self.errorMessage,
    ]);
  }

  TaskBoardState copyWith({
    List<RemoteTodo>? todos,
    String? query,
    TodoFilter? filter,
    bool? isLoading,
    bool? isRefreshing,
    bool? isInitialized,
    Object? errorMessage = _undefined,
  }) {
    final self = this as TaskBoardState;
    final nextTodos = List<RemoteTodo>.of(
      (todos ?? self.todos).map((item_0) => item_0.copyWith()),
    );

    return TaskBoardState(
      todos: nextTodos,
      query: query ?? self.query,
      filter: filter ?? self.filter,
      isLoading: isLoading ?? self.isLoading,
      isRefreshing: isRefreshing ?? self.isRefreshing,
      isInitialized: isInitialized ?? self.isInitialized,
      errorMessage: identical(errorMessage, _undefined)
          ? self.errorMessage
          : errorMessage as String?,
    );
  }
}
