// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'orders.dart';

Router $ordersRoutes() => Router.module(
      prefix: '',
      routes: [
        Route('GET', '/', _$handleListOrders),
        Route('GET', '/{id}', _$handleReadOrder),
        Route('POST', '/', _$handlePlaceOrder),
        Route('DELETE', '/{id}', _$handleCancelOrder),
      ],
    );

Future<Response> _$handleListOrders(Request request) async {
  final account = await const RequireScope().extract(request);
  if (account case Err(:final error)) return error.intoResponse();
  final account$ = (account as Ok<Account, Rejection>).value;

  final limit = await const QueryExtractable<int?>('limit').extract(request);
  if (limit case Err(:final error)) return error.intoResponse();
  final limit$ = (limit as Ok<int?, Rejection>).value;

  final offset = await const QueryExtractable<int?>('offset').extract(request);
  if (offset case Err(:final error)) return error.intoResponse();
  final offset$ = (offset as Ok<int?, Rejection>).value;

  final repo = await const StateExtractable<OrdersRepo>().extract(request);
  if (repo case Err(:final error)) return error.intoResponse();
  final repo$ = (repo as Ok<OrdersRepo, Rejection>).value;

  return guard(() async {
    final result = await listOrders(account$, limit$, offset$, repo$);
    return switch (result) {
      Ok(:final value) => jsonResponse(value),
      Err(:final error) => error.intoResponse(),
    };
  });
}

Future<Response> _$handleReadOrder(Request request) async {
  final id = await const PathExtractable<int>('id').extract(request);
  if (id case Err(:final error)) return error.intoResponse();
  final id$ = (id as Ok<int, Rejection>).value;

  final account = await const RequireScope().extract(request);
  if (account case Err(:final error)) return error.intoResponse();
  final account$ = (account as Ok<Account, Rejection>).value;

  final repo = await const StateExtractable<OrdersRepo>().extract(request);
  if (repo case Err(:final error)) return error.intoResponse();
  final repo$ = (repo as Ok<OrdersRepo, Rejection>).value;

  return guard(() async {
    final result = await readOrder(id$, account$, repo$);
    return switch (result) {
      Ok(:final value) => jsonResponse(value),
      Err(:final error) => error.intoResponse(),
    };
  });
}

Future<Response> _$handlePlaceOrder(Request request) async {
  final account = await const OrdersWrite().extract(request);
  if (account case Err(:final error)) return error.intoResponse();
  final account$ = (account as Ok<Account, Rejection>).value;

  final repo = await const StateExtractable<OrdersRepo>().extract(request);
  if (repo case Err(:final error)) return error.intoResponse();
  final repo$ = (repo as Ok<OrdersRepo, Rejection>).value;

  final input = await const ValidatedExtractable<NewOrder>(
    JsonExtractable<NewOrder>(NewOrder.deserialize),
  ).extract(request);
  if (input case Err(:final error)) return error.intoResponse();
  final input$ = (input as Ok<NewOrder, Rejection>).value;

  return guard(() async {
    final result = await placeOrder(account$, repo$, input$);
    return switch (result) {
      Ok(:final value) => jsonResponse(value, status: 201),
      Err(:final error) => error.intoResponse(),
    };
  });
}

Future<Response> _$handleCancelOrder(Request request) async {
  final account = await const OrdersWrite().extract(request);
  if (account case Err(:final error)) return error.intoResponse();
  final account$ = (account as Ok<Account, Rejection>).value;

  final id = await const PathExtractable<int>('id').extract(request);
  if (id case Err(:final error)) return error.intoResponse();
  final id$ = (id as Ok<int, Rejection>).value;

  final repo = await const StateExtractable<OrdersRepo>().extract(request);
  if (repo case Err(:final error)) return error.intoResponse();
  final repo$ = (repo as Ok<OrdersRepo, Rejection>).value;

  return guard(() async {
    final result = await cancelOrder(account$, id$, repo$);
    return switch (result) {
      Ok() => noContent(),
      Err(:final error) => error.intoResponse(),
    };
  });
}
