// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'order_model.dart';

mixin _$Order implements Serializable {
  @override
  String toString() {
    final self = this as Order;
    return 'Order('
        'id: ${self.id}, '
        'accountId: ${self.accountId}, '
        'item: ${self.item}, '
        'quantity: ${self.quantity}, '
        'placedAt: ${self.placedAt}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Order;
    return identical(this, other) ||
        other is Order &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.accountId == self.accountId &&
            other.item == self.item &&
            other.quantity == self.quantity &&
            other.placedAt == self.placedAt;
  }

  @override
  int get hashCode {
    final self = this as Order;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.accountId,
      self.item,
      self.quantity,
      self.placedAt,
    ]);
  }

  /// Creates a copy of this `Order` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = order.copyWith(id: 1);
  /// ```
  @pragma('vm:prefer-inline')
  _$OrderCopyWith<Order> get copyWith => _$OrderCopyWithImpl<Order>(this as Order, (value) => value);

  Map<String, Object?> serialize() => _$OrderSerialize(this as Order);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$OrderCopyWith<$Res> {
  $Res call({
    int? id,
    int? accountId,
    String? item,
    int? quantity,
    String? placedAt,
  });
}

/// @nodoc
final class _$OrderCopyWithImpl<$Res> implements _$OrderCopyWith<$Res> {
  const _$OrderCopyWithImpl(this._self, this._then);

  final Order _self;
  final $Res Function(Order) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? id = null,
    Object? accountId = null,
    Object? item = null,
    Object? quantity = null,
    Object? placedAt = null,
  }) {
    return _then(
      Order(
        id: id == null ? _self.id : id as int,
        accountId: accountId == null ? _self.accountId : accountId as int,
        item: item == null ? _self.item : item as String,
        quantity: quantity == null ? _self.quantity : quantity as int,
        placedAt: placedAt == null ? _self.placedAt : placedAt as String,
      )
    );
  }
}
final class $OrderSerializer implements Serializer<Order, Map<String, Object?>> {
  const $OrderSerializer();

  @override
  Map<String, Object?> serialize(Order value) => _$OrderSerialize(value);
}
extension OrderFromRow on Order {
  static Order fromRow(Row row) {
    return Order(
      id: row.read<int>('id'),
      accountId: row.read<int>('account_id'),
      item: row.read<String>('item'),
      quantity: row.read<int>('quantity'),
      placedAt: row.read<String>('placed_at'),
    );
  }
}

/// Row deserializer for [Order].
///
/// Pass it as the `using:` argument of a typed row query, so a row type with
/// no mapping is an analyzer error rather than a failure on the first request.
final class $OrderFromRow implements RowDeserializer<Order> {
  const $OrderFromRow();

  @override
  Order deserialize(Row row) => OrderFromRow.fromRow(row);
}

final bool _$orderFromRowRegistered = registerRowMapper<Order>(OrderFromRow.fromRow);

Map<String, Object?> _$OrderSerialize(Order instance) {
  return <String, Object?>{
    'id': instance.id,
    'accountId': instance.accountId,
    'item': instance.item,
    'quantity': instance.quantity,
    'placedAt': instance.placedAt,
  };
}

Map<String, Object?> _$OrderToJson(Order instance) =>
    _$OrderSerialize(instance);
