// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'product_detail_view_model.dart';

abstract class $ProductDetailViewModel extends ViewModelBase<ProductDetailState, ProductDetailViewModelArgs> {
  $ProductDetailViewModel(super.args) : super(initialState: const ProductDetailState());
  ShoppingRepository get repository => args.repository;
}

class _$ProductDetailViewModelProxy {
  _$ProductDetailViewModelProxy(this._context, this._vm);

  final BuildContext _context;
  final ProductDetailViewModel _vm;

  ProductDetailState get value {
    ProductDetailViewModelScope.of(_context);
    return _vm.value;
  }
}

class ProductDetailViewModelScope extends StatefulWidget {
  const ProductDetailViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
  }) : value = null;

  const ProductDetailViewModelScope.value({
    super.key,
    required ProductDetailViewModel this.value,
    required this.child,
  }) : args = null,
       create = null;

  final ProductDetailViewModelArgs Function(BuildContext context)? args;
  final ProductDetailViewModel Function(BuildContext context, ProductDetailViewModelArgs args)? create;
  final ProductDetailViewModel? value;
  final Widget child;

  static ProductDetailViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_ProductDetailViewModelInherited>()
        ?.widget as _ProductDetailViewModelInherited?;
    if (scope == null) throw StateError('No ProductDetailViewModelScope found in context.');
    return scope.viewModel;
  }

  static ProductDetailViewModel of(BuildContext context, {Object? aspect}) {
    final scope = context.dependOnInheritedWidgetOfExactType<_ProductDetailViewModelInherited>(
      aspect: aspect,
    );
    if (scope == null) throw StateError('No ProductDetailViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<ProductDetailViewModelScope> createState() => _ProductDetailViewModelScopeState();
}

class _ProductDetailViewModelScopeState extends State<ProductDetailViewModelScope> {
  @override
  Widget build(BuildContext context) {
    final external = widget.value;
    return external == null
        ? ViewModelOwner<ProductDetailViewModel, ProductDetailViewModelArgs>(
            debugName: 'ProductDetailViewModelScope',
            args: widget.args!,
            create: widget.create!,
            builder: _buildInherited,
          )
        : ViewModelOwner<ProductDetailViewModel, ProductDetailViewModelArgs>.value(
            debugName: 'ProductDetailViewModelScope.value',
            value: external,
            builder: _buildInherited,
          );
  }

  Widget _buildInherited(BuildContext context, ProductDetailViewModel viewModel) {
    return ListenableBuilder(
      listenable: viewModel,
      builder: (context, child) => _ProductDetailViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: child!,
      ),
      child: widget.child,
    );
  }
}

class _ProductDetailViewModelInherited extends InheritedModel<Object> {
  const _ProductDetailViewModelInherited({required this.viewModel, required this.state, required super.child});

  final ProductDetailViewModel viewModel;
  final ProductDetailState state;

  @override
  bool updateShouldNotify(_ProductDetailViewModelInherited oldWidget) => state != oldWidget.state;

  @override
  bool updateShouldNotifyDependent(_ProductDetailViewModelInherited oldWidget, Set<Object> dependencies) {
    return false;
  }
}

class ProductDetailViewModelListener extends StatefulWidget {
  const ProductDetailViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<ProductDetailViewModelListener> createState() => _ProductDetailViewModelListenerState();
}

class _ProductDetailViewModelListenerState extends State<ProductDetailViewModelListener> {
  StreamSubscription<Object>? _sub;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _sub?.cancel();
    _sub = ProductDetailViewModelScope.read(context).effects.listen((effect) {
      if (mounted) widget.listener(context, effect);
    });
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

extension ProductDetailViewModelBuildContext on BuildContext {
  ProductDetailViewModel get productDetailViewModel => ProductDetailViewModelScope.of(this);

  _$ProductDetailViewModelProxy watchProductDetailViewModel() {
    return _$ProductDetailViewModelProxy(this, ProductDetailViewModelScope.read(this));
  }

  ProductDetailViewModel readProductDetailViewModel() => ProductDetailViewModelScope.read(this);
}
