// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'products_state.dart';

const DeepCollectionEquality _productsStateProductsEquality = DeepCollectionEquality();

mixin _$ProductsState {
  @override
  String toString() {
    final self = this as ProductsState;
    return 'ProductsState('
        'products: ${self.products}, '
        'status: ${self.status}, '
        'errorMessage: ${self.errorMessage}, '
        'selectedCategory: ${self.selectedCategory}, '
        'searchQuery: ${self.searchQuery}, '
        'sortOption: ${self.sortOption}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ProductsState;
    return identical(this, other) ||
        other is ProductsState &&
            runtimeType == other.runtimeType &&
            _productsStateProductsEquality.equals(other.products, self.products) &&
            other.status == self.status &&
            other.errorMessage == self.errorMessage &&
            other.selectedCategory == self.selectedCategory &&
            other.searchQuery == self.searchQuery &&
            other.sortOption == self.sortOption;
  }

  @override
  int get hashCode {
    final self = this as ProductsState;
    return Object.hashAll([
      runtimeType,
      _productsStateProductsEquality.hash(self.products),
      self.status,
      self.errorMessage,
      self.selectedCategory,
      self.searchQuery,
      self.sortOption,
    ]);
  }

  ProductsState copyWith({
    List<Product>? products,
    ProductsStatus? status,
    Option<String?> errorMessage = const None(),
    Option<String?> selectedCategory = const None(),
    String? searchQuery,
    ProductSortOption? sortOption,
  }) {
    final self = this as ProductsState;
    final nextProducts = List<Product>.of(
      (products ?? self.products).map((item_0) => item_0.copyWith()),
    );
    final nextErrorMessage = switch (errorMessage) {
      None<String?>() => self.errorMessage,
      Some<String?>(:final value) => value,
    };
    final nextSelectedCategory = switch (selectedCategory) {
      None<String?>() => self.selectedCategory,
      Some<String?>(:final value) => value,
    };

    return ProductsState(
      products: nextProducts,
      status: status ?? self.status,
      errorMessage: nextErrorMessage,
      selectedCategory: nextSelectedCategory,
      searchQuery: searchQuery ?? self.searchQuery,
      sortOption: sortOption ?? self.sortOption,
    );
  }
}
