import 'dart:async';

import 'package:flutter/material.dart' hide Route;

/// Maximum redirect hops before the router reports a debug-cycle assertion.
const int maxRedirects = 8;

/// Mutable route stack maintained by the generated router delegate.
typedef RouteStack<T extends Object> = List<T>;

/// Converts an incoming browser or platform URI into a typed route object.
typedef RouteParser<T extends Object> = T Function(Uri uri);

/// Builds a Flutter page for one typed route object.
typedef RoutePageBuilder<T extends Object> = Page<void> Function(T route);

/// Resolves route-level guards for one typed route object.
typedef RouteGuardResolver<T extends Object> =
    List<RouteGuard<T>> Function(T route);

/// Converts a typed route object back into a URL location.
typedef RouteLocation<T extends Object> = String Function(T route);

/// Returns whether a route participates in router-level auth checks.
typedef RouteRequiresAuth<T extends Object> = bool Function(T route);

/// Base class for user-owned generated routers.
///
/// Dust generates an app-specific subclass base in `route.g.dart`; the user
/// extends that generated base to provide app dependencies, redirects, guards,
/// and optional refresh behavior.
abstract class DustRouterBase<T extends Object> {
  /// Optional listenable that triggers redirect/guard reevaluation.
  Listenable? get refreshListenable => null;

  /// Returns a replacement route before guards run, or `null` to continue.
  T? redirect(DustRouteState<T> state) => null;

  /// Runs guard handling for the current route state.
  ///
  /// The default implementation executes generated route-level guards from
  /// [DustRouteState.guards]. Override this only for additional app-wide async
  /// checks, and call `super.guard(state)` when route guards should still run.
  Future<RouteGuardResult<T>> guard(DustRouteState<T> state) async {
    return RouteGuardChain<T>(state.guards).canActivate(state);
  }
}

/// Runtime configuration generated for one Dust router.
final class DustRouterConfig<T extends Object> {
  /// Creates a router runtime configuration.
  const DustRouterConfig({
    required this.router,
    required this.initialRoute,
    required this.parseRoute,
    required this.routeLocation,
    required this.requiresAuth,
    required this.resolveGuards,
    required this.buildPage,
  });

  /// User-owned router instance.
  final DustRouterBase<T> router;

  /// Route used when the app starts with no explicit route.
  final T initialRoute;

  /// URI-to-route parser generated by Dust.
  final RouteParser<T> parseRoute;

  /// Route-to-location formatter generated by Dust.
  final RouteLocation<T> routeLocation;

  /// Auth requirement lookup generated by Dust.
  final RouteRequiresAuth<T> requiresAuth;

  /// Route guard lookup generated by Dust.
  final RouteGuardResolver<T> resolveGuards;

  /// Page builder generated by Dust.
  final RoutePageBuilder<T> buildPage;
}

/// Immutable navigation state passed to redirects and guards.
final class DustRouteState<T extends Object> {
  /// Creates a route state snapshot.
  const DustRouteState({
    required this.uri,
    required this.route,
    required this.stack,
    required this.isInitial,
    this.guards = const [],
  });

  /// Parsed URI for [route].
  final Uri uri;

  /// Candidate route being evaluated.
  final T route;

  /// Current navigation stack before [route] is committed.
  final RouteStack<T> stack;

  /// Route-level guards attached to [route].
  final List<RouteGuard<T>> guards;

  /// Whether this navigation is the initial route evaluation.
  final bool isInitial;

  /// String location for [uri].
  String get location => uri.toString();
}

/// Result returned by router and route guard checks.
sealed class RouteGuardResult<T extends Object> {
  /// Creates a guard result.
  const RouteGuardResult();

  /// Allows navigation to continue.
  const factory RouteGuardResult.allow() = RouteGuardAllow<T>;

  /// Blocks navigation without changing the current route.
  const factory RouteGuardResult.block() = RouteGuardBlock<T>;

  /// Redirects navigation to another typed route.
  const factory RouteGuardResult.redirect(T route) = RouteGuardRedirect<T>;
}

/// Route-specific guard contract.
abstract interface class RouteGuard<T extends Object> {
  /// Evaluates whether [state] may be activated.
  Future<RouteGuardResult<T>> canActivate(DustRouteState<T> state);
}

/// Runs route guards in declaration order.
final class RouteGuardChain<T extends Object> {
  /// Creates a guard chain.
  const RouteGuardChain(this.guards);

  /// Guards to run.
  final List<RouteGuard<T>> guards;

  /// Runs guards until one blocks or redirects.
  Future<RouteGuardResult<T>> canActivate(DustRouteState<T> state) async {
    for (final guard in guards) {
      final result = await guard.canActivate(state);
      if (result is! RouteGuardAllow<T>) {
        return result;
      }
    }
    return RouteGuardResult<T>.allow();
  }
}

/// Guard result that allows navigation.
final class RouteGuardAllow<T extends Object> extends RouteGuardResult<T> {
  /// Creates an allow result.
  const RouteGuardAllow();
}

/// Guard result that blocks navigation.
final class RouteGuardBlock<T extends Object> extends RouteGuardResult<T> {
  /// Creates a block result.
  const RouteGuardBlock();
}

/// Guard result that redirects to [route].
final class RouteGuardRedirect<T extends Object> extends RouteGuardResult<T> {
  /// Creates a redirect result.
  const RouteGuardRedirect(this.route);

  /// Replacement route.
  final T route;
}

/// Imperative navigation controller exposed through [DustRouter.of].
final class DustRouterController<T extends Object> {
  DustRouterController._(this._delegate);

  final DustRouterDelegate<T> _delegate;

  /// Top route on the current stack.
  T get currentRoute => _delegate.currentRoute;

  /// Immutable copy of the current stack.
  RouteStack<T> get stack => List.unmodifiable(_delegate.stack);

  /// Replaces the whole stack with [route].
  void go(T route) => _delegate.go(route);

  /// Pushes [route] on top of the current stack.
  void push(T route) => _delegate.push(route);

  /// Replaces the current top route with [route].
  void replace(T route) => _delegate.replace(route);

  /// Pops the top route if possible.
  void pop() => _delegate.popRoute();
}

/// Inherited scope used by generated BuildContext extensions.
class DustRouterScope extends InheritedNotifier<Listenable> {
  /// Creates a router scope.
  const DustRouterScope({
    required this.controller,
    required super.notifier,
    required super.child,
    super.key,
  });

  /// Router controller stored as Object so generated routers can keep T private.
  final Object controller;
}

/// Access point for the nearest Dust router controller.
abstract final class DustRouter {
  /// Returns the nearest typed Dust router controller.
  static DustRouterController<T> of<T extends Object>(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<DustRouterScope>();
    assert(scope != null, 'No DustRouter found in context.');
    return scope!.controller as DustRouterController<T>;
  }
}

/// Navigator 2.0 route information parser for generated Dust routes.
final class DustRouteInformationParser<T extends Object>
    extends RouteInformationParser<T> {
  /// Creates a route information parser.
  const DustRouteInformationParser({
    required this.parseRoute,
    required this.routeLocation,
  });

  /// URI-to-route parser generated by Dust.
  final RouteParser<T> parseRoute;

  /// Route-to-location formatter generated by Dust.
  final RouteLocation<T> routeLocation;

  @override
  Future<T> parseRouteInformation(RouteInformation routeInformation) async {
    return parseRoute(routeInformation.uri);
  }

  @override
  RouteInformation restoreRouteInformation(T configuration) {
    return RouteInformation(uri: Uri.parse(routeLocation(configuration)));
  }
}

/// Internal navigation action mode.
enum NavigationMode { go, push, replace }

/// Navigator 2.0 delegate used by generated Dust routers.
final class DustRouterDelegate<T extends Object> extends RouterDelegate<T>
    with ChangeNotifier, PopNavigatorRouterDelegateMixin<T> {
  /// Creates a router delegate from generated [config].
  DustRouterDelegate(this.config) {
    _controller = DustRouterController<T>._(this);
    stack.add(config.initialRoute);
    _rebuildPageKeyMap();
    config.router.refreshListenable?.addListener(_scheduleRefresh);
    // The initial route is added to the stack before redirect and guard
    // run. The microtask below will re-evaluate and replace it if needed.
    // The page is not built until the first frame, so this is not visible.
    _scheduleRefresh();
  }

  /// Generated router runtime configuration.
  final DustRouterConfig<T> config;

  /// Mutable route stack used by `Navigator.pages`.
  final RouteStack<T> stack = <T>[];
  final Map<Key, int> _keyToStackIndex = <Key, int>{};
  late final DustRouterController<T> _controller;
  bool _refreshScheduled = false;
  int _navigationEpoch = 0;

  T get currentRoute => stack.isEmpty ? config.initialRoute : stack.last;

  @override
  final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

  @override
  T get currentConfiguration => currentRoute;

  @override
  Widget build(BuildContext context) {
    return DustRouterScope(
      controller: _controller,
      notifier: this,
      child: Navigator(
        key: navigatorKey,
        pages: [for (final route in stack) config.buildPage(route)],
        onDidRemovePage: (page) {
          final key = page.key;
          final index = key == null ? null : _keyToStackIndex[key];
          if (index != null && index >= 0 && index < stack.length) {
            stack.removeAt(index);
            _rebuildPageKeyMap();
            notifyListeners();
          }
        },
      ),
    );
  }

  @override
  Future<void> setNewRoutePath(T configuration) {
    return _applyRoute(configuration, NavigationMode.go);
  }

  @override
  Future<bool> popRoute() async {
    if (stack.length <= 1) {
      return false;
    }
    stack.removeLast();
    _rebuildPageKeyMap();
    notifyListeners();
    return true;
  }

  void go(T route) {
    unawaited(_applyRoute(route, NavigationMode.go));
  }

  void push(T route) {
    unawaited(_applyRoute(route, NavigationMode.push));
  }

  void replace(T route) {
    unawaited(_applyRoute(route, NavigationMode.replace));
  }

  @override
  void dispose() {
    config.router.refreshListenable?.removeListener(_scheduleRefresh);
    super.dispose();
  }

  void _scheduleRefresh() {
    if (_refreshScheduled) {
      return;
    }
    _refreshScheduled = true;
    scheduleMicrotask(() {
      _refreshScheduled = false;
      unawaited(_applyRoute(currentRoute, NavigationMode.replace));
    });
  }

  Future<void> _applyRoute(
    T requested,
    NavigationMode mode, {
    bool isInitial = false,
  }) async {
    final epoch = ++_navigationEpoch;
    var candidate = requested;

    var redirects = 0;
    for (; redirects < maxRedirects; redirects += 1) {
      final state = DustRouteState<T>(
        uri: Uri.parse(config.routeLocation(candidate)),
        route: candidate,
        stack: List.unmodifiable(stack),
        isInitial: isInitial,
      );
      final redirected = config.router.redirect(state);
      if (redirected == null ||
          config.routeLocation(redirected) == config.routeLocation(candidate)) {
        break;
      }
      candidate = redirected;
    }
    assert(
      redirects < maxRedirects,
      'Dust router hit the redirect cap ($maxRedirects) navigating to '
      '"${config.routeLocation(requested)}". Check for a redirect cycle.',
    );

    if (epoch != _navigationEpoch) {
      return;
    }

    final guards = config.resolveGuards(candidate);
    final state = DustRouteState<T>(
      uri: Uri.parse(config.routeLocation(candidate)),
      route: candidate,
      stack: List.unmodifiable(stack),
      isInitial: isInitial,
      guards: guards,
    );
    // guard() is intentionally skipped for public routes with no guards.
    // redirect() always runs regardless of auth status. If you need
    // guard-like behaviour on all routes, override guard() and return
    // RouteGuardResult.allow() for public routes explicitly.
    if (config.requiresAuth(candidate) || guards.isNotEmpty) {
      final result = await config.router.guard(state);
      if (epoch != _navigationEpoch) {
        return;
      }
      switch (result) {
        case RouteGuardAllow<T>():
          break;
        case RouteGuardBlock<T>():
          return;
        case RouteGuardRedirect<T>(route: final route):
          await _applyRoute(route, mode, isInitial: isInitial);
          return;
      }
    }

    _commitRoute(candidate, mode);
  }

  void _commitRoute(T route, NavigationMode mode) {
    switch (mode) {
      case NavigationMode.go:
        stack
          ..clear()
          ..add(route);
      case NavigationMode.push:
        stack.add(route);
      case NavigationMode.replace:
        if (stack.isEmpty) {
          stack.add(route);
        } else {
          stack[stack.length - 1] = route;
        }
    }
    _rebuildPageKeyMap();
    notifyListeners();
  }

  void _rebuildPageKeyMap() {
    _keyToStackIndex
      ..clear()
      ..addEntries(
        stack.indexed.map((entry) {
          final (index, route) = entry;
          return MapEntry<Key, int>(_pageKey(route), index);
        }),
      );
  }

  Key _pageKey(T route) => ValueKey<String>(config.routeLocation(route));
}

/// Builds a generated Flutter page for one typed Dust route.
Page<void> generatedPage({
  required String location,
  required String name,
  required Widget child,
  PageTransitionsBuilder? transition,
  bool fullscreenDialog = false,
  bool maintainState = true,
}) {
  return MaterialPage<void>(
    key: ValueKey(location),
    name: name,
    fullscreenDialog: fullscreenDialog,
    maintainState: maintainState,
    child: transition == null
        ? child
        : _RouteTransitionOverride(builder: transition, child: child),
  );
}

class _RouteTransitionOverride extends StatelessWidget {
  const _RouteTransitionOverride({required this.builder, required this.child});

  final PageTransitionsBuilder builder;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Theme(
      data: Theme.of(context).copyWith(
        pageTransitionsTheme: PageTransitionsTheme(
          builders: {
            for (final platform in TargetPlatform.values) platform: builder,
          },
        ),
      ),
      child: child,
    );
  }
}

/// Bottom-to-top page transition for fullscreen dialog routes.
class BottomToTopPageTransitionsBuilder extends PageTransitionsBuilder {
  /// Creates a bottom-to-top page transition builder.
  const BottomToTopPageTransitionsBuilder();

  @override
  Widget buildTransitions<T>(
    PageRoute<T> route,
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
    Widget child,
  ) {
    if (MediaQuery.of(context).disableAnimations) {
      return child;
    }
    return SlideTransition(
      position: Tween<Offset>(
        begin: const Offset(0, 1),
        end: Offset.zero,
      ).animate(CurvedAnimation(parent: animation, curve: Curves.easeOutCubic)),
      child: child,
    );
  }
}
